### ISSUE TITLE
Create folder

### ISSUE THREAD

**Issue by senger1985** [iobroker-community-adapters/ioBroker.hue#103]
**Is your feature request related to a problem? Please describe.**
Create folder for lights and groups

**Describe the solution you'd like**
maybe it would be possible to ask when activating the adapter whether folders should be created for lights and groups.

**Additional context**
see folder structure of the extended adapter

**Comment by foxriver76** [comment]
I don’t see a benefit in the proposed structure. You could just filter the role in admin.

**Comment by senger1985** [comment]
In my opinion, the structure is a little clearer.
But it's okay.
You can close if you want.
