### ISSUE TITLE
"Erstelle User" schlägt fehl

### ISSUE THREAD

**Issue by tepebox** [iobroker-community-adapters/ioBroker.hue#105]
Hallo,

wenn ich auf den Button "Erstelle User" klicke bekomme ich folgende Fehlermeldung:
Fehler beim Anwendererzeugen: {"message":"connect ECONNREFUSED 127.0.0.1:80","name":"Error","stack":"Error: connect ECONNREFUSED 127.0.0.1:80\n at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)","config":{"url":"http:/api/config","method":"get","headers":{"Accept":"application/json, text/plain, */*","User-Agent":"axios/0.19.2"},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1},"code":"ECONNREFUSED"}

Ich musste erst einmal "Speichern und Schließen", damit wohl die IP meiner Bridge gespeichert wurde. Danach konnte ich die Konfiguration neu starten und dann war das "Erstelle User" auch möglich.

Ich verwende Version 3.2.8

**Comment by foxriver76** [comment]
Danke fürs melden, sollte behoben sein in 3.2.9
