### ISSUE TITLE
Changing bri on lightgroups turns them on

### ISSUE THREAD

**Issue by tobiashahner** [iobroker-community-adapters/ioBroker.hue#111]
When changing the brightness of a lightgroup, all lights are turned on before applying the new brightness.
The natural behaviour would be to only apply the new brightness to the already turned-on lights. (Like the bridge does)

**Comment by foxriver76** [comment]
Can't really reproduce this, maybe my eyes are too slow.. lol

Which adapter version? How can I reproduce it?

Ah.. you mean it should not turn the other lights on.. okay this is reproduceable.. 

I think many scripts currently rely on this behaviour, but we can probably connect it with the native turn on behaviour in the adapter settings.

**Comment by tobiashahner** [comment]
A connection to the native turn on behaviour would in fact be a intuitive solution, as it was the first thing i tried to solve the issue :-)

**Comment by foxriver76** [comment]
Please test 3.3.0

I decided to use the following behavior -> when native turn on/off behavior is configured -> no lamp of the group is on -> all will be turned on -> if any is already on -> only change the brightness of already turned on lamps.

Please check if this makes sense for you.
