### ISSUE TITLE
New devices not detected

### ISSUE THREAD

**Issue by mbrammer** [iobroker-community-adapters/ioBroker.hue#112]
After adding the Adapter, all my HUE devices where listed in ioBroker. Now I added a new device (it's active and working in the HUE app), but the device does not appear on the Objects page in ioBraker.
I tried to restart the HUE adapter and also used the device discovery adapter (even if there is no zigbee adapter in it), but the new device does not appear.

**Comment by foxriver76** [comment]
Discovery has nothing to do with it. After restarting the hue adapter new devices should be displayed, have you done a refresh of the admin page?

**Comment by mbrammer** [comment]
Yes, I restarted the Adapter and reloaded the page. It does not appear and is still missing. Also after the adapter update  did today.

**Comment by foxriver76** [comment]
Can you show me a screenshot of the device in the hue app + all adapter objects. Maybe conflicting naming conventions which the adapter isn't able to handle..

**Comment by mbrammer** [comment]
Sure, here you go...

![Screenshot_20200531-120916_Hue](https://user-images.githubusercontent.com/2786547/83349868-2efc3c80-a338-11ea-9ebf-d804adb37748.jpg)

![Bildschirmfoto 2020-05-31 um 12 13 11](https://user-images.githubusercontent.com/2786547/83349866-2e63a600-a338-11ea-888c-5483dce362ad.png)

![Bildschirmfoto 2020-05-31 um 12 13 19](https://user-images.githubusercontent.com/2786547/83349893-64a12580-a338-11ea-976c-8b9a1d372911.png)

**Comment by foxriver76** [comment]
Hm I think the problem is that the sensor has the same name as the room. And the adapter is probably not able to handle it atm. I will look into it.. for now you could rename the sensor. On the other hand it seems to work for 'Wohnzimmer', could you expand the both 'Kinderzimmer' channels and show a screenshot.

**Comment by foxriver76** [comment]
And please delete the room which is named 'Kinderzimmer' (not 'Kinderzimmer_Room' once). And then please show a log from instance restart.

**Comment by mbrammer** [comment]
I saw you already comitted a new version with a fix. The update id currently not appearing in my iobroker, so I can't test it yet.
Do you still want to have the screenshots?

**Comment by foxriver76** [comment]
3.3.3 should be available in latest repository. I guess when you delete the room as mentioned above, the sensor will be created correctly. But with the new version a scenario like yours should not happen again.
