### ISSUE TITLE
Problem nach Update von 3.3.2 auf 3.3.3

### ISSUE THREAD

**Issue by mp-itconsulting** [iobroker-community-adapters/ioBroker.hue#116]
Seit dem Update auf 3.3.3 besteht speziell bei den Hue-Plugs das Problem, dass beim Adapterstart ein neuer Objekt erstellt wird, z.B.

Es existiert "Deckenlicht"

Beim Adapterstart wird eine bereits existierende ID hierfür als Problem gemeldet und ein neuer Baum mit Namen "Deckenlicht_hue_...." angelegt (ich weiß den Suffix nicht mehr genau). Danach laufen dann auch einige Skripte nicht mehr, weil die Objektzuordnungen nicht mehr stimmen.

Lösche ich dagegen "Deckenlicht" und starte den Adapter neu, wird ein Baum "Deckenlicht" angelegt und die Skripte laufen wie gewohnt.

Wenn ich den Adapter jetzt jedoch wieder neu starte (oder den iobroker), wird wieder das existierende Objekt "Deckenlicht" als Problem gemeldet und "Deckenlicht_hue_..." wird wieder angelegt bzw. verwenden. D.h. selbst wenn aber das Objekt Deckenlicht_hue_..." existiert, wird es nicht als bereits existierend moniert sondern genutzt. Das Problem mit den existierenden Id's tritt nur bei den Objekten ohne den Suffix (also Namen wie in der App) auf.

Dieses Verhalten tritt wie o.g. nur bei den Hue-Steckdosen auf, jedoch nicht bei Lampen oder Dimmer/Schaltern. Ich habe dann letztendlich ein Downgrade auf 3.3.2 vorgenommen und der Fehler ist wieder weg.

Als Workaround kann man natürlich beide Objektbäume stehen lassen und nur den mit dem Suffix nutzen, ist aber unschön (und erfordert Überarbeitung der Skripte).

Gruß
M.P.

**Comment by foxriver76** [comment]
Kannst du mir mal ein Screenshot des channels eines Plugs zeigen, bzw role wäre wichtig

**Comment by foxriver76** [comment]
I assume role is switch

**Comment by mp-itconsulting** [comment]
Thx for the quick fix. Your assumption was right. Role = "switch". Works like a charme.

**Comment by foxriver76** [comment]
Danke fürs Feedback. :+1:
