### ISSUE TITLE
umbenennen der Lampen, alte Datenpunkte müssen manuell gelöscht werden

### ISSUE THREAD

**Issue by ruhr70** [iobroker-community-adapters/ioBroker.hue#12]
Wenn man in hue die Lampen oder Gruppen löscht oder umbenennt, bleiben die alten Datenpunkte erhalten.

**Comment by JanJohansen** [comment]
I can confirm the issue.
Is this intended?

**Comment by GermanBluefox** [comment]
It is not the issue, it's a feature

чт, 28 июн. 2018 г., 18:10 Jan Johansen <notifications@github.com>:

**Comment by JanJohansen** [comment]
Thats what VW said...

Schönes Wochenende... ;O)
