### ISSUE TITLE
Ergänzung der Temperatur aus Bewegungsmelder

### ISSUE THREAD

**Issue by Azathoth88** [iobroker-community-adapters/ioBroker.hue#130]
Über den Hue-Bewegungsmelder kann die Temperatur erfasst werden. Die Funktion ist versteckt abrufbar.
`{"state":{"temperature":2579,"lastupdated":...
`
Es wäre schön, wenn die Temperatur standardmäßig als Objekt abrufbar wäre.
Derzeit verwende ich hierfür ein Skript:

//Bad Temp Sensor
schedule("*/5 * * * *", function () { // Abfrage alle 1 Min
	var url = "http://192.168.178.5/api/...../sensors/24";
	var request = require("request");
	request(url, function (error, response, body) {
	var json = JSON.parse(body);
	var Temperatur = parseInt(json.state.temperature);
	Temperatur = Temperatur/100;
  	setState("ManuelleVariablen.0.Hue_Badezimmer_Temperatur", Temperatur); // Anpassen auf deinen erstellten Datenpunkt
  	});
});

**Comment by foxriver76** [comment]
Der Adapter sollte ein extra Objekt für den Temperatursensor anlegen, da dieser innerhalb der Bridge als Extra Sensor gehandhabt wird. Bei mir heißt dieser z. B. `hue.0.Hue_temperature_sensor_1`
