### ISSUE TITLE
Philips Hue dimmer switch press does change switch.lastupdated but not switch.buttonevent

### ISSUE THREAD

**Issue by mtoensing** [iobroker-community-adapters/ioBroker.hue#139]
**Describe the bug**
If the Philips Hue dimmer switch is pressed there is no change in switch.buttonevent visible. Only the time stamp in switch.lastupdated changes. There does not seem to be a way to get the current button event. 

**To Reproduce**
1. Pair the Philips Hue dimmer switch with hue bridge
2. Install ioBroker Philips Hue Bridge adapter 
3. Pair the bridge with iobroker to controls lights.
4. Press a button on the hue dimmer switch
5. switch.buttonevent is always empty.

<img width="877" alt="Screen Shot 2020-10-11 at 17 12 11" src="https://user-images.githubusercontent.com/136737/95682337-f1ac9300-0be4-11eb-9cfb-326395d56497.png">

**Expected behavior**
switch.buttonevent show the event.

**Versions:**
 - Adapter version:  3.3.5
 - JS-Controller version: <js-controller-version>
 - Node version: v12.18.3
 - Operating system: Linux (Docker)
 - Bridge model: recent

**logs**

hue.0 | 2020-10-11 17:09:12.046 | warn | (1662) Changed buttonevent of sensor 17 to 1002 - currently not supported
-- | -- | -- | --
host.iobroker5 | 2020-10-11 17:05:27.432 | info | Update repository "default" under "http://download.iobroker.net/sources-dist.json"
info.0 | 2020-10-11 17:04:02.784 | info | (156) Popup news was read...
hue.0 | 2020-10-11 16:44:40.982 | warn | (1662) Changed buttonevent of sensor 17 to 0 - currently not supported
hue.0 | 2020-10-11 16:41:02.086 | warn | (1662) Changed buttonevent of sensor 17 to 0 - currently not supported
hue.0 | 2020-10-11 16:40:54.877 | error | (1662) Cannot update sensor 17: Error: parameter, alert, not available: /sensors/17/config
hue.0 | 2020-10-11 16:40:51.276 | error | (1662) Cannot update sensor 17: Error: parameter, alert, not available: /sensors/17/config
hue.0 | 2020-10-11 16:40:49.399 | error | (1662) Cannot update sensor 17: Error: parameter, alert, not available: /sensors/17/config
hue.0 | 2020-10-11 16:40:48.512 | error | (1662) Cannot update sensor 17: Error: parameter, alert, not available: /sensors/17/config
hue.0 | 2020-10-11 16:39:50.120 | info | (1662) creating/updating bridge device

**Comment by foxriver76** [comment]
I cannot reproduce it with my Hue Dimmer Switch, please not rely on admin tab only, better use a script or the cli. Admin often has caching problems and tends to not update some values.

**Comment by mtoensing** [comment]
I will provide an onchange script test then.

**Comment by mtoensing** [comment]
```
on('hue.0.switch.buttonevent', function (obj) {
 log(obj.state.val);
 log("changed");
});
```

Ok, it works: 

19:41:07.713 | info | javascript.0 (1632) script.js.common.Badezimmersteuerung.huetest: 4002
19:41:07.713 | info | javascript.0 (1632) script.js.common.Badezimmersteuerung.huetest: changed
19:41:18.328 | info | javascript.0 (1632) script.js.common.Badezimmersteuerung.huetest: 1002
19:41:18.328 | info | javascript.0 (1632) script.js.common.Badezimmersteuerung.huetest: changed

But with a huge delay of 1 to 2 seconds. Is this normal?

**Comment by foxriver76** [comment]
Yes, the Hue API needs to be polled. You can configure the interval in the adapter settings, however minimum is 2 seconds.
