### ISSUE TITLE
Sync new scenes afterwards

### ISSUE THREAD

**Issue by karsten089** [iobroker-community-adapters/ioBroker.hue#141]
How can I sync new created scenes to ioBroker?
Setup works perfectly and all „buttons“ for my hue scenes are available, but when I create new scenes within the hue app on iOS, the new scene does not show up under my objects. How to sync?

**Comment by foxriver76** [comment]
Normal scenes should pop up in the related room after adapter restart

**Comment by karsten089** [comment]
Thanks. So easy... :-)
