### ISSUE TITLE
Hue Adapter starts to switch by itself

### ISSUE THREAD

**Issue by freaktech** [iobroker-community-adapters/ioBroker.hue#149]
Hallo!

I use the latest version.

When i push the button multiple times, the adapter starts to switch by itself

any ideas what is wrong?

here you can see the problem

https://youtu.be/a-rtB2UGm9E

thank you tom

**Comment by foxriver76** [comment]
Which state is linked to that button, `on` state of a bulb? How is the polling interval configured? Maybe you have a script which triggers this behavior?

**Comment by freaktech** [comment]
Hallo!

the state is

hue.0.Philips_hue.Esszimmer.on


<img width="906" alt="Bildschirmfoto 2020-11-23 um 23 07 31" src="https://user-images.githubusercontent.com/33237257/100020815-c373c300-2de0-11eb-84c8-bc6f08b15993.png">

**Comment by foxriver76** [comment]
Ok, schaut unkritisch aus. Nochmal das Problem: Du schaltest die Lampe an und der Switch geht wieder auf aus? Die Lampe ist jedoch an? Wird sie denn währendessen in der Hue App als an angezeigt? Ansonsten evtl. da Synchro-Probleme. Und sonst mal schauen ob es an Visu liegt oder auch im Objekte Tab im Admin das Szenario ist. Und sonst mal checken ob iwelche Skripte den Datenpunkt verwenden.

**Comment by freaktech** [comment]
Es viel mir gestern auf als ich die Optik der VIS überarbeitet habe.

Ich klick einfach schnell hintereinander ein paar mal auf den Schalter und plötzlich beginnt dieser sich dauern selbst ein/aus zuschalten.

Das geht Minutenlang so weiter Obst irgendwann aufhört kann ich nicht sagen ich hab dann den Adapter gestoppt und neu gestartet und es passte wieder.

Hatte auch zum Test einen andere Schalter Widget genommen, das gleiche.

lg
tom

**Comment by foxriver76** [comment]
Also ich kann das nicht nachstellen, sobald ich aufhöre hin und her zu wechseln ändert sich nichts mehr an den States. Einziger Unterschied - mein Polling Intervall steht auf 2 Sekunden. Daran sollte es allerdings nicht liegen. Wie gesagt, mal die oberen Punkte durchgehen, vorallem wenn es nur an der Visualisierung liegt, kann der Adapter nix dafür. Daher die Punkte durchgehen und nach Möglichkeit ausschließen.

**Comment by freaktech** [comment]
Ansonsten evtl. da Synchro-Probleme. Und sonst mal schauen ob es an Visu liegt oder auch im Objekte Tab im Admin das Szenario ist. Und sonst mal checken ob iwelche Skripte den Datenpunkt verwenden.

Datenpunkte verwende ich keine die diese Lampe schalten.

schauen ob es an Visu liegt    ist für mich schwierig damit was anzufangen
es kann natürlich sein dass die VIS das xxx fach sendet wenn man schnell 4-5 mal draufdrückt   das geht dann sicher 30 x on/off ?!?

wenn ich auf den Button einen shelly lege statt ein HUE passt alles.

dass sich der Adapter da wo in ne Schleife verhängt? denn es geht auch weiter wenn ich das VIS Fenster im Browser zumache
klar die vis am Server läuft dadurch weiter

komische Sache

**Comment by foxriver76** [comment]
Na mit Visu ausschließen meine ich schauen ob das auch passiert wenn du auf eine andere Art schaltest, z. B. Admin. Debug Log wenn das passiert wäre noch ne Möglichkeit, was zu sehen ob der Adapter da tatsächlich hin und her switched.

**Comment by freaktech** [comment]
ich habe nun testweise auf den hue extended adapter umgestellt und dort ist dieser Fehler nicht bei mir

**Comment by foxriver76** [comment]
Wie gesagt die Infos sind mau, ich kann es bei mir nicht nachstellen.
