### ISSUE TITLE
js-controller 3.2.x - has no existing object - Osram smart+ Steckdose

### ISSUE THREAD

**Issue by Feuer-sturm** [iobroker-community-adapters/ioBroker.hue#155]
Beim Beta Test vom js-controller 3.2.x (in diesem Fall 3.2.5) gab es folgende Warnung. Philips Hue Bridge Adapter v3.3.8

Im Einsatz sind zwei Osram smart+ Steckdosen, welche an die HUE Bridge angelernt sind.
Die Steckdosen haben andere Datenpunkte als z.B. ein Leuchtmittel.
 
```
hue.0 | 2021-01-10 22:00:00.511 | warn | (2268) State "hue.0.Weihnachten_Küche.bri" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-10 22:00:00.494 | warn | (2268) State "hue.0.Steckdose-Musikbox.bri" has no existing object, this might lead to an error in future versions
```

![grafik](https://user-images.githubusercontent.com/25422320/104135435-c4f94a80-5390-11eb-8aa1-a276d2858ac8.png)

**Comment by sigi2345** [comment]
Schließe mich an Version  3.2.6.0


hue.0 | 2021-01-10 23:49:21.484 | warn | (8516) State "hue.0.Philips_hue_Entertainment-Bereich_3.allOn" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
hue.0 | 2021-01-10 23:49:21.482 | warn | (8516) State "hue.0.Philips_hue_Entertainment-Bereich_3.anyOn" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-10 23:49:21.468 | warn | (8516) State "hue.0.Philips_hue_Alle.allOn" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-10 23:49:21.461 | warn | (8516) State "hue.0.Philips_hue_Entertainment-Bereich_2.allOn" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-10 23:49:21.459 | warn | (8516) State "hue.0.Philips_hue_Entertainment-Bereich_2.anyOn" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-10 23:49:21.443 | warn | (8516) State "hue.0.Philips_hue_Entertainment-Bereich_1.allOn" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-10 23:49:21.441 | warn | (8516) State "hue.0.Philips_hue_Entertainment-Bereich_1.anyOn" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-10 23:49:21.423 | warn | (8516) State "hue.0.Philips_hue_Küche.allOn" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-10 23:49:21.421 | warn | (8516) State "hue.0.Philips_hue_Küche.anyOn" has no existing object, this might lead to an error in future versions

`

**Comment by foxriver76** [comment]
@sigi2345 existieren die Objekte? Was sind das für channel Typen? Evtl mal Screenshot. Logging nur beim Start oder regelmäßig?

@Feuer-sturm Osram Plugs muss ich schauen, villt habe ich iwo einen rumfliegen zum testen. Logging nur beim Start oder regelmäßig?

**Comment by foxriver76** [comment]
@Feuer-sturm für dich sollte 3.3.9 es fixen,  von @sigi2345 bräuchte ich die Infos

**Comment by sigi2345** [comment]
> @sigi2345 existieren die Objekte? Was sind das für channel Typen? Evtl mal Screenshot. Logging nur beim Start oder regelmäßig?
> 

Fehler kommen jetzt nicht mehr mit V 3.2.6.0

**Comment by sigi2345** [comment]
Kommt doch wieder.

**Comment by foxriver76** [comment]
Daher bitte die oberen Fragen beantworten

**Comment by sigi2345** [comment]
> @sigi2345 existieren die Objekte?
Ja

 Was sind das für channel Typen?
?

 Evtl mal Screenshot. 

![Screenshot (3092)](https://user-images.githubusercontent.com/41079106/104226665-7909dc80-5448-11eb-8c33-2eb6d4e66f47.png)


![Screenshot (3094)](https://user-images.githubusercontent.com/41079106/104226876-c8500d00-5448-11eb-9215-82d7e21d9bd6.png)


Logging nur beim Start oder regelmäßig?

Regelmässig

**Comment by foxriver76** [comment]
Ah.. iwie wird da für die beiden States `anyOn` und `allOn` die id falsch gebaut

`hue.0.Philips_hue_Entertainment-Bereich_3.anyOn` statt `hue.0.Philips_hue.Entertainment-Bereich_3.anyOn`

**Comment by foxriver76** [comment]
3.3.10 fixt das nun auch

**Comment by Feuer-sturm** [comment]
Habe auf 3.3.10 aktualisiert. Werde es beobachten. Beim ersten Schalten gab es keine Warnungen.

**Comment by sigi2345** [comment]
Habe auf 3.3.10 aktualisiert.
`

hue.0 | 2021-01-11 23:43:59.842 | warn | (11068) State "hue.0.Büro.allOn" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
hue.0 | 2021-01-11 23:43:59.840 | warn | (11068) State "hue.0.Büro.anyOn" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:43:59.829 | warn | (11068) State "hue.0.Büro.level" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:43:59.825 | warn | (11068) State "hue.0.Büro.bri" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:43:59.822 | warn | (11068) State "hue.0.Büro.on" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:40:57.718 | warn | (11068) State "hue.0.Entertainment-Bereich_3.allOn" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:40:57.715 | warn | (11068) State "hue.0.Entertainment-Bereich_3.anyOn" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:40:57.711 | warn | (11068) State "hue.0.Entertainment-Bereich_3.level" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:40:57.707 | warn | (11068) State "hue.0.Entertainment-Bereich_3.b" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:40:57.704 | warn | (11068) State "hue.0.Entertainment-Bereich_3.g" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:40:57.701 | warn | (11068) State "hue.0.Entertainment-Bereich_3.r" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:40:57.695 | warn | (11068) State "hue.0.Entertainment-Bereich_3.bri" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:40:57.692 | warn | (11068) State "hue.0.Entertainment-Bereich_3.on" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:40:57.680 | warn | (11068) State "hue.0.Entertainment-Bereich_2.allOn" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:40:57.669 | warn | (11068) State "hue.0.Entertainment-Bereich_2.anyOn" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:40:57.665 | warn | (11068) State "hue.0.Entertainment-Bereich_2.level" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:40:57.663 | warn | (11068) State "hue.0.Entertainment-Bereich_2.b" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:40:57.660 | warn | (11068) State "hue.0.Entertainment-Bereich_2.g" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:40:57.658 | warn | (11068) State "hue.0.Entertainment-Bereich_2.r" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:40:57.653 | warn | (11068) State "hue.0.Entertainment-Bereich_2.bri" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:40:57.651 | warn | (11068) State "hue.0.Entertainment-Bereich_2.on" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:40:57.649 | warn | (11068) State "hue.0.Entertainment-Bereich_1.allOn" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:40:57.646 | warn | (11068) State "hue.0.Entertainment-Bereich_1.anyOn" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:40:57.644 | warn | (11068) State "hue.0.Entertainment-Bereich_1.level" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:40:57.641 | warn | (11068) State "hue.0.Entertainment-Bereich_1.b" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:40:57.639 | warn | (11068) State "hue.0.Entertainment-Bereich_1.g" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:40:57.637 | warn | (11068) State "hue.0.Entertainment-Bereich_1.r" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:40:57.633 | warn | (11068) State "hue.0.Entertainment-Bereich_1.bri" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:40:57.630 | warn | (11068) State "hue.0.Entertainment-Bereich_1.on" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:40:57.628 | warn | (11068) State "hue.0.Küche.allOn" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:40:57.626 | warn | (11068) State "hue.0.Küche.anyOn" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:40:57.623 | warn | (11068) State "hue.0.Küche.level" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:40:57.621 | warn | (11068) State "hue.0.Küche.b" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:40:57.618 | warn | (11068) State "hue.0.Küche.g" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:40:57.615 | warn | (11068) State "hue.0.Küche.r" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:40:57.612 | warn | (11068) State "hue.0.Küche.bri" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:40:57.610 | warn | (11068) State "hue.0.Küche.on" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:40:37.394 | warn | (11068) State "hue.0.Entertainment-Bereich_3.level" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:40:37.390 | warn | (11068) State "hue.0.Entertainment-Bereich_3.b" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:40:37.387 | warn | (11068) State "hue.0.Entertainment-Bereich_3.g" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:40:37.384 | warn | (11068) State "hue.0.Entertainment-Bereich_3.r" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:40:37.379 | warn | (11068) State "hue.0.Entertainment-Bereich_3.bri" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:40:37.360 | warn | (11068) State "hue.0.Entertainment-Bereich_2.level" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:40:37.358 | warn | (11068) State "hue.0.Entertainment-Bereich_2.b" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:40:37.355 | warn | (11068) State "hue.0.Entertainment-Bereich_2.g" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:40:37.353 | warn | (11068) State "hue.0.Entertainment-Bereich_2.r" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:40:37.349 | warn | (11068) State "hue.0.Entertainment-Bereich_2.bri" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:40:37.345 | warn | (11068) State "hue.0.Entertainment-Bereich_1.level" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:40:37.343 | warn | (11068) State "hue.0.Entertainment-Bereich_1.b" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:40:37.341 | warn | (11068) State "hue.0.Entertainment-Bereich_1.g" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:40:37.338 | warn | (11068) State "hue.0.Entertainment-Bereich_1.r" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:40:37.335 | warn | (11068) State "hue.0.Entertainment-Bereich_1.bri" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:40:37.332 | warn | (11068) State "hue.0.Küche.level" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:40:37.330 | warn | (11068) State "hue.0.Küche.b" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:40:37.328 | warn | (11068) State "hue.0.Küche.g" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:40:37.326 | warn | (11068) State "hue.0.Küche.r" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:40:37.322 | warn | (11068) State "hue.0.Küche.bri" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:56.196 | warn | (11068) State "hue.0.Entertainment-Bereich_3.ct" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:56.194 | warn | (11068) State "hue.0.Entertainment-Bereich_3.xy" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:56.188 | warn | (11068) State "hue.0.Alle.xy" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:56.175 | warn | (11068) State "hue.0.Entertainment-Bereich_2.ct" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:56.171 | warn | (11068) State "hue.0.Entertainment-Bereich_2.xy" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:56.160 | warn | (11068) State "hue.0.Entertainment-Bereich_1.ct" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:56.157 | warn | (11068) State "hue.0.Entertainment-Bereich_1.xy" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:56.148 | warn | (11068) State "hue.0.Küche.ct" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:56.146 | warn | (11068) State "hue.0.Küche.xy" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:35.895 | warn | (11068) State "hue.0.Entertainment-Bereich_3.allOn" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:35.893 | warn | (11068) State "hue.0.Entertainment-Bereich_3.anyOn" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:35.890 | warn | (11068) State "hue.0.Entertainment-Bereich_3.level" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:35.888 | warn | (11068) State "hue.0.Entertainment-Bereich_3.b" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:35.886 | warn | (11068) State "hue.0.Entertainment-Bereich_3.g" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:35.883 | warn | (11068) State "hue.0.Entertainment-Bereich_3.r" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:35.880 | warn | (11068) State "hue.0.Entertainment-Bereich_3.ct" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:35.878 | warn | (11068) State "hue.0.Entertainment-Bereich_3.xy" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:35.875 | warn | (11068) State "hue.0.Entertainment-Bereich_3.bri" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:35.873 | warn | (11068) State "hue.0.Entertainment-Bereich_3.on" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:35.868 | warn | (11068) State "hue.0.Alle.xy" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:35.863 | warn | (11068) State "hue.0.Entertainment-Bereich_2.allOn" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:35.861 | warn | (11068) State "hue.0.Entertainment-Bereich_2.anyOn" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:35.858 | warn | (11068) State "hue.0.Entertainment-Bereich_2.level" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:35.856 | warn | (11068) State "hue.0.Entertainment-Bereich_2.b" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:35.853 | warn | (11068) State "hue.0.Entertainment-Bereich_2.g" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:35.851 | warn | (11068) State "hue.0.Entertainment-Bereich_2.r" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:35.848 | warn | (11068) State "hue.0.Entertainment-Bereich_2.ct" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:35.846 | warn | (11068) State "hue.0.Entertainment-Bereich_2.xy" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:35.843 | warn | (11068) State "hue.0.Entertainment-Bereich_2.bri" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:35.841 | warn | (11068) State "hue.0.Entertainment-Bereich_2.on" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:35.838 | warn | (11068) State "hue.0.Entertainment-Bereich_1.allOn" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:35.836 | warn | (11068) State "hue.0.Entertainment-Bereich_1.anyOn" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:35.833 | warn | (11068) State "hue.0.Entertainment-Bereich_1.level" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:35.831 | warn | (11068) State "hue.0.Entertainment-Bereich_1.b" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:35.829 | warn | (11068) State "hue.0.Entertainment-Bereich_1.g" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:35.826 | warn | (11068) State "hue.0.Entertainment-Bereich_1.r" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:35.823 | warn | (11068) State "hue.0.Entertainment-Bereich_1.ct" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:35.820 | warn | (11068) State "hue.0.Entertainment-Bereich_1.xy" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:35.816 | warn | (11068) State "hue.0.Entertainment-Bereich_1.bri" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:35.814 | warn | (11068) State "hue.0.Entertainment-Bereich_1.on" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:35.810 | warn | (11068) State "hue.0.Küche.allOn" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:35.808 | warn | (11068) State "hue.0.Küche.anyOn" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:35.804 | warn | (11068) State "hue.0.Küche.level" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:35.801 | warn | (11068) State "hue.0.Küche.b" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:35.799 | warn | (11068) State "hue.0.Küche.g" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:35.796 | warn | (11068) State "hue.0.Küche.r" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:35.793 | warn | (11068) State "hue.0.Küche.ct" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:35.790 | warn | (11068) State "hue.0.Küche.xy" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:35.786 | warn | (11068) State "hue.0.Küche.bri" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:35.783 | warn | (11068) State "hue.0.Küche.on" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:15.507 | warn | (11068) State "hue.0.Büro.allOn" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:15.504 | warn | (11068) State "hue.0.Büro.anyOn" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:15.502 | warn | (11068) State "hue.0.Büro.level" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:15.499 | warn | (11068) State "hue.0.Büro.bri" has no existing object, this might lead to an error in future versions
hue.0 | 2021-01-11 23:38:15.495 | warn | (11068) State "hue.0.Büro.on" has no existing object, this might lead to an error in future versions

`
