### ISSUE TITLE
Please escape %

### ISSUE THREAD

**Issue by RP70DP** [iobroker-community-adapters/ioBroker.hue#165]
`2021-02-18 13:05:09.324 - warn: hue.0 (3295) Used invalid characters: hue.0.Philips_hue.Wohnzimmer_100％_Medium.lastupdated changed to hue.0.Philips_hue.Wohnzimmer_100__Medium.lastupdated`

JS-Controller: 3.2.16

**Comment by foxriver76** [comment]
![Bildschirmfoto von 2021-02-18 13-28-08](https://user-images.githubusercontent.com/25484431/108357440-b9017380-71ed-11eb-8f12-e10e5b724883.png)
![Bildschirmfoto von 2021-02-18 13-28-30](https://user-images.githubusercontent.com/25484431/108357450-bbfc6400-71ed-11eb-8152-549f12cf0bb6.png)

Lol ;-)
