### ISSUE TITLE
Warnung nach update auf js-controller 3.2

### ISSUE THREAD

**Issue by michi-68** [iobroker-community-adapters/ioBroker.hue#167]
Hallo,
nach dem update auf js-controller 3.2.16 kommt folgende Warnung
hue.1	2021-02-19 20:53:07.734	warn	(11111) State "hue.1.Philips_hue1.TV_Steckdose.bri" has no existing object, this might lead to an error in future versions
ist eine Osram Smart+ Plug Steckdose

beim schalten von Lampen kommt keine Warnung

Update hue from @3.4.0 to @3.5.0 habe ich mal gemach hat aber nicht geholfen

Raspbeery 4
Node.js 12.20.2
npm 6.14.11
js-controller 3.2.16

edit:
js-controller 3.2.16 meine ich natürlich

**Comment by foxriver76** [comment]
Sollte eigentlich gefixt sein siehe https://github.com/iobroker-community-adapters/ioBroker.hue/issues/155

Falls du von GitHub geupgradet hast bitte Upload machen, sonst bitte mehr Infos wie regelmäßig kommt das logging - bei polling? Existiert der Channel etc.

**Comment by michi-68** [comment]
Hallo,
Fehler tritt nur auf wenn ich die Steckdosen an oder aus mache, sonst nicht
Steckdose geht auch an und aus
Existiert der Channel, den verstehe ich nicht sorry

Polling steht auf 3 sek
habe eine PhilipsHue Bridge

es geht sonst alles Lampen an, aus, dimmen, farbe,

update hab ich über den admin gemacht, latest
jetzt noch mal über die Katze
upload gemacht

hue.1	2021-02-20 00:12:51.842	warn	(21023) State "hue.1.Philips_hue1.Fire_TV_Steckdose.bri" has no existing object, this might lead to an error in future versions

immer noch die Warnung
Raspberry Neustart
immer noch die Warnung
link von github
immer noch die Warnung
hue.1	2021-02-20 00:27:14.388	warn	(5918) State "hue.1.Philips_hue1.Fire_TV_Steckdose.bri" has no existing object, this might lead to an error in future versions

wenn du mehr infos brauchst sag mir gerne welche und wo ich die finde hab leider nicht ganz so viel ahnung

Edit:
meinst du das mit channel

hue.1	2021-02-20 00:36:56.849	info	(30759) created/updated 123 scenes
hue.1	2021-02-20 00:36:56.827	info	(30759) created/updated 25 groups channels
hue.1	2021-02-20 00:36:56.789	info	(30759) created/updated 33 light channels
hue.1	2021-02-20 00:36:56.726	info	(30759) created/updated 16 sensor channels

**Comment by foxriver76** [comment]
Mal Screenshot vom `hue.1.Philips_hue1.Fire_TV_Steckdose` Objekt und mal bitte sagen ob natives einschaltverhalten in den adapter Einstellungen an oder aus ist.

**Comment by michi-68** [comment]
so ich hab es rausbekommen, habe auch in der Alexa app den Hue Skill und der schaltet die Steckdose ein und aus wenn ich den smartNamen in Iobroker ändere und dann nicht Fire TV an sage sondern Fire TV Steckdose geht es ohne Fehlermeldung. 
natives einschaltverhalten ist aus

![firetv01](https://user-images.githubusercontent.com/74839473/108575916-07ad2b80-731c-11eb-9632-a120a5dd6ab6.png)
![firetv02](https://user-images.githubusercontent.com/74839473/108575930-0c71df80-731c-11eb-8613-0ae5809f89b5.png)

**Comment by michi-68** [comment]
natives einschaltverhalten hab ich jetzt mal an gemacht, und wieder auf Fire TV umbenannt und siehe das es geht. Sorry manchmal kann es so einfach sein.
Ist das Peinlich, ich mach dann zu erledigt

**Comment by foxriver76** [comment]
Hm bin mir nicht sicher aber okay du schaltest einen Room, und der hat nen on state aber kein bri.. könnte im Adapter das Handling noch fehlen.. ich schaue die Tage nochmal.

**Comment by michi-68** [comment]
Vielen Dank noch für die schnelle Hilfe, wenn ich noch was Testen soll oder du noch einen Screenshot brauchst einfach bescheid sagen.
Und noch mal vielen Dank
