### ISSUE TITLE
Feller Smart Light Schalter

### ISSUE THREAD

**Issue by Kusi-Schweiz** [iobroker-community-adapters/ioBroker.hue#178]
Heute habe ich einen "Feller" Schalter (mit 4 Tasten) mit der Hue-Bridge verbunden und nutze nun so sämtliche Tasten in den Skripten. Mir ist aufgefallen, dass sich der Datenpunkt "last button event" nicht "aktualisiert", wenn dieselbe Taste mehrmals hintereinander gedrückt wird. Die benötige ich aber, um eine Lampe/Steckdose mit nur einer Taste ein- und ausschalten zu können.

Im Moment habe ich dies gelöst, indem das Skript auf die Aktualisierung von "last updated" reagiert.

Kann dies geändert werden?

**Comment by foxriver76** [comment]
Wenn du innerhalb des poll Intervalls mehrmals den Taster drückst ist das mit der hue api leider nicht erkennbar. Also sowas wie Doppelklick kann man leider nicht abgreifen insofern es da kein vorgefertigten state in der api gibt.

**Comment by Kusi-Schweiz** [comment]
Danke für die rasche Antwort. Ich meine NICHT den Doppelklick. Ich kann auch nach 2 Minuten nochmals dieselbe Taste drücken,  "last updated" aktualisiert sich, "last button event" jedoch nicht.

Mir wäre sowieso lieber gewesen, ich könnte den Feller Smart Light Schalter über DeConz Conbee einbinden, aber dies funktioniert nicht.

**Comment by foxriver76** [comment]
Ja, der Hue Adapter aktualisiert States nur, wenn sich diese auch ändern.

https://github.com/iobroker-community-adapters/ioBroker.hue/blob/184fab3b0a80e32484d0f02e540bfd66dde0e774/main.js#L1630

Grundsätzlich spart das sehr viel Schreiblast für die DB, gerade da viele den Hue Adapter aufgrund des Designfehlers der API mit sehr niedrigem Pollintervall laufen haben. In dem Fall ist deine Vorgehensweise also die Korrekte, weiß jetzt ad-hoc auch nicht ob ich das ändern würde.

Wie heißt denn das Event bei deinem Schalter? Bei den Hue Dimmer Switches heißt es `buttonevent`.

**Comment by Kusi-Schweiz** [comment]
Ich habe mein Polling auf 2 Sekunden. Hat es denn einen Nachteil, wenn der DP oft geschrieben/aktualisiert wird?

**Comment by foxriver76** [comment]
Ne, wg einem DP ists net schlimm, können den hinzufügen. Daher mein Frage:

> Wie heißt denn das Event bei deinem Schalter? Bei den Hue Dimmer Switches heißt es buttonevent.

**Comment by Kusi-Schweiz** [comment]
Anbei die Datenpunkte:
![image](https://user-images.githubusercontent.com/71840093/115085540-fe4ed280-9f0a-11eb-9edc-39794ff7814f.png)

**Comment by foxriver76** [comment]
Ah edit: ich hatte einen Denkfehler, wie anfangs gesagt, geht ja gar nicht. Wir fragen bei der Hue API alle States ab, da bekommen wir jetzt buttontype z. B. 21 aber ob dieser seit dem letzten Poll gedrückt wurde, oder nicht sehen wir ja nicht wirklich, daher wieder nur sehr umständlich möglich nämlich über das lastupdated event..
