### ISSUE TITLE
wrong type in some datapoints?

### ISSUE THREAD

**Issue by BramTown** [iobroker-community-adapters/ioBroker.hue#181]
since update to ioBroker js-controller v3.3.1 there were some warn messages regarding the values

```
hue.0 | 2021-04-30 09:27:18.937 | warn | (1425) State value to set for "hue.0.Philips_hue.BWM_Nebeneingang_Light.lightlevel" has value "31252" greater than max "17000"
-- | -- | -- | --
hue.0 | 2021-04-30 09:26:43.328 | warn | (1425) State value to set for "hue.0.Philips_hue.Hue_outdoor_ambient_light_sensor.lightlevel" has value "35517" greater than max "17000"

```
may there has to be something corrected to this datapoints during installation?

**Comment by foxriver76** [comment]
Thanks for reporting.

**Comment by foxriver76** [comment]
not sure what the acutally max is of lightlevel, so I do some research or will remove it, was added in https://github.com/iobroker-community-adapters/ioBroker.hue/commit/cf0026cb1481089008867ac5f7c8bf0711248fce by @robbsta, idk where the information of a max of 17k came from.

**Comment by foxriver76** [comment]
I guess it's value is in Lux and thus not have a formal `max`

**Comment by foxriver76** [comment]
fixed in https://github.com/iobroker-community-adapters/ioBroker.hue/commit/7357bf3b2b29a7944faabec8f15b9d0b3de09e32
