### ISSUE TITLE
JS-Controller 3.3 - is missing the required property "common.type"

### ISSUE THREAD

**Issue by kueppert** [iobroker-community-adapters/ioBroker.hue#182]
hue.0 | 2021-04-30 10:05:57.686 | warn | (18475) Object of state "hue.0.roomstate.status" is missing the required property "common.type"
hue.0 | 2021-04-30 10:05:03.356 | warn | (18475) Object of state "hue.0.roomstate.status" is missing the required property "common.type"
hue.0 | 2021-04-30 10:04:47.097 | warn | (18475) Object of state "hue.0.Keller.allOn" is missing the required property "common.type"
hue.0 | 2021-04-30 10:04:47.043 | warn | (18475) Object of state "hue.0.Keller.anyOn" is missing the required property "common.type"
hue.0 | 2021-04-30 10:04:46.761 | warn | (18475) Object of state "hue.0.presenceState.status" is missing the required property "common.type"
hue.0 | 2021-04-30 10:04:46.712 | warn | (18475) Object of state "hue.0.roomstate.status" is missing the required property "common.type"

**Comment by foxriver76** [comment]
Can you at first please try to recreate the states, by deleting the affected once. The `type: 'state'` should be there, at least in my installation, but I will look a bit deeper inside the code.

**Comment by foxriver76** [comment]
Edit.. common.type okay will look again

**Comment by foxriver76** [comment]
fixed in https://github.com/iobroker-community-adapters/ioBroker.hue/commit/7357bf3b2b29a7944faabec8f15b9d0b3de09e32

**Comment by foxriver76** [comment]
Bitte testen ob mit 3.5.10 die Probleme behoben sind.

**Comment by Feuer-sturm** [comment]
@foxriver76 Leider noch nicht. Ich hab mal ein neues issue aufgemacht https://github.com/iobroker-community-adapters/ioBroker.hue/issues/184
