### ISSUE TITLE
Protect the user token

### ISSUE THREAD

**Issue by klein0r** [iobroker-community-adapters/ioBroker.hue#185]
Consider to add protectedNative / encryptedNative attributes to io-package.json

```
    "protectedNative": [
        "user"
    ],
    "encryptedNative": [
        "user"
    ],
```

https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/adaptersecurity.md

**Comment by foxriver76** [comment]
Not really sensitive, but can be done

**Comment by Apollon77** [comment]
... but would be a breaking change!

**Comment by foxriver76** [comment]
Yes, users will have to create the user again, good point

**Comment by foxriver76** [comment]
But protected can be done ;-)

**Comment by klein0r** [comment]
Maybe just add `protectedNative` to avoid breaking change?

**Comment by foxriver76** [comment]
This is done on master.

**Comment by foxriver76** [comment]
We can also implement it when we have other breaking changes, however in the current situation I don't want to annoy the users further because the situation is already tensed due to the controller release and the corresponding log messages.
