### ISSUE TITLE
Object of state "hue.0.Wohnzimmer.scene_xx" is missing the required property "common.type

### ISSUE THREAD

**Issue by Feuer-sturm** [iobroker-community-adapters/ioBroker.hue#189]
js-controller 3.3.8
Admin 5.0.15

Im Log taucht bei mir folgende Warnung auf:
` javascript.0 (10826) Object of state "hue.0.Wohnzimmer.scene_tv_schauen" is missing the required property "common.type"`

Ich hab ein Skript welches den Datenpunkt mit true beschreibt:
```
const DP_HueSzeneTvSchauen = "hue.0.Wohnzimmer.scene_tv_schauen";


//Wenn der Fernseher eingeschaltet wird, wird die Szene zum TV Schauen eingeschaltet
on({id: DP_SamsungTV_isOn, value: "on"}, function(obj){

    setState(DP_HueSzeneTvSchauen,true);

});
```

common.type fehlt bei allen Datenpunkten hue.0.Wohnzimmer.scene_xxxxx

**Comment by foxriver76** [comment]
Danke fürs Melden - 3.5.16 sollte die Eigenschaft `common.type` ergänzen

**Comment by Feuer-sturm** [comment]
Warnung ist mit 3.5.16 weg.
Danke.
