### ISSUE TITLE
Incorrect min max values for ct

### ISSUE THREAD

**Issue by DrBakterius** [iobroker-community-adapters/ioBroker.hue#192]
I recently started getting the following error message in the ioBroker log:

`State value to set for "hue.0.name.ct" has value "2000" less than min "2179"`

The following limit values are specified by default in the adapter's data point:

    "min": 2179,
    "max": 6536,

However, the range is different depending on the lamp. For example, the innr smart bulb color has a range of 1800 to 6500 Kelvin. The original colored lamps from Philips range from 2000 to 6500 Kelvin.

Is it possible to change the limit range or remove it completely to prevent such incorrect entries in the log?

**Comment by foxriver76** [comment]
In a Perfect World we could detect which values are possible for each light. Let’s wait for an answer https://github.com/peter-murray/node-hue-api/issues/199 before implementing a suboptimal workaround.

**Comment by DrBakterius** [comment]
What happens if you control a lamp with a value outside its capabilities? If it simply ignores the command or takes the highest or lowest value it can handle, you don't have to limit it in the adapter.

**Comment by foxriver76** [comment]
min/max of the object is more meant for visualization adapters, thus I would appreciate if we are able to find the correct values

**Comment by DrBakterius** [comment]
Understand.

What happens currently when a value is written out of bounds? Is it still set, ignored or corrected?

**Comment by foxriver76** [comment]
Converted: https://github.com/iobroker-community-adapters/ioBroker.hue/blob/5a685765c426cbb363d34685cd44c56087d67866/main.js#L367

**Comment by foxriver76** [comment]
Some kind of legacy code so idk what happens if we set outside the valid range. You could outcomment the line and try

**Comment by DrBakterius** [comment]
Line 367 only?

**Comment by foxriver76** [comment]
I think so.

**Comment by DrBakterius** [comment]
Does not change anything. I set the values 'xy' by command (e.g. {"transitiontime":4, "xy": "1,0.3", "level":100}) or by Alexa. Does this change anything?

Wir können gerne auch auf deutsch weiter schreiben... ;-)

**Comment by foxriver76** [comment]
Dachte du wolltest `ct` auf einen Wert größer/kleiner der alten definierten min/max setzen? ;-)

Dann wäre interessant ob er darauf reagiert und was letztendlich gesetzt wird. Ich nutze den Adapter selbst nur sehr oberflächlich, unterstütze allerdings gerne bei Bedarf um den Adapter besser zu machen.

**Comment by DrBakterius** [comment]
Nein, 'ct' wird dabei automatisch mit verändert (Rückmeldung von der Bridge?) und dabei im Log der Fehler ausgegeben.

Setze ich den 'ct' direkt z.B. auf 300, wird der auf 2198 geändert und im Log der Fehler ausgegeben. Wenn ich die Änderung in VIS über den Colorpicker mache, wird ct nach einiger Zeit auf z.B. 2007 geändert und es folgt der Fehler. Mit Alexa ändere ich die Farbe auf rot, nach einigen Sekunden wird ct auf 1802 geändert und im Log wieder der Fehler.

Kommt die Änderung also über die Hue-Bridge, könnte man den Wert ignorieren. Wird er vom User geändert, wird er auf gültige Werte innerhalb der Grenzen geändert. In beiden Fällen ist eine Fehlerausgabe IMHO unnötig.

**Comment by foxriver76** [comment]
> Setze ich den 'ct' direkt z.B. auf 300, wird der auf 2198 geändert

Mit geändert meinst du du bekommst 2919 und ack true dann zurück von der Bridge? Dass er bei dem Setzen von 300 jammert im Log ist klar, solange das Minimum darüber liegt. Evtl konvertiert auch der Code nochmal, um zu sehen was die Brdige direkt liefert mal auf Debug schalten, dann sollte man das hier sehen können.

https://github.com/iobroker-community-adapters/ioBroker.hue/blob/5a685765c426cbb363d34685cd44c56087d67866/main.js#L1673 Das ist alles was von der Bridge kommt unverändert durch unseren Code.

**Comment by foxriver76** [comment]
> Kommt die Änderung also über die Hue-Bridge, könnte man den Wert ignorieren. Wird er vom User geändert, wird er auf gültige Werte innerhalb der Grenzen geändert. In beiden Fällen ist eine Fehlerausgabe IMHO unnötig.

Die Fehlerausgabe kommt vom Controller - sprich setzt du den Wert erstmal unter min generiert dies schon eine Ausgabe bevor ich den Wert überhaupt zur Verarbeitung bekomme -> folglich meine Ursprungsaussage -> Way to go ist, die korrekten min/max Werte heraus zu finden.

**Comment by DrBakterius** [comment]
Wenn ich den 'ct' direkt ändere, wird der Wert korrigiert falls er zu niedrig ist. Sieht im Log so aus:

```
2021-05-21 16:24:58.069 -&nbsp;warn: admin.0 (324) State value to set for "hue.0.Arbeitszimmer.ct" has value "1800" less than min "2179"
--
2021-05-21 16:24:58.079 -&nbsp;debug: hue.0 (30473) stateChange hue.0.Arbeitszimmer.ct {"val":1800,"ack":false,"ts":1621607098076,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1621607098076}
2021-05-21 16:24:58.110 -&nbsp;debug: hue.0 (30473) final lightState for Arbeitszimmer:{"bri":254,"on":true,"ct":455,"colormode":"ct","level":100}
2021-05-21 16:24:58.270 -&nbsp;debug: hue.0 (30473) polling group Arbeitszimmer (6)
2021-05-21 16:24:58.298 -&nbsp;debug: hue.0 (30473) Unblock Arbeitszimmer
2021-05-21 16:24:58.347 -&nbsp;debug: hue.0 (30473) updated group state (6) after change
```

Wenn ich das Licht per Alexa ändere, kommt mit dem Polling der Bridge der geänderte Wert (der auch tatsächlich ansteht), in die Datenpunkte und es wird eben der Logeintrag gesetzt.

Schon klar, dass da nicht der Adapter sondern der Controller schreit. Aber man könnte kurzfristig abhelfen indem man die Standardwerte auf den niedrigsten bzw. höchsten bekannten Wert setzt. Soviel ich gefunden habe auf 1800 bzw 6500 K. Die korrekten Werte für alle unterschiedlichen Leuchtmittel ist dann der "Goldstandard".

Ich setze das Logging des Adapters inzwischen auf Error, dann bleiben mir die unnötigen Warnungen erspart.

**Comment by foxriver76** [comment]
Also ich erkenne im Log nichts was auf eine Korrektur hindeutet, der Controller ändert die Werte nicht ab. Der stateChange kommt mit 1800 am Adapter an, was die Bridge daraus macht ist leider im geposteten Log nicht zu sehen.

Ja, kann man als kurzfristigen Workaround tun, allerdings macht die Warnung absolut nichts (Werte werden hierdurch nicht verändert) und ich warte lieber ein paar Tage ob eine Antwort auf mein erstelltes Issue kommt, bevor ich hier jetzt hin und her ändere ;-)

**Comment by DrBakterius** [comment]
Der Wert wird im Datenpunkt geändert auch wenn im Log nichts zu sehen ist. Aber vielen Dank für deine Mühe und da ich den 'ct' sowieso nicht direkt ändere, kann ich gut abwarten. ;-)

**Comment by foxriver76** [comment]
Ja, weil kein poll all zwischendrin stattgefunden hat, beim einzelnen Gruppen poll wird wohl nix geloggt. Aber ja ist unwichtig, ich weiß was zu tun ist.
