### ISSUE TITLE
v3.5.15 : The id "hue.0." is invalid. Ids are not allowed to end in "." 

### ISSUE THREAD

**Issue by texiuozelotl** [iobroker-community-adapters/ioBroker.hue#196]
Moin,

ich habe zwei Hue Bridges. Seit dem Upgrade des Adapters auf 3.5.15 kann ich die erste Instanz (0) nicht mehr starten. Die zweite instanz (1) startet problemlos. Im Log sehe ich: 

The id "hue.0." is invalid. Ids are not allowed to end in "." 

Ich habe versucht die erste 0er Instanz zu löschen und wieder neu hinzu zu fügen, erhalte dann aber die gleiche Fehelrmeldung.

**Logfile**
host.iobroker-0	2021-05-26 12:29:02.970	info	Restart adapter system.adapter.hue.0 because enabled
host.iobroker-0	2021-05-26 12:29:02.970	error	instance system.adapter.hue.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.iobroker-0	2021-05-26 12:29:02.970	error	Caught by controller[1]: at Object.main [as ready] (/opt/iobroker/node_modules/iobroker.hue/main.js:1932:5)
host.iobroker-0	2021-05-26 12:29:02.970	error	Caught by controller[1]: at connect (/opt/iobroker/node_modules/iobroker.hue/main.js:1583:5)
host.iobroker-0	2021-05-26 12:29:02.970	error	Caught by controller[1]: at syncObjects (/opt/iobroker/node_modules/iobroker.hue/main.js:1594:35)
host.iobroker-0	2021-05-26 12:29:02.970	error	Caught by controller[1]: at Adapter.getForeignObjectAsync (/opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1568:16)
host.iobroker-0	2021-05-26 12:29:02.970	error	Caught by controller[1]: at new Promise (<anonymous>)
host.iobroker-0	2021-05-26 12:29:02.970	error	Caught by controller[1]: at /opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1569:16
host.iobroker-0	2021-05-26 12:29:02.970	error	Caught by controller[1]: at Adapter.getForeignObject (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:2942:17)
host.iobroker-0	2021-05-26 12:29:02.970	error	Caught by controller[1]: at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:532:23)
host.iobroker-0	2021-05-26 12:29:02.970	error	Caught by controller[1]: Error: The id "hue.0." is invalid. Ids are not allowed to end in "."
host.iobroker-0	2021-05-26 12:29:02.969	error	Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejecte
hue.0	2021-05-26 12:29:02.427	warn	(27051) Terminated (UNCAUGHT_EXCEPTION): Without reason
hue.0	2021-05-26 12:29:02.427	info	(27051) terminating
hue.0	2021-05-26 12:29:02.427	info	(27051) cleaned everything up...
hue.0	2021-05-26 12:29:02.410	error	(27051) The id "hue.0." is invalid. Ids are not allowed to end in "."
hue.0	2021-05-26 12:29:02.409	error	at Object.main [as ready] (/opt/iobroker/node_modules/iobroker.hue/main.js:1932:5)
hue.0	2021-05-26 12:29:02.409	error	at connect (/opt/iobroker/node_modules/iobroker.hue/main.js:1583:5)
hue.0	2021-05-26 12:29:02.409	error	at syncObjects (/opt/iobroker/node_modules/iobroker.hue/main.js:1594:35)
hue.0	2021-05-26 12:29:02.409	error	at Adapter.getForeignObjectAsync (/opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1568:16)
hue.0	2021-05-26 12:29:02.409	error	at new Promise (<anonymous>)
hue.0	2021-05-26 12:29:02.409	error	at /opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1569:16
hue.0	2021-05-26 12:29:02.409	error	at Adapter.getForeignObject (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:2942:17)
hue.0	2021-05-26 12:29:02.409	error	at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:532:23)
hue.0	2021-05-26 12:29:02.409	error	(27051) Error: The id "hue.0." is invalid. Ids are not allowed to end in "."
hue.0	2021-05-26 12:29:02.405	error	(27051) unhandled promise rejection: The id "hue.0." is invalid. Ids are not allowed to end in "."
hue.0	2021-05-26 12:29:02.405	error	(27051) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
hue.0	2021-05-26 12:29:01.450	info	(27051) creating/updating bridge device
hue.0	2021-05-26 12:29:01.450	info	(27051) created/updated 174 scenes
hue.0	2021-05-26 12:29:01.434	info	(27051) created/updated 21 groups channels

**Versions:**
 - Adapter version: 3.5.15
 - JS-Controller version: 3.2.16
 - Node version: 14.16.0
 - Operating system: ubuntu 20.04
 - Bridge model: 2

**Comment by foxriver76** [comment]
3.5.17 should not crash, however I can only guess that you have a nameless light or something like that

**Comment by texiuozelotl** [comment]
yep, that's it: In the hue app I named a switch "???". That caused the issue. Thanks a lot :-)
