### ISSUE TITLE
Losing bridge user

### ISSUE THREAD

**Issue by neo4a** [iobroker-community-adapters/ioBroker.hue#198]
Host version: 3.3.11 Hue version: 3.5.17, 3.5.19

The adapter configuration loses the entered value for the bridge user "after some time", but always within 24 h.

Reinstalling the instance, creating a new user or entering an already created user works immediately. But after some time the value is empty again, there is an error entry and the adapter is functionless.

Update: Restarting an ioBroker instance will cause loosing bridge user id in config. As soon as admin panel is avaiable and hue adapter instance is not started yet last bridge user entry is shown in config screen. But right after auto start of hue adapter bridge user entry is gone and must be re-assigned in order to get a working instance.

This behavior is reproducable in my environment by simply call "iobroker stop" & "iobroker start".

HTH.

**Comment by foxriver76** [comment]
You have pretty much a script which sets the `system.adapter.instance` object which will delete the key

**Comment by neo4a** [comment]
@foxriver76: Not that I'm aware of.

My ioBroker instance is running on a Windows 10 VM that recieved a system update recently. No idea about dependencies but at the moment I'm not able to update adapters from admin page (get a npm msg about locked files) so I update ioBroker via cmd line (iobroker stop; update; upgrade [self]; start;).

Maybe this causes some conflicts in the start routine of hue adapter, too?!

    Windows
Betriebssystem
    win32
Architektur
    x64
CPUs
    2
Geschwindigkeit
    3293 MHz
Modell
    Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz
RAM
    4 GB
System Betriebszeit
    00:00:16
Node.js
    v14.17.0 (Empfohlene Version v12.22.1)
NPM
    6.14.13
Anzahl der Adapter
    418
Festplatte Größe
    126.4 GB
Festplatte frei
    61.38 GB
Betriebszeit
    06:06:14
Aktive Instanzen
    23

**Comment by foxriver76** [comment]
The problem looks very familiar to me, because recently the user attribute has been protected, which means it will be removed from the object. If you now get the `system.adapter.hue.0` object you will receive it without the `user` attribute and if you now set it back, then it the attribute is of course missing. Thus, please check if you have a script which restarts the adapter or multiple adapters in this fashion you should adapt it, e. g. using `extendObject('system.adapter.hue.0', {'common': {'enabled': true}})`. So please check your scripts first.

**Comment by neo4a** [comment]
Sorry. My mistake. I overlooked a running script. Have no idea if it's even necessary anymore.

> function _restartAdapter(aAdapter)
{
    var obj = getObject(aAdapter);
    obj.common.enabled = !obj.common.enabled;  
    setObject(aAdapter, obj);
    if (!obj.common.enabled){
        setTimeout(function(){_restartAdapter(aAdapter)}, 1 * 60 * 1000);
    }
}
schedule('5 1 * * *', function()
{
  _restartAdapter("system.adapter.hue.0")
});
// Test
  _restartAdapter("system.adapter.hue.0")


If I start ioBroker the test call of restarting script is running which causes the problem. 

So thank you for your help.
