### ISSUE TITLE
Error on command "ct"

### ISSUE THREAD

**Issue by PrintSeb** [iobroker-community-adapters/ioBroker.hue#204]
Hallo,
habe ein kleines Problem, evtl. kann , mir jemand einen Tipp geben oder helfen.
Ich habe das Problem, wenn ich über die command funktion z.b "ct":"3500" beutze bekomme ich einen error (Invalid "ct" value "{"ct":"3500"}").
Gebe ich ein ct_inc geht es!

**Comment by foxriver76** [comment]
Hab jetzt nicht im Code geschaut aber übergebe mal bitte eine Number und kein String

**Comment by PrintSeb** [comment]
Oh mist , Vielen dank, hab grad im Code gesehen, dass es ab 5.2 als error kommt wenn’s keine Nummer is…  

„ if (typeof ls.ct !== 'number') {
                     adapter.log.error(`Invalid "ct" value "${state.val}" (type: ${typeof ls.ct}) for id "${id}"`);
                     return;
                 }“

Danke bin voll auf dem Schlauch gestanden
