### ISSUE TITLE
State value to set for "hue.0.Custom_group_for_$lights_LightGroup.ct" has value "2000" less than min "2179"

### ISSUE THREAD

**Issue by Homeworker11** [iobroker-community-adapters/ioBroker.hue#216]
Admin  v5.1.23
Hue v3.5.19
JS v12.21.0
NPM 6.14.11

Adapter neu gestartet
Gruppe neu angelegt
Iobroker neu gestartet

Errorlog
![image](https://user-images.githubusercontent.com/74406135/128886664-0de1706f-b47a-449e-9b5f-dd1fa2a75e5a.png)

**Comment by SliX185** [comment]
@foxriver76 
Don't want to open a new issue, but i got pretty much the same errors in my log...
It's an "innr e14 colour" lamp

![Unbenannt](https://user-images.githubusercontent.com/47434006/148661060-a0cc8255-0542-4b8e-9556-ed72aabf1d8c.JPG)

https://github.com/iobroker-community-adapters/ioBroker.hue/blob/4174bfac57853b5015c585aba356fbfaf0cbb1a2/main.js#L1417

changing the value of `gobj.common.min` to `1800 ` would work for me.

`gobj.common.min = 1800;`

**Comment by foxriver76** [comment]
hm okay so fallback ct needs to be even lower

**Comment by foxriver76** [comment]
controlling the light directly so without a group shows no problems? So can you show min/max of the light ct object

**Comment by SliX185** [comment]
I'm getting the error controlling the light with my HUE Android App. When i come below ct value 2000, i'll got that error in log. (Adapter is polling -> spitting errors under value 2000, no matter how or what is controlling the light)

The object min/max values of the light self, are right. No, issues with that.
```
{
  "_id": "hue.0.innr_e14_color.ct",
  "type": "state",
  "common": {
    "name": "innr e14 color.ct",
    "read": true,
    "write": true,
    "type": "number",
    "role": "level.color.temperature",
    "unit": "°K",
    "min": 1802,
    "max": 6536,
    "def": 1802
  },
```

Schönen Sonntag noch!
