### ISSUE TITLE
No value provided and 'light id' is not optional

### ISSUE THREAD

**Issue by sigi2345** [iobroker-community-adapters/ioBroker.hue#221]
Hallo,

bekomme folgenden Fehler:

`
<html>
<body>

hue.0 | 2021-08-12 13:53:39.321 | error | Could not set LightState of Philips hue.Büro: Error: No value provided and 'light id' is not optional
-- | -- | -- | --

</body>
</html>`

Hatte bis jetzt immer funktioniert?

RAW vom DP

`{
  "_id": "hue.0.Philips_hue.Büro.on",
  "type": "state",
  "common": {
    "name": "Philips hue.Büro.on",
    "read": true,
    "write": true,
    "type": "boolean",
    "role": "switch",
    "def": false,
    "custom": {
      "eventlist.0": {
        "enabled": true,
        "event": "Licht Büro ",
        "changesOnly": false,
        "defaultMessengers": true,
        "color": "rgba(150,144,144,1)",
        "icon": "data:image/svg+xml;base64, PHN2ZyBpZD0iQ2VpbGluZyBsYW1wIiBlbmFibGUtYmFja2dyb3VuZD0ibmV3IDAgMCA1MTIgNTEyIiBoZWlnaHQ9IjUxMiIgdmlld0JveD0iMCAwIDUxMiA1MTIiIHdpZHRoPSI1MTIiDQogICAgIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+DQogICAgPGcgZmlsbD0iY3VycmVudENvbG9yIj4NCiAgICAgICAgPHBhdGggZD0ibTMwMy42ODUgMTI2Ljc5MmMyMC42OC0xMTAuNzk1IDE5LjMxNS0xMDIuODUgMTkuMzE1LTEwNC44NjkgMC0xMi40OTgtMTEuNjA4LTIxLjkyMy0yNy0yMS45MjNoLTgwYy0xOC4yNjMgMC0yOC45NTIgMTIuODI3LTI2Ljc0NiAyNC42NzVsMTkuMDYgMTAyLjExN2MtODguMDE1IDIxLjcxMS0xNTEuMzE0IDEwMC43NTctMTUxLjMxNCAxOTMuMjA4IDAgOC4yODQgNi43MTYgMTUgMTUgMTVoODIuMDk2YzcuMjg0IDQ5LjcxIDUwLjIwNCA4OCAxMDEuOTA0IDg4IDUxLjY5OSAwIDk0LjYxOS0zOC4yOSAxMDEuOTA0LTg4IC4xNDEgMCA4Mi4yNzYgMCA4Mi4xMTkgMCA4LjI2Ny0uMDEzIDE0Ljk2NC02LjcxIDE0Ljk3Ny0xNC45NzcuMTQtOTEuMzctNjIuMzk1LTE3MS4yOTctMTUxLjMxNS0xOTMuMjMxem0tNjUuOTM0LTUuNzkyLTE2Ljk4NS05MWg3MC40NjdsLTE2Ljk4NSA5MXptMTUyLjIzMSA5NmgtMjY3Ljk2NWM2Ny41NjMtODcuODM5IDIwMC4yMy04OC4wNjIgMjY3Ljk2NSAwem0tMTMzLjk4MiAxNzZjLTM1LjExMyAwLTY0LjUxNS0yNC45MTgtNzEuNDUxLTU4aDE0Mi45MDJjLTYuOTM2IDMzLjA4Mi0zNi4zMzkgNTgtNzEuNDUxIDU4em0tMTY4LjMzMy04OGMxLjc5My0yMC4xMzYgNy4xOC0zOS44NDEgMTUuODczLTU4aDMwNC45MThjOC42OTMgMTguMTU5IDE0LjA4IDM3Ljg2NCAxNS44NzMgNTgtMTUuMjAxIDAtMzIxLjI4IDAtMzM2LjY2NCAweiIvPg0KICAgICAgICA8cGF0aCBkPSJtMjU2IDQ1N2MtOC4yODQgMC0xNSA2LjcxNi0xNSAxNXYyNWMwIDguMjg0IDYuNzE2IDE1IDE1IDE1czE1LTYuNzE2IDE1LTE1di0yNWMwLTguMjg0LTYuNzE2LTE1LTE1LTE1eiIvPg0KICAgICAgICA8cGF0aCBkPSJtMzUzLjQ3IDQzNi4xNDZjLTMuMDc2LTcuNjkxLTExLjgwMi0xMS40MzQtMTkuNDk4LTguMzU1LTcuNjkxIDMuMDc3LTExLjQzMyAxMS44MDctOC4zNTUgMTkuNDk4bDguOTE0IDIyLjI4M2MyLjM0NiA1Ljg2NSA3Ljk3OSA5LjQzMyAxMy45MzIgOS40MzMgMTAuNTQxIDAgMTcuODc2LTEwLjY5MSAxMy45MjItMjAuNTc1eiIvPg0KICAgICAgICA8cGF0aCBkPSJtMTc4LjAyNyA0MjcuNzljLTcuNjkyLTMuMDc5LTE2LjQyMS42NjUtMTkuNDk4IDguMzU2bC04LjkxMyAyMi4yODNjLTMuOTQ4IDkuODY5IDMuMzYxIDIwLjU3NCAxMy45MjIgMjAuNTc0IDUuOTUzIDAgMTEuNTg2LTMuNTY4IDEzLjkzMi05LjQzNGw4LjkxMy0yMi4yODNjMy4wNzctNy42OS0uNjY0LTE2LjQyLTguMzU2LTE5LjQ5NnoiLz4NCiAgICA8L2c+DQo8L3N2Zz4=",
        "states": [
          {
            "val": "false",
            "text": "Licht Büro wurde ausgeschaltet",
            "color": "default",
            "icon": "default"
          },
          {
            "val": "true",
            "text": "Licht Büro wurde eingeschaltet",
            "color": "default",
            "icon": "default"
          }
        ]
      },
      "material": {
        "admin": {
          "enabled": false,
          "name": "Philips hue"
        }
      }
    }
  },
  "native": {
    "id": "6"
  },
  "from": "system.adapter.hue.0",
  "user": "system.user.admin",
  "ts": 1628695253590,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`

`Plattform: Windows
RAM: 16 GB 
Node.js: 12.22.5
NPM: 6.14.14
JS Controller: 3.3.15
Admin: 5.1.24
Web: 3.4.9
Socket.io: 3.1.4
Script Engine: 5.2.8
IOT: 1.8.22
VIS: 1.4.3
HM-Rega: 3.0.31
HM-RPC: 1.14.43
Jarvis: 3.0.0
Backitup: 2.1.16
Cloud: 4.1.0
ICal: 1.11.3
iQontrol: 1.8.2
fb-checkpresence: 1.1.5
Hue: 3.5.22
Alexa2: 3.9.3
Material UI: 1.0.4
E-Charts: 1.0.2
Info: 1.9.7
UPnP: 1:0:19`

**Comment by foxriver76** [comment]
Welche Version und wie kommt es zum Fehler?

**Comment by sigi2345** [comment]
> Welche Version und wie kommt es zum Fehler?

Hue: 3.5.22, kommt immer.

Das Widget dazu:

`[{"tpl":"i-vis-universal","data":{"g_fixed":true,"g_visibility":false,"g_css_font_text":false,"g_css_background":false,"g_css_shadow_padding":false,"g_css_border":false,"g_gestures":false,"g_signals":false,"g_last_change":false,"visibility-cond":"==","visibility-val":1,"visibility-groups-action":"hide","iUniversalWidgetType":"Switch","iValueType":"boolean","iStateResponseTime":"0","iNavWait":"100","iButtonCol":"","iButtonActive":"","iOpacityBack":"1","iCornerRadiusUL":"0","iCornerRadiusUR":"0","iCornerRadiusLR":"0","iCornerRadiusLL":"0","iContentFlexDirection":"vertical","iContentVertAlign":"iSpace-between","iContentOrder":"orderTextImg","iOpacityCtn":"1","iTextColor":"{vis-inventwo.0.CSS.Text}","iTextSize":"12","iTextAlign":"iCenter","iTextSpaceTop":"0","iTextSpaceBottom":"0","iTextSpaceLeft":"0","iTextSpaceRight":"0","iIconSize":"70","iImgAlign":"iCenter","iImgSpaceTop":"5","iImgSpaceBottom":"0","iImgSpaceLeft":"0","iImgSpaceRight":"0","iImgRotation":"0","iImgBlinkFalse":"0","iImgBlinkTrue":"0","iShadowXOffset":"0","iShadowYOffset":"0","iShadowBlur":"4","iShadowSpread":"5","iShadowColor":"#111111","iShadowColorActive":"#111111","iShadowInnerXOffset":"0","iShadowInnerYOffset":"0","iShadowInnerBlur":"0","iShadowInnerSpread":"0","iShadowInnerColor":"#111111","iShadowInnerColorActive":"#111111","iBorderSize":"1","iBorderStyle":"solid","iBorderColor":"#c70000","iBorderColorActive":"#00cc1a","signals-cond-0":"==","signals-val-0":true,"signals-icon-0":"/vis/signals/lowbattery.png","signals-icon-size-0":0,"signals-blink-0":false,"signals-horz-0":0,"signals-vert-0":0,"signals-hide-edit-0":false,"signals-cond-1":"==","signals-val-1":true,"signals-icon-1":"/vis/signals/lowbattery.png","signals-icon-size-1":0,"signals-blink-1":false,"signals-horz-1":0,"signals-vert-1":0,"signals-hide-edit-1":false,"signals-cond-2":"==","signals-val-2":true,"signals-icon-2":"/vis/signals/lowbattery.png","signals-icon-size-2":0,"signals-blink-2":false,"signals-horz-2":0,"signals-vert-2":0,"signals-hide-edit-2":false,"lc-type":"last-change","lc-is-interval":true,"lc-is-moment":false,"lc-format":"","lc-position-vert":"top","lc-position-horz":"right","lc-offset-vert":0,"lc-offset-horz":0,"lc-font-size":"12px","lc-font-family":"","lc-font-style":"","lc-bkg-color":"","lc-color":"","lc-border-width":"0","lc-border-style":"","lc-border-color":"","lc-border-radius":10,"lc-zindex":0,"oid":"hue.0.Philips_hue.Büro.on","iValueFalse":"","iValueTrue":"","iTextFalse":"Büro Off","iTextTrue":"Büro On","iImageFalse":"/vis-icontwo/Lights/light_off.png","iImageTrue":"/vis-icontwo/Lights/light_on.png","iInvertImageCol":true,"iFlipImage":false,"iStateResetValueTime":"0","iImgColorFalse":"#c70000","iImgColorTrue":"#00cc1a","iImgColorFalseFilter":"filter: invert(9%) sepia(86%) saturate(7489%) hue-rotate(11deg) brightness(89%) contrast(115%);","iImgColorTrueFilter":"filter: invert(54%) sepia(36%) saturate(3531%) hue-rotate(89deg) brightness(100%) contrast(108%);","views":["Alarm","Yamaha_Status_Netradio"],"name":"Spot Büro","filterkey":"Button","iValueComparison":"equal","iPopUpBackground":"#666666","iPopUpPreventClickOutside":"","iPopUpShowTitle":"true","iPopUpTitle":"","iPopUpTitleColor":"#ffffff","iPopUpCloseBtnColor":"#dc2e2e","iPopUpWidth":"800px","iPopUpHeight":"500px","iPopUpHeightTitle":"50","iPopUpTitleSize":"28","iPopUpPosition":"center","iPopUpPositionX":"0","iPopUpPositionY":"0","iPopUpCloseAfterSeconds":"0","iPopUpCornerRadiusUL":"12","iPopUpCornerRadiusUR":"0","iPopUpCornerRadiusLR":"12","iPopUpCornerRadiusLL":"0","iPopUpShadowXOffset":"2","iPopUpShadowYOffset":"2","iPopUpShadowBlur":"2","iPopUpShadowSpread":"1","iPopUpShadowColor":"#111111","iButtonColHover":"","iContentType":"image","iImgClockFace":"001","iImgClockHands":"001","iImgClockShowBorder":"1","iImgColorClockFace":"#ffffff","iImgColorHands":"#ffffff","iImgColorHandSecond":"#ff0000","iClockShowSeconds":"","iClockTimezone":"Europe/Berlin","iHtmlTextFieldFalse":"","iHtmlTextFieldTrue":"","iShadowColorHover":"","iShadowInnerColorHover":"","iShadowTextXOffset":"0","iShadowTextYOffset":"0","iShadowTextBlur":"0","iShadowTextColor":"#111111","iShadowTextColorActive":"#111111","iBorderColorHover":""},"style":{"left":"425px","top":"93px","z-index":"4","width":"110px","height":"110px"},"widgetSet":"vis-inventwo"}]`


![Screenshot (4158)](https://user-images.githubusercontent.com/41079106/129209208-4bb52bdb-25d6-4f00-9ce3-1800aa5a4b64.png)

**Comment by foxriver76** [comment]
> Hue: 3.5.22, kommt immer.

Also immer wenn du den State änderst. Kann es bei mir leider nicht nachstellen.

Hast du den Adapter mal neugestartet?

**Comment by sigi2345** [comment]
> > Hue: 3.5.22, kommt immer.
> 
> Also immer wenn du den State änderst. Kann es bei mir leider nicht nachstellen.
> 
> Hast du den Adapter mal neugestartet?

Jetzt geht es wieder.
Habe in den Einstellungen auf poolig 10 sec gestellt und den Haken bei Gruppen ignorieren raus gemacht.

**Comment by foxriver76** [comment]
Ja.. wenn du Gruppen ignorieren drin hast und Büro eine Gruppe ist.. aber sollte sich jetzt mit der neusten Version nix am Verhalten geändert haben.

Wenn ich den Adapter erst laufen lassen habe mit Gruppen und er dann die Gruppe angelegt hat bleibt diese auch bei einem Gruppe ignorieren run bestehen, beim steuern passiert allerdings dann das gezeigte Verhalten ja.. sehe ich jetzt nicht als Fehler an.

**Comment by sigi2345** [comment]
> Ja.. wenn du Gruppen ignorieren drin hast und Büro eine Gruppe ist.. aber sollte sich jetzt mit der neusten Version nix am Verhalten geändert haben.

Verhalten? Ich habe den Haken vor kurzen mal gesetzt, warum auch immer.
Kann geschlossen werden. Danke.
