### ISSUE TITLE
Verify lamp ct values

### ISSUE THREAD

**Issue by Pmant** [iobroker-community-adapters/ioBroker.hue#224]
https://github.com/iobroker-community-adapters/ioBroker.hue/blob/0a1bac04d0e61e2a461b825f6514cfd5b62e3ced/main.js#L1166
Non Philips lights may not report ct range which results in bridge reporting a range of **0-65535**. Eventually this leads to the ct state having a ct range of **15** to **null** which causes adapter warnings when changing the value.

Lamp on Bridge:
```	
"50": {
		"state": {
			"on": false,
			"bri": 62,
			"ct": 367,
			"alert": "select",
			"colormode": "ct",
			"mode": "homeautomation",
			"reachable": false
		},
		"swupdate": {
			"state": "notupdatable",
			"lastinstall": null
		},
		"type": "Color temperature light",
		"name": "Arbeitszimmer_Decke",
		"modelid": "TS0502A",
		"manufacturername": "_TZ3000_rylaozuc",
		"productname": "Color temperature light",
		"capabilities": {
			"certified": false,
			"control": {
				"ct": {
					"min": 0,
					"max": 65535
				}
			},
			"streaming": {
				"renderer": false,
				"proxy": false
			}
		},
		"config": {
			"archetype": "classicbulb",
			"function": "functional",
			"direction": "omnidirectional"
		},
		"uniqueid": "58:8e:81:ff:fe:ed:d0:a7-01",
		"swversion": ""
	}
```

ct state in ioBroker:
```
{
  "_id": "hue.0.Arbeitszimmer_Decke.ct",
  "type": "state",
  "common": {
    "name": "Arbeitszimmer_Decke.ct",
    "read": true,
    "write": true,
    "type": "number",
    "role": "level.color.temperature",
    "unit": "°K",
    "min": 15,
    "max": null,
    "def": 2725
  },
  "native": {
    "id": "50"
  },
  "from": "system.adapter.hue.0",
  "user": "system.user.admin",
  "ts": 1629898947658,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
```

**Comment by foxriver76** [comment]
Don't really get it right now, but I will look into it. Probably due to the conversion the numbers get messed up

**Comment by Pmant** [comment]
The Bridge returns an invalid ct range (0-65535) for some non Philips lights. This code line will not use the default _ctObj_ but the invalid values reported by the hue bridge. 
https://github.com/iobroker-community-adapters/ioBroker.hue/blob/0a1bac04d0e61e2a461b825f6514cfd5b62e3ced/main.js#L1166

This causes a division by zero here
https://github.com/iobroker-community-adapters/ioBroker.hue/blob/0a1bac04d0e61e2a461b825f6514cfd5b62e3ced/main.js#L1173-L1174

And this results in a ct state object with **max: null**

**Comment by foxriver76** [comment]
Thanks, will catch this and fallback to default in this case. If you like you can also create a PR, will not come back to this until tomorrow.
