### ISSUE TITLE
New Hue API with push

### ISSUE THREAD

**Issue by Flothoger** [iobroker-community-adapters/ioBroker.hue#227]
The time delay with polling is pretty frustrating when dealing with motion sensors. I recently read that the bridge got a new api with push. This should mitigate the problems of polling, because the bridge is sending changes directly to the application.

So far, however, the new API does not seem to be documented by signify.

If it is possible to implement will this be planned for a future version of the adapter?

The article I have read: https://www.smarthomeassistent.de/neue-philips-hue-api-arbeitet-per-push-schnellere-kommunikation/

**Comment by foxriver76** [comment]
We would like to continue to use the node-hue-api, thus we will wait until https://github.com/peter-murray/node-hue-api/issues/202 is implemented. We could also rely on https://github.com/homegraph/philips-hue-push-client, but that doesn't fit that well in our infrastructure and is likely to be not as well maintained as node-hue-api

**Comment by Pmant** [comment]
You can try [this](https://forum.iobroker.net/post/670867) script until the push API is officially supported.

**Comment by Flothoger** [comment]
> You can try [this](https://forum.iobroker.net/post/670867) script until the push API is officially supported.

That works realy well, at least for now. Thank you for the suggestion.

**Comment by klein0r** [comment]
Some official information:

> ## Hue API V2
> The Hue API - referred to as CLIP API ('Connected Lighting Interface Protocol') - will move to version 2, which is a breaking change over version 1. Version 2 is still a RESTful JSON HTTP API, but the structure has been redefined to make some improvements and allow for new use-cases. Both APIs will exist in parallel to give developers time to upgrade, however any new features (such as dynamic scenes) will only be available on V2, and in the long term the V1 API will eventually be removed. The V2 API is currently in early access and not yet feature complete, but it is already available on production bridges and in use by Signify developed applications. For features that are available on both versions, we recommend to start using V2. Just make sure to check that the bridge version is at least 1948086000.

https://developers.meethue.com/develop/hue-api-v2/

> As per today, we deprecate UPnP as a local bridge discovery method, scheduled to be disabled in Q2 2022. Please use the recommended discovery methods mDNS and discovery.meethue.com which are supported since January 2018.

https://developers.meethue.com/new-hue-api/

**Comment by BigMike71** [comment]
any news about updating the adapter to the new Push Api?

**Comment by foxriver76** [comment]
Still https://github.com/peter-murray/node-hue-api/issues/202

**Comment by BigMike71** [comment]
how can i use it with iobroker? its a plugin?

**Comment by klein0r** [comment]
@BigMike71 It is not a plugin, it's a library (which is used by the ioBroker hue adapter). This library has to be updated (see linked issue). After that, this adapter can be updated to use the latest version of that library.

**Comment by rug1024** [comment]
Please make this happen, the workaround script by Pmant worked out of the box but not for long, after some time states just were not updated anymore. IKEA Tradfri does 'push' since always, did'nt even know that this issue exists when changing my whole home to Philips Hue.
