### ISSUE TITLE
New users are created with "null"

### ISSUE THREAD

**Issue by klein0r** [iobroker-community-adapters/ioBroker.hue#249]
**Describe the bug**

- New users are created with "null" value

https://github.com/iobroker-community-adapters/ioBroker.hue/blob/aef65e45d7d370ad3170249a506ac539357c3495/main.js#L687

**To Reproduce**

1. Go to instance configuration
2. Click on 'create user'
3. Push the button on the hue bridge

**Expected behavior**

- A new user will be created with additional info

**Screenshots & Logfiles**

<img width="565" alt="Screenshot 2021-10-20 at 15 57 28" src="https://user-images.githubusercontent.com/1959049/138107456-bd614ef8-bc2b-4dd2-a0a9-accb618f0f22.png">

**Versions:**
 - Adapter version: 3.5.25
 - JS-Controller version: 3.3.18
 - Node version: v12.22.6
 - Operating system: Debian Bullseye
 - Bridge model: Gen 2

**Additional context**

- [See API documentation](https://developers.meethue.com/develop/hue-api/7-configuration-api/)
- [node-hue-api Reference](https://github.com/peter-murray/node-hue-api/blob/HEAD/docs/users.md#createuser)

**Comment by klein0r** [comment]
What is the intended result?

Maybe `ioBroker.hue#<ioBrokerIpAdress>` ?

`ip` is the address of the hue bridge in this case (which makes no sense as the user description):

https://github.com/iobroker-community-adapters/ioBroker.hue/blob/aef65e45d7d370ad3170249a506ac539357c3495/main.js#L691

**Comment by foxriver76** [comment]
> Maybe `ioBroker.hue#<ioBrokerIpAdress>` ?

Seems like the code has been like this since forever https://github.com/iobroker-community-adapters/ioBroker.hue/blob/293bfd3021dc72533416e55b4c4fc8f3c67b1318/hue.js#L387-L392

It seems like the used hue lib has changed its behavior by only requiring two attributes now. First parameter is is `appName` second `deviceName`, so would move third param at second param.
