### ISSUE TITLE
Changing CT switches lights on that have been off

### ISSUE THREAD

**Issue by EagleeyeKai** [iobroker-community-adapters/ioBroker.hue#259]
**Describe the bug**
Changing the colortemperature of a room or lamp itself will switch it on even if all lamps in a room or the single one is switched off prior to changing the ct value.

**Expected behavior**
I would expect that the lamp will not change its state/level, but only change the color temperature. My intended behaviour is to change the ct of all lights im my house depending on the day time using i simple javascript. If a light is switched on at any time of the day, it should light up in the prior defined ct. However, if I change the predefined ct of all lights, I do not want to change their status / switch them on.

**Screenshots & Logfiles**
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**
 - Adapter version: 3.5.25
 - JS-Controller version: 5.2.13
 - Node version: v12.22.7
 - Operating system: Raspbian
 - Bridge model: 2nd generation

**Additional context**

**Comment by foxriver76** [comment]
It’s the same for level etc, would be a breaking change and thus will pretty much not be implemented. So better use a script which just changes these values for all turned on values. 

We can maybe change this with other breaking changes but only for this change it is not worth changing the behavior. Or with new api it may be possible to know the real status of lamps at all time and we can make a custom state for with turn kn and without. But I am currently not aware how many users this change will break.
