### ISSUE TITLE
Log Warning "has no existing object" with certain Dimmer Switch

### ISSUE THREAD

**Issue by TimoGoerlich** [iobroker-community-adapters/ioBroker.hue#273]
**Describe the bug**
Repetitive warning "State "hue.0.Garage_LEDs.bri" has no existing object, this might lead to an error in future versions" for follwing paired HW device: https://www.amazon.de/gp/product/B07PCRJ66Y

**Versions:**
 - Adapter version: 3.5.31
Plattform: linux
Betriebssystem: linux
Architektur: arm
CPUs: 4
Geschwindigkeit: 1000 MHz
Modell: ARMv7 Processor rev 3 (v7l)
Node.js: v12.22.8
NPM: v6.14.15

**Comment by foxriver76** [comment]
Maybe it helps when you show me a screenshot of the object tree, especially role of this dimmer object

**Comment by TimoGoerlich** [comment]
Thanks for the feedback, attached a respective screenshot

As you are hinting towards the role: Should I change it? right now it has light.color. But this is just a simple on/off actor, no dimming or color setting possible

![image](https://user-images.githubusercontent.com/97469924/149011154-519f3aac-660a-41df-bae1-f5342ec7151a.png)

**Comment by foxriver76** [comment]
Yes, the adapter needs to detect, that it is not a color light of course, can click on the pencil behind the Garage_LEDs channel and show the raw object?

Actually you could try to change the role to switch, but I am not sure if the adapter will respect it if it's set from outside

**Comment by TimoGoerlich** [comment]
{
  "_id": "hue.0.Garage_LEDs",
  "type": "channel",
  "common": {
    "name": "Garage LEDs",
    "role": "light.color"
  },
  "native": {
    "id": "14",
    "type": "On/Off light",
    "name": "Garage LEDs",
    "modelid": "ON/OFF",
    "swversion": "2.5.3_r47"
  },
  "from": "system.adapter.hue.0",
  "user": "system.user.admin",
  "ts": 1641827920951
}

**Comment by foxriver76** [comment]
okay have to look into the adapter, on/off light should be fine to detect it as a switch, I will look into it tommorow

**Comment by TimoGoerlich** [comment]
Thank you, have a good night

**Comment by foxriver76** [comment]
okay is already fixed was just a nit, 3.6.4 on the way, please give feedback if you find some time to test

and you probably need to delete the object then restart with the new version, so the object will be created anew
