### ISSUE TITLE
Entertainment start/stop Spotify sync

### ISSUE THREAD

**Issue by tuvya** [iobroker-community-adapters/ioBroker.hue#281]
hi everyone,

i have an entertainment area in hue that synchronises with my spotify account. My goal is to start and stop the synchronisation with the adapter.

I have seen there have been some efforts to get this working with the sync box. But is there a way just to start/stop the sync when spotify is already running? No sync box involved.

active stream just shows the state but does nothing to start the sync.

Kind regards,
Tobias

**Comment by foxriver76** [comment]
Only possible to disable an ongoing stream over hue api https://github.com/peter-murray/node-hue-api/issues/163
