### ISSUE TITLE
Gruppen und Räume optional synchronisieren

### ISSUE THREAD

**Issue by janhuddel** [iobroker-community-adapters/ioBroker.hue#29]
Hallo,

ich bin noch recht neu im ioBroker-Umfeld. Ich habe meine Hue-Bridge erfolgreich angebunden. Bei der Synchronisation werden in ioBroker sowohl Objekte für die einzelnen Lampen angelegt als auch für Räume (Rolle "Room") bzw. für Gruppen (Rolle "LightGroup"). Wieso hier die Hue-API noch zwischen Room und LightGroup unterscheidet, erschließt sich mir nicht wirklich.

Wenn nun der Hue-Adapter für einen Raum ein "virtuelles" Objekt anlegt, dann habe ich ein Problem bei der Reaktion auf Events. Wenn ich zum Beispiel per Scipt immer etwas tun möchte, wenn eine Hue-Lampe geschaltet wird, dann würde ich das ja so formulieren:
```javascript
on({id: /^hue.*\.on$/,
    change: 'ne' // nur bei Änderung triggern
}, function (obj) {
    log('new state "' + obj.id + '": ' + obj.state.val);
});
```

Schalte ich jetzt eine Lampe (die einzige in einem Raum) an, dann wird das Event 2 mal gefeuert: Einmal für die Gruppe/ den Raum und einmal für die Lampe selbst. Ich habe keine Möglichkeit gefunden, zu erkennen, ob es sich bei `obj` um die Lampe handelt oder die Gruppe/der Raum.

Sind einer Gruppe/ einem Raum mehrere Lampen zugeordnet, dann wird das Event zunächst nur einmal gefeuert. Erst wenn die letzte Lampe angeschaltet wird, wird das Event wieder 2 mal gefeuert (einmal für die Lampe und einmal für die Gruppe/ den Raum).

Ich würde es befürworten, wenn die Anlage von Gruppen/ Räumen optional wäre (über eine Checkbox im Config-Dialog).

Was haltet ihr davon?

Viele Grüße
Jan

**Comment by Pmant** [comment]
> Bei der Synchronisation werden in ioBroker sowohl Objekte für die einzelnen Lampen angelegt als auch für Räume (Rolle "Room") bzw. für Gruppen (Rolle "LightGroup"). Wieso hier die Hue-API noch zwischen Room und LightGroup unterscheidet, erschließt sich mir nicht wirklich.

Die LightGroups gab es schon, bevor es Rooms in HUE gab. Rooms werden vor allem in der HUE App genutzt.

> Ich habe keine Möglichkeit gefunden, zu erkennen, ob es sich bei obj um die Lampe handelt oder die Gruppe/der Raum.

obj.common.role?
https://github.com/ioBroker/ioBroker.javascript#user-content-on---subscribe-on-changes-or-updates-of-some-state

**Comment by janhuddel** [comment]
> Die LightGroups gab es schon, bevor es Rooms in HUE gab. Rooms werden vor allem in der HUE App genutzt.

Ok, das klingt plausibel. Dann muss ich vielleicht mal die Raum- bzw Gruppenzuordnungen in der App mal komplett löschen und neu einrichten. Danach dürfte es dann ja keine Gruppen mehr geben.

> obj.common.role?

Funktioniert leider nicht, denn sowohl beim Raum als auch bei der Lampe selbst handelt es sich um die Rolle "switch".

Nochmal zurück zum "Feature-Request": 
Bei den Homematic-Adaptern wird ja auch zwischen der RPC- (`hm-rpc`) und der Logikschicht (`hm-rega`) unterschieden. M.E gehört die Zuordnung von Lampen zu Räumen in die Logikschicht und sollte optional sein. Zumal nach meinem Verständnis Räume bzw. Gruppen in ioBroker eher zu den Aufzählungen gehören und nicht zu den Objekten.

**Comment by GermanBluefox** [comment]
Please test 1.1.1 from git
