### ISSUE TITLE
zwei IDs werden nicht/falsch erkannt

### ISSUE THREAD

**Issue by schneidy76** [iobroker-community-adapters/ioBroker.hue#30]
![huelog](https://user-images.githubusercontent.com/26479254/30785318-87c69658-a165-11e7-9fde-cf5edb2ab52f.png)
IDs werden nicht korrekt eingelesen

**Comment by GermanBluefox** [comment]
Leider verstehe ich überhaupt nicht, was das ist. Kannst du mehr info geben?
Welche Gruppen existieren bei dir?

**Comment by schneidy76** [comment]
Hi,

ich weiß ja auch nicht viel mehr. Steuern kann ich zum Beispiel die Gruppe 22 auch nicht…

Habe schon die ID geändert, aber alles umsonst

 

VG Torsten

 

Von: Bluefox [mailto:notifications@github.com] 
Gesendet: Sonntag, 24. September 2017 21:02
An: ioBroker/ioBroker.hue <ioBroker.hue@noreply.github.com>
Cc: Torsten Schneider <schneidy76@web.de>; Author <author@noreply.github.com>
Betreff: Re: [ioBroker/ioBroker.hue] zwei IDs werden nicht/falsch erkannt (#30)

 

Leider verstehe ich überhaupt nicht, was das ist. Kannst du mehr info geben?
Welche Gruppen existieren bei dir?

**Comment by Pmant** [comment]
Also die Gruppe existiert auf deiner Bridge? Kannst du vielleicht sagen, um was für eine Gruppe es sich handelt, welche Lampen sind daran beteiligt? Ist es ein Raum?

**Comment by schneidy76** [comment]
Ja, die Gruppe existiert. Der Name ist „Terrasse“ . In der App Huetro ist befindet sie sich bei den Räumen, in HVL (Homematic) heißt sie HueGroup 04.
Die andere ID Lampe 5, ist „Stehlampe Schlafzimmer“.
Vg Torsten 

Gesendet von meinem Windows 10 Phone

Von: Pmant
Gesendet: Montag, 25. September 2017 00:47
An: ioBroker/ioBroker.hue
Cc: Torsten Schneider; Author
Betreff: Re: [ioBroker/ioBroker.hue] zwei IDs werden nicht/falsch erkannt(#30)

Also du Gruppe existiert auf deiner Bridge? Kannst du vielleicht sagen um was für eine Gruppe es sich handelt, welche Lampen sind daran beteiligt? Ist es ein Raum?

**Comment by GermanBluefox** [comment]
Is the Problem still exists?

**Comment by jens-maus** [comment]
Since I had this issue myself for a while. I investigated it and found that the error actually originates from the `node-hue-api` NodeJS package ioBroker.hue is using. After more investigation I reported that as an actual bug in this package and it was just fixed today with version 2.4.4 of node-hue-api. See here for more information: https://github.com/peter-murray/node-hue-api/issues/123
