### ISSUE TITLE
Nach Update auf 0.6.9 erscheinen Fehler im LogFile

### ISSUE THREAD

**Issue by modmax** [iobroker-community-adapters/ioBroker.hue#31]
Hi,
nach dem Update auf 0.6.9 erscheint alle 30 Sekunden beim Pollen folgender Fehler:

hue.0 | 2017-10-28 00:54:29.437 | debug | polling light Philips_hue.Stehlampe
hue.0 | 2017-10-28 00:54:29.447 | error | TypeError: adapter.setForeignStateChanged is not a function
hue.0 | 2017-10-28 00:54:29.447 | error | Cannot get result for lightStatus4

Scheint so, als wenn im Adapter etwas nicht funktioniert.
Schalten der Lampen geht noch, aber beim Pollen des aktuellen Status von der Bridge hapert es nun.

**Comment by Pmant** [comment]
welche Version von js-controller nutzt du?

**Comment by modmax** [comment]
Guter Tipp!
Meiner war veraltet ... hab den wohl etwas länger nicht mehr aktualisiert.
Mein Fehler .. nun geht alles wieder!

Danke für den Hinweis ... :-)
