### ISSUE TITLE
Falscher Link zur ioBroker.hue-Seite

### ISSUE THREAD

**Issue by modmax** [iobroker-community-adapters/ioBroker.hue#32]
Der Link bei der Instanz (?) verweist nun auf:
https://raw.githubusercontent.com/ioBroker/ioBroker.hue/master/README.md
statt auf 
https://github.com/ioBroker/ioBroker.hue/blob/master/README.md

**Comment by Pmant** [comment]
Stimmt, das müsste hier ausgetauscht werden https://github.com/ioBroker/ioBroker.hue/blob/e4acb9e0a88cb060214209be88a75d78214e0311/io-package.json#L68

**Comment by GermanBluefox** [comment]
Done. Thanks.
https://github.com/ioBroker/ioBroker.hue/commit/4704f603cd1ec6ec3bb58a976b9cbcc415df47e5
