### ISSUE TITLE
CLIPGenericFlag not syncing

### ISSUE THREAD

**Issue by Eistee82** [iobroker-community-adapters/ioBroker.hue#328]
**Describe the bug**
CLIPGenericFlag Sensors are not working. CLIPGenericStatus workes fine.

**To Reproduce**
Define a CLIPGenericFlag sensor with an app like all4HUE.

**Expected behavior**
CLIPGenericFlag workes like CLIPGenericStatus sensors.

**Screenshots & Logfiles**
No Errors in log.

**Versions:**
 - Adapter version: v3.6.5
 - JS-Controller version: 4.0.23
 - Node version: v16.15.0
 - Operating system: debian
 - Bridge model: V2

**Comment by foxriver76** [comment]
I will try to unlock them, should only be a „feature flag“

**Comment by Eistee82** [comment]
I get a warning with the updated adapter version when I set the Value in iobroker: Changed flag of sensor 12 to false - currently not supported
