### ISSUE TITLE
hue motion sensor

### ISSUE THREAD

**Issue by mikiline** [iobroker-community-adapters/ioBroker.hue#33]
@GermanBluefox 
hello, maybe is it possible to integrate the hue motion sensor into the adapter?
thank you very much

**Comment by maikbooehme** [comment]
I'm also interested on it

**Comment by GermanBluefox** [comment]
I dont have motion sensor. May be you can do that?

**Comment by maikbooehme** [comment]
I can help with the testing, but I do not have any experience with coding .
If you need anything, any data which I could capture for you, then please let me know.
I only need to know, who to capture .

**Comment by Miggi1986** [comment]
Gibt es hierzu schon etwas neues? Ich würde wirklich gerne den Bewegungssensor inkl. der Temperaturdaten im IoBroker nutzen. Ich wäre auch breit dir einen motion Sensor zur Verfügung zu stellen.

**Comment by COMHOME** [comment]
+1

**Comment by eXTreMe-1337** [comment]
http://forum.iobroker.net/viewtopic.php?f=20&t=8730

**Comment by mikiline** [comment]
könnte das jemand in den [Adapter](http://forum.iobroker.net/viewtopic.php?f=20&t=8730) integrieren bitte?

**Comment by mikiline** [comment]
push ! Thanks und Danke

**Comment by COMHOME** [comment]
Wem muss ich einen Motion Sensor schenken, damit er es implementiert? 😂

**Comment by eXTreMe-1337** [comment]
hier eine lösung von mir wie es mit einem javascript geht
https://forum.iobroker.net/viewtopic.php?f=24&t=11751#p124271
bekomm ich auch einen motion sensor dafür? :)

**Comment by arteck** [comment]
ich habe den ZLLSwitch und ZGPSwitch implementiert.. reaktion auf dessen wie im polling angegeben.. 
nen motion sensor habe ich leider nicht im hause..  

Bluefox muss den merge durchführen

**Comment by eXTreMe-1337** [comment]
> ich habe den ZLLSwitch und ZGPSwitch implementiert.. reaktion auf dessen wie im polling angegeben..
> nen motion sensor habe ich leider nicht im hause..

Danke dafür!
Kann man dir die Daten für den Motion Sensor irgendwie zur Verfügung stellen? Was brauchst du?

**Comment by arteck** [comment]
dir ist klar dass die Reaktion erst nach dem polling statfindet.. und nicht SOFORT..da die api das nicht hergibt

**Comment by eXTreMe-1337** [comment]
ja das ist mir bewusst, aber man könnte den bewegungsmelder doch trotzdem integrieren?
es gibt zwar den workaround dass man einfach den on state einer mit dem melder gekoppelten lampe als trigger für weitere aktionen nehmen kann aber wenn die lampe abhängig von uhrzeit oder helligkeit nicht angeschaltet wird dann funktioniert der workaround nicht, da wäre es dann super einen direkten motion-detected datenpunkt vom melder zu haben den man auslesen kann. mit den x sekunden verzögerung muss man halt leben.
in erster linie geht es mir darum, dass adapter möglichst viele funktionen besitzen und man nicht immer zusätzlich javascripte braucht wenn die funktion sich in den adapter integrieren lässt. das macht iobroker auch viel interessanter für user ohne javascriptkenntnisse. außerdem werden adapter im github hinterlegt ubd änderungen können direkt für alle zur verfügung gestellt werden und man muss nicht zig forenposts mit scripten in seinen lesezeichen abspeichern um zu schauen ob der jemand ein script update zur verfügung gestellt hat.
da es sowas wie die adapterliste nicht für javascripts gibt, sollte der trend meiner meinung nach dahin gehen möglichst viele „allgemeine“ scripte in einen adapter umzuwandeln.

**Comment by Apollon77** [comment]
Genau muss man sinnvolle Grenzen setzen!
Der Hue Adapter in dem Fall realisiert die Anbindung an die Gerätewelt und kann im ersten Schritt das was dort möglich ist.
Jegliche Zusatzlogik die am Ende "unerwartet" funktioniert ist oder sehr Userspezifisch ist hat ggf nichts in einem Adapter verloren.

Auch die Idee "Möglichst viele JavaScripts in Adapter zu verwandeln" ist ggf problematisch. Man muss da sehr genau schauen was Sinn macht.
ioBroker ist mit JavaScript sehr mächtig und das ist auch gut so - wir brauchen eher noch einfachere wege für User Logiken zu entwicklen ausser JavaScript :-)

Hat alles seine Vor- und Nachteile ...

**Comment by Pmant** [comment]
Ich sehe schon hunderte Foren Threads vorraus, weil der Sensor nicht schnell genug auslöst. Als Lösung wird die Polling-Frequenz erhöht und ioBroker überlastet.
Spaß beiseite: Ich glaube im Moment findet sich einfach niemand, der etwas großes am Adapter machen möchte ohne dass es wirklich neue Funktionen bringt. Zumindest trifft dies auf mich zu. Sollte es eine neue HUE-API mit PUSH per Websocket oder ähnliches geben, werde ich den Adapter gerne komplett überarbeiten.

**Comment by arteck** [comment]
theoretisch könnte man alle Hue Produkte in den Adapter intergrieren.. nur .. ich sehe hier ein zeitliches Problem in der Abfrage ... und das gemecker .. warum den iobroker so langsam reagiert auf den "Bewegungsmelder".. wir tun uns damit kein gefallen

**Comment by COMHOME** [comment]
Unter node-red läuft der Motion Sensor schon eine Weile bei einem Bekannten. Wo ist hier das Problem?

**Comment by Apollon77** [comment]
Und wie genau? Welche polling Geschwindigkeit?

**Comment by COMHOME** [comment]
https://flows.nodered.org/node/node-red-contrib-huemagic#hue-motion-sensor

**Comment by COMHOME** [comment]
Für mich sieht das bei node-red gar nicht nach polling aus...

**Comment by Pmant** [comment]
> Für mich sieht das bei node-red gar nicht nach polling aus...

Ist es aber, es sind dort 3 Sekunden voreingestellt. Es gibt auch keine magischen Funktionen in der HUE-API um das Polling zu umgehen. Wir müssen da abwarten, ob Philips irgendwann einsieht, dass Polling bei Automatisierung nicht sinnvoll ist. Bisher sieht es da eher schlecht aus, wenn man ins HUE dev-Forum guckt.

**Comment by arteck** [comment]
man könnte ewtl von dem Sensor die Temperatur und was weiss ich was der noch mist .. übernehmen..

**Comment by mikiline** [comment]
Hmmmm, mir sind 3 sekunden verzögerung egal.....hauptsache man weiss das der Melder angesprochen hat und kann ihm auch einen Status geben. Ob mit oder ohne den 3 Sekunden wäre es auf jeden Fall sinnvoll das zu integrieren.
Ändern muss man es später sowieso

Wäre jemand bereit es zu integrieren? Auch mit den 3 Sekunden?

**Comment by cernst1980** [comment]
Gibt es schon länger.
https://github.com/robbsta/ioBroker.hue

Man braucht aber auch nen Fork von node-hue-api.
https://github.com/abwaters/node-hue-api

Aktuell habe ich dies aber über node-red (node-red-contrib-huemagic) mit 1s Polling gelöst.

Wenn ich mal Zeit habe, wollte ich mich mal mit ein paar Themen auseinandersetzen.
Z.B. wird jeder Sensor einzeln gepollt (macht dann mehrere Requests pro Sekunde und man kommt irgendwann ans Limit), obwohl man mit dem Endpoint "/sensors" auch alle Sensoren in einem Call abfragen kann und trotzdem alle Informationen enthält. Dadurch ließe sich das Polling Intervall auch weiter reduzieren, auch wenn Push natürlich die bessere Option wäre.
Bei den anderen Endpoints würde das auch gehen.
Lediglich die group 0 muss man dediziert abfragen, soweit ich aktuell weiß.
Am Ende kann man vielleicht alle Informationen die man braucht über den root Endpoint abfragen.
"lights": {},
"groups": {},
"config": {},
"schedules": {},
"scenes": {},
"rules": {},
"sensors": {},
"resourcelinks": {}

**Comment by GermanBluefox** [comment]
We must wait, till this PR merged https://github.com/peter-murray/node-hue-api/pull/121

**Comment by robbsta** [comment]
Habe den aktuellen Master in meinen Fork gezogen und die Bewegungsmelder eingebaut.
Wenn oben genannter PR durch ist, kann ich gerne einen neuen PR machen.

**Comment by GermanBluefox** [comment]
: [peter-murray/node-hue-api] added sensor status and set sensor name (#121)
Merged

**Comment by robbsta** [comment]
PR für Temperatur- Helligkeit-, Tageslicht- und und Bewegungssensor erstellt. #43 

Hoffe, das ist ok so.
Sonst hatte ich überlegt ob man eine eigene Funktion nur für diese vier macht, damit Lichter, Schalter und Sensoren jeweils getrennt betrachten werden können.

**Comment by haselchen** [comment]
Ich habe die Version 1.1.1. des Adapters bei IOBroker. Ich habe leider nicht soviel Plan von der Materie. Was muss ich nun tun, damit der Sensor in meinen Objekten erscheint?

**Comment by dnnrwttr** [comment]
so wie ich sehe kann man den Dämmerrungssensor des Motionsensors noch nicht nutzen oder?
