### ISSUE TITLE
State value to set for "hue.0.example.ct" has value "2000" less than min "2203"

### ISSUE THREAD

**Issue by bobbiest** [iobroker-community-adapters/ioBroker.hue#336]
The (nightlight / nightscene) from hue android app causes the aforementioned error for a Hue Ambiamce Candle (model: LTW012, hw:100b-10c, sw:1.88.1)

![hue error](https://user-images.githubusercontent.com/108470829/176687833-d6e8ccd2-09b1-4474-a842-50247cc1449a.jpg)

For testing I manually set the minimum value to 2000, that solved the problem

 - Adapter version: 3.7.0
 - JS-Controller version: 4.0.23
 - Node version: 14.19.3
 - Bridge model: 2.1
 - Hue android app: 4.21.999 (10508) (beta) but also testet with an alpha version

**Comment by MiniAdnim** [comment]
State value to set for "hue.0.Hue_ambiance_spot_1_Garderobe_.ct" has value "2000" less than min "2203"

Hi, habe die gleiche Fehlermeldung, kann es zwar manuell ändern aber nach neu Erstellung der Objekte wird es immer wieder falsch angelegt. Kannst du dir das nochmal anschauen @Apollon77 . Wenn ich noch etwas Unterstützen kann , gib mir gerne bescheid!

VG
