### ISSUE TITLE
Letztes Level speichern

### ISSUE THREAD

**Issue by modmax** [iobroker-community-adapters/ioBroker.hue#34]
Wenn der Level > 0 ist den letzten Stand speichern.
So könnte man bei Aktionen auf die Hue-Lampe auf den letzten Stand setzen,
ohne dafür eigene Datenüunkte anzulegen.

Praktisches Beispiel: Die HUE-Lampem schalten ich über ein HM-Fernbedienung an und aus.
Da wäre es schön den letzten Stand zu habe. Momentan passiert das über on-Trigger auf "level"
und Speichern in einem angelegten Zustand.

**Comment by travelbugde** [comment]
In der Hue App funktioniert das auf diese Weise. Das letzte Level wird bei OFF/ON wieder angesteuert (auch ganze Räume). Die Hue Lampen (IKEA Tradfri in meinem Fall) behalten ihren Level auch bei Stromverlust (Lichtschalter). Das würde es ermöglichen ein eingestelltes Lichtszenario nur mit OFF/ON (Property on=false/true) wieder abzurufen, ohne die einzelnen Level programmieren zu müssen. Im Moment ist der Level beim Einschalten über das Property on immer auf 100%.

**Comment by thommbauer** [comment]
Wenn man bei bestehender Beläuchtung z.B. duch eine andere Farbe einen Anruf signalisieren möchte, wäre es toll dannach wieder zu einem letzten Stand zurückkehren zu können.

Alternativ:
Wie kann ich in JS (iobroker) mit wenig Aufwand alle Variablen einer Lampe speichern ?

**Comment by BuZZy1337** [comment]
Ich habe selber keine Hue Komponenten.
Mache es bei Tradfri z.B. aber so, dass ich EINEN Datenpunkt habe und in diesem Datenpunkt speichere ich die Werte ALLER Lampen als Objekt.

So kann ich dann mit dem einen Datenpunkt alle Werte abrufen wie sie vorher waren. Den Datenpunkt habe ich "javascript.0.tradfri.settingsbefore" genannt.

Wenn ich z.B. meine "Netflix Stimmung" aktiviere werden die Werte aller Glühbirnen (color und brightness) in diesem Datenpunkt abgespeichert und dann wird das licht gedimmt und auf warmweiß gestellt.
Wenn ich die Netflix Stimmung wieder deaktiviere werden die Werte wieder aus dem Datenpunkt gelesen und auf allen Glühbirnen wiederhergestellt.

**Comment by gehrausundspiel** [comment]
Buzzy wie geht dies? Alles in einen Datenpunkt schreiben und wieder auslesen?

**Comment by Mihaeru2110** [comment]
Ich habe das Problem, dass die Brightness verzögert auch dann auf 100% gesetzt wird, wenn ich die Lampen per Hue App oder per Fernbedienung einschalte. Beim Einschalten durch App/FB ist erst mal der alte Zustand aktiv aber sobald der Adapters die neuen Werte bekommt, durch das Polling verzögert, wird vermutlich ein stateChanged auf 'on' ausgelöst und Bri auf 254 gesetzt.

**Comment by foxriver76** [comment]
Ist dies noch relevant, nachdem in der Hue App nun der Einschaltzustand nach Stromverlust konfiguriert werden kann (u. a. letzten Zustand wieder herstellen)? Oder geht es tatsächlich um das schalten ohne zwischenzeitlichen Stromverlust?

**Comment by dot-not** [comment]
Hallo zusammen,

ich hätte noch Interesse an der Funktion und eine Frage zum Hintergrund dazu:

Meine Installation funktioniert wie von modmax beschrieben: Ich nutze Homematic Schalter zum Ein- und Ausschalten der Hue Leuchten.
Wenn eine Leuchte zuletzt gedimmt war (z.B. bri < 127) und man sie ausschaltet, wäre es schön, wenn sie beim nächsten Einschalten wieder mit dem gleichen Wert angeht.

Wie von travelbudge erwähnt, verhält sich die Hue App auch so.
In den Hue Leuchten gibt es den Datenpunkt 'on'. Wenn per HTTP PUT ein { "on": true } an den State einer Leuchte geschickt wird, wird sie mit der letzten Helligkeit eingeschaltet. Das ist das gewünschte Verhalten.
Soweit ich gesehen habe, wandelt der Adapter allerdings Werteänderungen für den ioBroker Datenpunkt 'on' in Änderungen an 'bri' um und setzt 0 bzw. 254.
Ist das eine technische Notwendigkeit?

Viele Grüße,
dot-not

**Comment by foxriver76** [comment]
Man sollte den Nutzer wählen lassen, welches Verhalten er wünscht.

**Comment by dot-not** [comment]
Neben "on" gibt es ja noch "bri", welches verwendet werden kann, wenn man einen festen Wert vorgeben möchte.

**Comment by foxriver76** [comment]
https://github.com/iobroker-community-adapters/ioBroker.hue/commit/8466f465942f912935d741ba3b249dd9e979f7ca

**Comment by foxriver76** [comment]
Bitte 2.1.0 probieren und in den Adaptereinstellungen den Haken setzen, dass das native Einschaltverhalten gewünscht ist.
