### ISSUE TITLE
No Delay for Hue anymore

### ISSUE THREAD

**Issue by XSDiVer** [iobroker-community-adapters/ioBroker.hue#343]
Hello,

I found a Script with cancel the Delay between,
ioBroker and the HUE Bridge.

it would be a good thing if the switching of HUE lamps and motion sensors could be integrated into ioBroker without delay.

https://www.smarthomejetzt.de/hue-bewegungsmelder-und-lampen-ohne-verzoegerung-mit-hue-push-api-in-iobroker-einbinden/

I don’t tested the Script - but the Idea is Great, if it works.

Thank you,

XSD

**Comment by mtoensing** [comment]
Should fix the latency for the hue switch, too! Would be great if this were part of the adapter!

**Comment by Baenker** [comment]
#227

**Comment by foxriver76** [comment]
implemented in 3.9.0
