### ISSUE TITLE
Use the "device"-Type for the lights instead of the bridge

### ISSUE THREAD

**Issue by WolfspiritM** [iobroker-community-adapters/ioBroker.hue#36]
Coming from https://github.com/ioBroker/ioBroker.cloud/issues/45

For the cloud adapter we need to find out the correct toggle/dimmer for the device. Especially for percentage. Right now we're looking for all the numeric state Objects inside the same channel and if one of it is a level.dimmer we ignore all the other. This works for Hue and Tradfri but Homematic does have different channels for brightness and color. So it sets brightness, but also the hue/color value for example.

The correct implementation would be to look for the "device" and use that as starting point. If there is any level.dimmer beneath the device we will use that. This would work for Tradfri and Homematic but right now the Hue Adapter only has the Bridge as Device and not the lights.

I think that change would also mean to remove the bridge from the ID and introduce a "fake" channel similar to the Tradfri "lightbulb" implementation by @AlCalzone. But that would break all existing scripts for hue as the ID will change drastically. A less destructive but less "clean" solution would be to just change the type for the lights from channel to device.

Current:

| Adapter  | Device | Channel | State |
| ------------- | ------------- | ------------- | ------------- |
| hue.0  | Philips_hue  | Go  | level
| hue.0  | Philips_hue  | Go  | hue
| tradfri.0  | Light-ID  | lightbulb (fake)  | level
| tradfri.0  | Light-ID  | lightbulb (fake)  | hue
| hpm.0  | Device-ID  | 0  | level
| hpm.0  | Device-ID  | 1  | hue

Needed:

| Adapter  | Device | Channel | State |
| ------------- | ------------- | ------------- | ------------- |
| hue.0  | Go  | xxx  | level
| hue.0  | Go  | xxx  | hue
| tradfri.0  | Light-ID  | lightbulb (fake)  | level
| tradfri.0  | Light-ID  | lightbulb (fake)  | hue
| hpm.0  | Device-ID  | 0  | level
| hpm.0  | Device-ID  | 1  | hue

**Comment by foxriver76** [comment]
If you want to prepare this as a PR we could introduce this in a breaking v2, with a fix for hue/ct values and possibility to control scenes as done by https://github.com/cernst1980/iobroker.hue_scenes

**Comment by foxriver76** [comment]
If we go for this scenario, the question is if Rooms/Groups should also be of type device.
