### ISSUE TITLE
allOn and anyOn of Groups not working, if single Lamp turned on/off

### ISSUE THREAD

**Issue by Schmakus** [iobroker-community-adapters/ioBroker.hue#372]
**Describe the bug**
If a single lamp assigned to a group is switched on, the "anyOn" datapoint does not change. (see the screenshot)
Also if all lamps turned on, the datapoint "allOn" does not change.

**To Reproduce**
1. turn on single lamp2. 
2. look anyOn Datapoint of Room

**Expected behavior**
anyOn should turned on

**Screenshots & Logfiles**
![Xnip2023-01-05_22-18-46](https://user-images.githubusercontent.com/8231359/210883003-87f6fdba-ce88-440c-afd3-44e029976837.jpg)

**Versions:**
 - Adapter version: v3.7.1
 - JS-Controller version: 4.0.23
 - Node version: v16.18.0
 - Operating system: <os-name>
 - Bridge model: <bridge-model>

**Additional context**

**Comment by foxriver76** [comment]
The datapoints are provided 1:1 out of the API, there is no logic to calculate `anyOn` or `allOn` ourselves. 

If you switch a light via iob the light itself will be polled once right after the change and the group only at the next polling interval, in this case it can be out of sync even if the API provides correct values.

**Comment by Schmakus** [comment]
ok, but it would be possible with a little bit of coding?

**Comment by Schmakus** [comment]
Hi, maybe it's now possible with the push API? because ```bri``` and ```level``` also works. Please double check. Thx!
