### ISSUE TITLE
Szenen von der Hue-Bridge abfragen und über Objekte aktivierbar machen

### ISSUE THREAD

**Issue by Baenker** [iobroker-community-adapters/ioBroker.hue#39]
Ich fände es sinnvoll wenn der Hue Adapter die Szenen aus der Hue-Bridge ausliest und man diese dann einfach steuern kann.

Diese Szenen werden sowieso von Alexa bzw Siri genutzt sofern man Alexa bzw Siri mit der Hue-Bridge koppelt. Somit kann man zentral die Szenen pflegen und überall verwenden. Vorteil wenn ich eine Szene per iobroker schalte sehe ich den Zustand in Siri oder wenn ich per Alexa eine Szene aktiviere sieht man dies danach in vis usw.

Zu dem Thema existiert bereits ein quick & dirty Script

[](https://forum.iobroker.net/viewtopic.php?f=21&t=11610)

**Comment by mikiline** [comment]
Push! Danke

**Comment by Baenker** [comment]
Als Zwischenlösuzng nutze ich: https://github.com/cernst1980/iobroker.hue_scenes

wird einfach als Script eingebunden.

**Comment by foxriver76** [comment]
implemented in https://github.com/iobroker-community-adapters/ioBroker.hue/commit/a175313f3db89ac60eeab04f21d123d496b84c8f
