### ISSUE TITLE
Lampen level wird beim ausschalten per Hue App nicht auf 0 geändert.

### ISSUE THREAD

**Issue by Baenker** [iobroker-community-adapters/ioBroker.hue#408]
**Describe the bug**
Ausgangslage on = false und level = 0

Schalte ich den on-Datenpunkt bei der Lampe auf true ändert sich level auf 100. Schalte ich den on Datenpunkt auf false ändert sich level auf 0.

Mache ich das gleiche per Hue App wird der nur on Datenpunkt veröndert. Schalte ich per ioBroker eine Szene wird ebenfalls nur der on Datenpunkt verändert.

Syncronisation ist auf 61 Sekunden eingestellt. Die Zeit habe ich natürlich abgewartet.

**Comment by foxriver76** [comment]
Mit 3.7.1 auch das Problem?

**Comment by foxriver76** [comment]
Ansonsten kann man das konfigurieren mit natives Einschaltverhalten

**Comment by Baenker** [comment]
Installiert ist derzeit die 3.8. Dort habe ich gerade auf nativ umgestellt was aber nichts ändert. Mit der Vorversion war das verhalten (ohne nativ) anders.

**Comment by Baenker** [comment]
Gerade die 3,71 installiert. Dort ist das verhalten richtig. Sollte also mit der neuen Version zusammen hängen

**Comment by foxriver76** [comment]
Bitte von GitHub probieren, die GH Version hat auch bereits die Push API partiell integriert. Hier gerne separate Issues öffnen wenn Unknown update for type ... Meldungen kommen

**Comment by Baenker** [comment]
Sorry @foxriver76 habe es nicht eher geschafft. Mit der Github Version funktioniert es. Das Sahnetüpfelchen ist natürlich das endlich push integriert ist. Auch das funktioniert bisher zuverlässig. Schade natürlich das wenn das Licht per App oder Szene eingeschaltet wird das der Level nicht auch sofort den richtigen Wert hat sondern erst nach dem normalen pull aber vermutlich hat Hue das noch nicht integriert.

Ich sage auf jeden Fall vielen vielen Dank nicht nur für die Betreuung dieses Adapters sondern auch der Homematic Adapter und natürlich all der anderen Arbeit die Du dir machst. Spende im Dezember ist vorgemerkt :-)

**Comment by foxriver76** [comment]
Hi @Baenker das Level sollte nun mit 3.9.0 auch aktualisiert werden. Bislang allerdings nur von einzelnen Lampen. Ich bin da noch etwas am rumprobieren für Gruppen. ;-)

**Comment by Baenker** [comment]
@foxriver76 dann muss ich leider sagen das es nicht funktioniert (per Push oder zumindest mit einer Verzögerung). Ich habe primär bei einzelnen Lampen geguckt. Gruppe habe ich zwar auch angeguckt das war mir aber nicht so wichtig, da bei einer Gruppe der level ja max ein Mittelwert von mehreren Lampen sein kann.

**Comment by foxriver76** [comment]
Sicher, dass du die 3.9.0 drauf hast? Bei mir läuft es, eben nochmal getestet. Am Anfang wurde nur `on` synchronisiert.

**Comment by Baenker** [comment]
@foxriver76 relativ sicher. Ich habe per Github installiert und anschließend noch den Button upload gedrückt. Im Admin zeigt er mir auch die 3.9 an. Sicheres Indiz ist ja das push funktioniert obwohl ich das Push Script vorher deaktiviert habe.

Wie ich getestet habe: Ich habe einen Raum mit einer Hue Lampe. Der Raum hat zwei Szenen „hell“ und „gedimmt“. Setze ich nun in ioBroker bei dem Raum die Szene auf true schaltet das Licht an und das on-Objekt in der Gruppe (=Raum) und das on-Objekt bei der Lampe wird sofort true. Level bleibt sowohl im Raum als auch bei der Lampe auf 0. Mein pull Intervall ist auf 61 Sekunden gestellt. Innerhalb von 61 Sekunden im üngünstigsten Fall wird Level sowohl bei der Gruppe als auch bei der Lampe auf 100 gestellt (Szene hell hat level 100). Schalte ich nun per Handy den Raum aus ändert sich wieder nur beide on Objekte auf false Level bleibt bei 100 und ändert sich innerhalb von max 61 Sekunden auf 0. 

Weiterer Test per App. Dort gehe ich in den Raum und schalte die Lampe auf ein (also wirklich die Lampe) auch hier werden die on Objekte sofort auf true gestellt während level bei 0 bleibt bis zur Syncronisation.

**Comment by foxriver76** [comment]
Wenn du Loglevel auf `debug` stellst, könntest du mal bitte bei deinen Tests die Log Meldungen raus kopieren, die mit

```New push connection update: ...``` starten. Evtl. lässt sich da sehen woran es scheitert.
