### ISSUE TITLE
Dimmer-Level springt immer erst kurz auf 100% dann auf den eingestellten Wert

### ISSUE THREAD

**Issue by Smarti15** [iobroker-community-adapters/ioBroker.hue#41]
Hi Leute,

ich habe mir im Flur ein Script gebaut, wo Nachts durch einen Bewegungsmelder das Licht eingeschaltet wird. Die Philipps Hue sollen dann bei 50 % einschalten. Das funktioniert auch super.

Nun hab ich festgestellt, wenn man zwischendurch mit der Hue App auf dem Smartphone spielt und die Farben ändert, das dann beim Nachtlicht auch diese letztem gespeicherten Farben in der Hue App erscheinen. Das ist natürlich blöd, also hab ich gedacht kein Problem, gibtst du im Script die RGB Werte an. Sobald ich das aber machen, schalte die Lampe auf 100% und dimmt dann erst runter auf die 50% das ist doch recht störend, dieses aufflackern. Könnt ihr da vielleicht was machen oder vielleicht geht es auch schon und ich mach es nur falsch im Script? Danke!

Hier mal ein kurzer Ausschnitt:

``` on({id: "hm-rpc.0.LTK0113395.1.MOTION"/*Flur_BM_EG.MOTION*/, val: true}, function (obj) {
  var value = obj.state.val;
  var oldValue = obj.oldState.val;
  if (compareTime(getAstroDate("sunrise", undefined, 0), getAstroDate("sunset", undefined, 0), "not between", null)) {
    setState("hue.0.Hue_Bridge_1.Flur_Licht_rechts.on"/*Hue_Bridge_1.Flur_Licht_rechts.on*/, true);
    setState("hue.0.Hue_Bridge_1.Flur_Licht_rechts.level"/*Hue_Bridge_1.Flur_Licht_rechts.level*/, parseFloat(50));
    setState("hue.0.Hue_Bridge_1.Flur_Licht_links.b"/*Hue_Bridge_1.Flur_Licht_links.b*/, parseFloat(68));
    setState("hue.0.Hue_Bridge_1.Flur_Licht_links.g"/*Hue_Bridge_1.Flur_Licht_links.g*/, parseFloat(184));
    setState("hue.0.Hue_Bridge_1.Flur_Licht_links.r"/*Hue_Bridge_1.Flur_Licht_links.r*/, parseFloat(204));
    setState("hue.0.Hue_Bridge_1.Flur_Licht_links.level"/*Hue_Bridge_1.Flur_Licht_links.level*/, parseFloat(50));
    setState("hue.0.Hue_Bridge_1.Flur_Licht_links.on"/*Hue_Bridge_1.Flur_Licht_links.on*/, true);
    setState("hue.0.Hue_Bridge_1.Flur_Licht_rechts.b"/*Hue_Bridge_1.Flur_Licht_rechts.b*/, parseFloat(68));
    setState("hue.0.Hue_Bridge_1.Flur_Licht_rechts.g"/*Hue_Bridge_1.Flur_Licht_rechts.g*/, parseFloat(184));
    setState("hue.0.Hue_Bridge_1.Flur_Licht_rechts.r"/*Hue_Bridge_1.Flur_Licht_rechts.r*/, parseFloat(204));
    setState("hue.0.Hue_Bridge_1.Flur_Licht_OG.on"/*Hue_Bridge_1.Flur_Licht_OG.on*/, true);
    setState("hue.0.Hue_Bridge_1.Flur_Licht_OG.level"/*Hue_Bridge_1.Flur_Licht_OG.level*/, parseFloat(30));
    setState("hue.0.Hue_Bridge_1.Flur_Licht_OG.b"/*Hue_Bridge_1.Flur_Licht_OG.b*/, parseFloat(68));
    setState("hue.0.Hue_Bridge_1.Flur_Licht_OG.g"/*Hue_Bridge_1.Flur_Licht_OG.g*/, parseFloat(184));
    setState("hue.0.Hue_Bridge_1.Flur_Licht_OG.r"/*Hue_Bridge_1.Flur_Licht_OG.r*/, parseFloat(204));
  }
```

**Comment by Pmant** [comment]
Es passiert ja genau das, was im Script steht. Er wird eingeschaltet (on = 100%), dann gedimmt, dann die Farbe geändert. Du kannst den command Datenpunkt nutzen um mehrere Änderungen gleichzeitig vorzunehmen. Z. B. : 
`setState('hue.0.bridge.lampe.command', '{"level": 30, "ct": 250}')`

Ich schließe hier mal, das ist eher kein Fehler. Wenn noch Klärungsbedarf besteht einfach im Forum fragen.
