### ISSUE TITLE
Lampenstatus wird nicht richtig gesetzt

### ISSUE THREAD

**Issue by Eistee82** [iobroker-community-adapters/ioBroker.hue#410]
Der Lampenstatus anyOn wird nicht korrekt gesetzt. Ich verwende außerdem noch Hue extended wo dieser korrekt auf true geschalten ist. Siehe Screenshot:
![image](https://github.com/iobroker-community-adapters/ioBroker.hue/assets/1881217/6305d315-cd7a-4165-b38e-5267950ee0ed)

Adapter 3.8.0
Host 4.0.24
Hue Bridge 2 (eckig)

**Comment by foxriver76** [comment]
Mit 3.7.1 auch das Problem?

**Comment by Eistee82** [comment]
Mit 3.7.1 funktioniert es:
![image](https://github.com/iobroker-community-adapters/ioBroker.hue/assets/1881217/68185877-170d-4142-9483-51b834846b03)

**Comment by Negalein** [comment]
@foxriver76 

hab mit 3.8.0 auch das Problem.
bei Großteil der `hue.0.xxx.on`

**Comment by foxriver76** [comment]
Hat es evtl. Mit der neu eingeführten Funktion zu tun die über PR rein gekommen ist mit dem “turn on with others” Oder so ähnlich? Sorry, gerade nur am Handy ;-)

**Comment by Negalein** [comment]
> mit dem “turn on with others”

eher nicht.
Problem besteht, egal ob "turn on with others ..." aktiviert ist oder nicht.

**Comment by foxriver76** [comment]
Ok, irgendwie werden einige DPs nicht mehr aktualisiert, siehe auch #408 ich schaue es mir an

**Comment by foxriver76** [comment]
Bitte von GitHub probieren, die GH Version hat auch bereits die Push API partiell integriert. Hier gerne separate Issues öffnen wenn `Unknown update for type ...` Meldungen kommen

**Comment by Negalein** [comment]
> Bitte von GitHub probieren

passt derzeit.
Ich werde es beobachten.
