### ISSUE TITLE
Motion Sensor 'Presence' bleibt auf 'false'

### ISSUE THREAD

**Issue by StoniHome** [iobroker-community-adapters/ioBroker.hue#412]
Nach Update auf Version 3.8.0 reagiert kein Motion Sensor mehr (habe 3 im Einsatz) . Der Presence Status bleibt auf 'false'. 
Über die Hue App (Smartphone) wird jedoch geschaltet) allerdings funktioniert das schalten über Scripte in IOB nicht mehr.
Nach Rückkehr auf Version 3.7.1 funktionierte alles wieder wie vorher. Alle Funktionen lassen sich auch wieder aus IOB steuern und der Status 'presence' geht auch wieder auf 'true'. 

- Adapter version: 3.8.0 --> fail
- JS-Controller: 16.18.0
- IOB : 6.5.7
- Bridge 2 (eckig)

Gruß Holger

**Comment by foxriver76** [comment]
duplicate of #410 #408
