### ISSUE TITLE
Mit Version 3.9 Unknown update for type "xxxxx"

### ISSUE THREAD

**Issue by Baenker** [iobroker-community-adapters/ioBroker.hue#413]
Im Log taucht bei mir mit der neuen Hue Version incl push folgende Fehlermeldung auf:

`Unknown update for type "scene": {"id":"65afcc6a-da67-4784-a2c8-9ec114f79395","id_v1":"/scenes/yb7TUTkOifXlUD6","status":{"active":"static"},"type":"scene"}`

**Comment by foxriver76** [comment]
Dann fangen wir mal an zu sammeln: 

```
Unknown update for type "entertainment_configuration": 
{"active_streamer":{"rid":"fa2b6425-206c-40b0-82bc-2fd85d5422d0","rtype":"auth_v1"},"id":"0e1af2e6-89f1-4f9b-9ba1-2046a43dbc9d","id_v1":"/groups/200","status":"active","type":"entertainment_configuration"}
```

**Comment by RP70DP** [comment]
`2023-06-12 07:19:04.804  - [33mwarn[39m: hue.0 (11300) Unknown update for type "scene": {"id":"072c3706-4666-4cfa-ab10-612b4fd6546b","id_v1":"/scenes/rMUdChAxNllb6E3","status":{"active":"static"},"type":"scene"}
2023-06-12 07:19:16.365  - [33mwarn[39m: hue.0 (11300) Unknown update for type "scene": {"id":"404d9d67-dadd-45a3-9439-126c8260a483","id_v1":"/scenes/5kqjegTdE6tAjvn","status":{"active":"static"},"type":"scene"}
2023-06-12 07:38:02.159  - [33mwarn[39m: hue.0 (11300) Unknown update for type "button": {"button":{"button_report":{"event":"initial_press","updated":"2023-06-12T05:38:01.204Z"},"last_event":"initial_press"},"id":"645e2a8d-74ea-492e-98b9-4297e2599250","id_v1":"/sensors/20","owner":{"rid":"25ffcc31-98a2-432b-9100-3c7a25a55f5e","rtype":"device"},"type":"button"}
2023-06-12 07:38:03.167  - [33mwarn[39m: hue.0 (11300) Unknown update for type "button": {"button":{"button_report":{"event":"short_release","updated":"2023-06-12T05:38:01.347Z"},"last_event":"short_release"},"id":"645e2a8d-74ea-492e-98b9-4297e2599250","id_v1":"/sensors/20","owner":{"rid":"25ffcc31-98a2-432b-9100-3c7a25a55f5e","rtype":"device"},"type":"button"}
2023-06-12 07:38:47.311  - [33mwarn[39m: hue.0 (11300) Unknown update for type "scene": {"id":"f71e41ef-fea3-4c17-9185-dee65ab6dce8","id_v1":"/scenes/TNGxBTr6i9TMDnn","status":{"active":"inactive"},"type":"scene"}`

**Comment by foxriver76** [comment]
> `2023-06-12 07:19:04.804 - �[33mwarn�[39m: hue.0 (11300) Unknown update for type "scene": {"id":"072c3706-4666-4cfa-ab10-612b4fd6546b","id_v1":"/scenes/rMUdChAxNllb6E3","status":{"active":"static"},"type":"scene"} 2023-06-12 07:19:16.365 - �[33mwarn�[39m: hue.0 (11300) Unknown update for type "scene": {"id":"404d9d67-dadd-45a3-9439-126c8260a483","id_v1":"/scenes/5kqjegTdE6tAjvn","status":{"active":"static"},"type":"scene"} 2023-06-12 07:38:02.159 - �[33mwarn�[39m: hue.0 (11300) Unknown update for type "button": {"button":{"button_report":{"event":"initial_press","updated":"2023-06-12T05:38:01.204Z"},"last_event":"initial_press"},"id":"645e2a8d-74ea-492e-98b9-4297e2599250","id_v1":"/sensors/20","owner":{"rid":"25ffcc31-98a2-432b-9100-3c7a25a55f5e","rtype":"device"},"type":"button"} 2023-06-12 07:38:03.167 - �[33mwarn�[39m: hue.0 (11300) Unknown update for type "button": {"button":{"button_report":{"event":"short_release","updated":"2023-06-12T05:38:01.347Z"},"last_event":"short_release"},"id":"645e2a8d-74ea-492e-98b9-4297e2599250","id_v1":"/sensors/20","owner":{"rid":"25ffcc31-98a2-432b-9100-3c7a25a55f5e","rtype":"device"},"type":"button"} 2023-06-12 07:38:47.311 - �[33mwarn�[39m: hue.0 (11300) Unknown update for type "scene": {"id":"f71e41ef-fea3-4c17-9185-dee65ab6dce8","id_v1":"/scenes/TNGxBTr6i9TMDnn","status":{"active":"inactive"},"type":"scene"}`

Can you show me the datapoints in ioBroker for the button?

**Comment by Baenker** [comment]
Bekomme das gleiche. Anbei ein Bild der Datenpunkte:
<img width="1351" alt="Bildschirmfoto 2023-06-12 um 15 10 46" src="https://github.com/iobroker-community-adapters/ioBroker.hue/assets/22763577/3be60c4f-ec92-462b-80d8-eec00e68988a">

**Comment by RP70DP** [comment]
`2023-06-12 19:53:03.899  - [33mwarn[39m: hue.0 (11300) Unknown update for type "button": {"button":{"button_report":{"event":"initial_press","updated":"2023-06-12T17:53:03.530Z"},"last_event":"initial_press"},"id":"a987e5c3-4962-423a-9c33-1e6684697b2a","id_v1":"/sensors/43","owner":{"rid":"b1a245d5-afae-4d59-85a5-4f5849db73ac","rtype":"device"},"type":"button"}
2023-06-12 19:53:04.913  - [33mwarn[39m: hue.0 (11300) Unknown update for type "button": {"button":{"button_report":{"event":"short_release","updated":"2023-06-12T17:53:03.664Z"},"last_event":"short_release"},"id":"a987e5c3-4962-423a-9c33-1e6684697b2a","id_v1":"/sensors/43","owner":{"rid":"b1a245d5-afae-4d59-85a5-4f5849db73ac","rtype":"device"},"type":"button"}`

`{
  "_id": "hue.0.Wohnzimmer_Schalter_Tisch.buttonevent",
  "type": "state",
  "common": {
    "name": "Wohnzimmer Schalter Tisch.buttonevent",
    "read": true,
    "write": false,
    "role": "state",
    "type": "number",
    "def": 4002
  },
  "native": {
    "id": "43"
  },
  "from": "system.adapter.hue.0",
  "user": "system.user.admin",
  "ts": 1686545033927,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`

![hue_button](https://github.com/iobroker-community-adapters/ioBroker.hue/assets/62850183/ce47d36d-371e-40b0-9db4-db9d8e516fb9)

**Comment by foxriver76** [comment]
does someone know the encoding for the button actions like `short_release` to the ones which we receive via polling like `4002`? ;-) 

Else I will look into the docs, and hope to find the information

**Comment by Baenker** [comment]
das kommt auf den Taster an bei mir 

Ausschnitt aus einen Script im log habe ich geschrieben was es bedeutet:

`if(Schalter_kurz == '1'){
        if(debugging2){
            log('[DEBUG] ' +'Schalter Schlafzimmer Taste 1 wurde gedrückt: '+Schalter);
        }

        if(Schalter == 1000){
            if(debugging){
                log('[DEBUG] ' +'Kurzer Tastendruck Taste 1 Schlafzimmer --- func_Licht_an_dyn wird gestartet');
            }

            func_Licht_an_dyn();

        }
        else if(Schalter == 1001){
        
            if(debugging){
                log('[DEBUG] ' +'Langer Tastendruck Taste 1 Schlafzimmer');
            }
        

        }
        else if(Schalter == 1002){
            if(debugging2){
                log('[DEBUG] ' +'Loslassen kurzer Tastendruck Taste 1 Schlafzimmer');
            }
        

        }
        else if(Schalter == 1003){
            if(debugging){
                log('[DEBUG] ' +'Loslassen nach Langer Tastendruck Taste 1 Schlafzimmer');
            }
        

        }
    }
    else if(Schalter_kurz == '2'){
        if(debugging2){
            log('[DEBUG] ' +'Schalter Schlafzimmer Taste 2 wurde gedrückt: '+Schalter);
        }


        if(Schalter == 2000){
            if(debugging){
                log('[DEBUG] ' +'Kurzer Tastendruck Taste 2 Schlafzimmer --- func_Licht_aus wird gestartet');
            }

            func_Licht_aus();

        }
        else if(Schalter == 2001){
            if(debugging){
                log('[DEBUG] ' +'Langer Tastendruck Taste 2 Schlafzimmer');
            }
        

        }
        else if(Schalter == 2002){
            if(debugging2){
                log('[DEBUG] ' +'Loslassen nach kurzen Tastendruck Taste 2 Schlafzimmer');
            }
        

        }
        else if(Schalter == 2003){
            if(debugging){
                log('[DEBUG] ' +'Loslassen nach Langer Tastendruck Taste 2 Schlafzimmer');
            }
        

        }

    }
    else if(Schalter_kurz == '3'){
        if(debugging2){
            log('[DEBUG] ' +'Schalter Schlafzimmer Taste 3 wurde gedrückt: '+Schalter);
        }
        
        if(Schalter == 3000){
            if(debugging){
                log('[DEBUG] ' +'kurzer Tastendruck Taste 3 Schlafzimmer --- func_Licht_an_sehr_hell');
            }
            func_Licht_an_sehr_hell();
        

        }
        else if(Schalter == 3001){
            if(debugging){
                log('[DEBUG] ' +'Langer Tastendruck Taste 3 Schlafzimmer');
            }
        

        }
        else if(Schalter == 3002){
            if(debugging2){
                log('[DEBUG] ' +'Loslassen nach  kurzer Tastendruck Taste 3 Schlafzimmer');
            }
        

        }
        else if(Schalter == 3003){
            if(debugging){
                log('[DEBUG] ' +'Loslassen nach Langer Tastendruck Taste 3 Schlafzimmer');
            }
        

        }
    }
    else if(Schalter_kurz == '4'){
        if(debugging2){
            log('[DEBUG] ' +'Schalter Schlafzimmer Taste 4 wurde gedrückt: '+Schalter);
        }

        if(Schalter == 4000){
            if(debugging){
                log('[DEBUG] ' +'kurzer Tastendruck Taste 4 Schlafzimmer --- func_Licht_aus wird gestartet');
            }

            func_Licht_aus();
        

        }
        else if(Schalter == 4001){
            if(debugging){
                log('[DEBUG] ' +'Langer Tastendruck Taste 4 Schlafzimmer');
            }
        

        }
        else if(Schalter == 4002){
            if(debugging2){
                log('[DEBUG] ' +'loaslassen nach kurzen Tastendruck Taste 4 Schlafzimmer');
            }
        

        }
        else if(Schalter == 4003){
            if(debugging){
                log('[DEBUG] ' +'Loslassen nach Langer Tastendruck Taste 4 Schlafzimmer');
            }
        

        }

    }
    else{
        if(logging){
            log('Schalter Schlafzimmer --- unbekannte Taste . Hier sollte das Script nicht landen '+Schalter);
        }
            
        
    }
    
    


}

`

**Comment by RP70DP** [comment]
'sensors.button.last_event': {stateName: 'buttonevent', convert: (val) => {return ((UUIDs[this.idv2] && UUIDs[this.idv2].metadata) ? UUIDs[this.idv2].metadata.control_id : 0) * 1000 + (val === 'repeat' ? 1 : 0) + (val === 'short_release' ? 2 : 0) + (val === 'long_release' ? 3 : 0)}, validTypes: ['ZLLSwitch']},

Aus dem bekannten Push-API-Skript:
https://forum.iobroker.net/topic/47391/hue-push-api-f%C3%BCr-hue-adapter?_=1686592864895
