### ISSUE TITLE
V3.9.1 Tasten werden anders zurückgegeben

### ISSUE THREAD

**Issue by Baenker** [iobroker-community-adapters/ioBroker.hue#415]
Die Meldungen bezüglich button sind weg aber meine Scripte passen nicht mehr.

Ich nutze Senic Schalter (Friends for hue)

Dort gibt es 4 Tasten. Bisher war es so die erste Taste oben links:
Kurz drücken meldete erst 1000 und danach 1002
Also 1000 = kurzer Tastendruck
1002 = kurzer Tastendruck loslassen

Und es gab noch noch 1001 und 1003
1001 = Langertastendruck
1003 = langen Tastendruck loslassen

Das ganze gab es für jeden Schalter

Man kann zusammenfassen die ersteb beiden Ziefern 10,20,30,40 waren jeweils die taste
und die letzten beiden Ziefern sagte was gemacht wurde 
00 = kurz drücken
02 = kurz drücken loslassen
01 = lang drücken
03 = lang loslassen

Jetzt liefert mit die linke obere Taste 0 und dann 2
drücke ich die linke untere Taste kommt ebenfalls 0 und dann 2. Somit weiß man nicht welche Taste gedrückt wurde. Das finde ich jetzt eher ungünstig :-)

0 und 2 wurde per push ins Object geschrieben. Poll machte dann aus der 2 eine 20 bzw 21 bei der Taste 2

**Comment by foxriver76** [comment]
Jop das ist ungünstig, ich schaue nochmal drüber

**Comment by foxriver76** [comment]
Kannst du mir mal das raw vom channel zeigen? Da müsste der Typ drin stehen, evtl. ist die Codierung dafür nicht geeignet. Bzw. hast du das Skript für Push API damals genutzt und damit hat es funktioniert?

**Comment by Baenker** [comment]
Wo sehe ich das raw vom channel? Ist es das?

`{
  "_id": "hue.0.Schalter_Wohnzimmer_3.buttonevent",
  "type": "state",
  "common": {
    "name": "Schalter Wohnzimmer 3.buttonevent",
    "read": true,
    "write": false,
    "role": "state",
    "type": "number",
    "def": 20
  },
  "native": {
    "id": "59"
  },
  "from": "system.adapter.hue.0",
  "user": "system.user.admin",
  "ts": 1686653604607,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

`

Ja habe das Script aus dem Forum für Push benutzt.

**Comment by foxriver76** [comment]
Fast statt von `hue.0.Schalter_Wohnzimmer_3.buttonevent` das von `hue.0.Schalter_Wohnzimmer_3`

Ok sprich mit dem Skript aus dem Forum wurde dein Schalter aktualisiert und zwar korrekt? *gg*

**Comment by Baenker** [comment]
korrekt und zwar so wie oben beschrieben. 

`{
  "_id": "hue.0.Schalter_Wohnzimmer_3",
  "type": "channel",
  "common": {
    "name": "Schalter Wohnzimmer 3",
    "role": "ZGPSwitch"
  },
  "native": {
    "id": "59",
    "type": "ZGPSwitch",
    "name": "Schalter Wohnzimmer 3",
    "modelid": "FOHSWITCH"
  },
  "from": "system.adapter.hue.0",
  "user": "system.user.admin",
  "ts": 1686653604632,
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`

**Comment by Baenker** [comment]
Nachtrag: Ich meine auch beim poll (mit der alten Adapterversion) wurde das Feld hinterher nicht mehr verändert das heißt es blieb dann bei z. B. bei 1002 = kurzer Tastendruck Taste 1 loslassen

**Comment by Baenker** [comment]
@foxriver76 Vielen Dank. Jetzt funktioniert alles wieder
