### ISSUE TITLE
Temperature measurement hue motion sensor

### ISSUE THREAD

**Issue by Buddeli** [iobroker-community-adapters/ioBroker.hue#424]
**Is your feature request related to a problem? Please describe.**
I can see the temperature from the motion sensor in the HomeKit app from Apple. So I assume that there is a built in sensor for that. With the hue-adapter I couldn't see any temperature value.

**Describe the solution you'd like**
I would like to have the temperature measurement in the ioBroker visible.

**Describe alternatives you've considered**

**Additional context**
Maybe there are further values (humidity) as well.

**Comment by foxriver76** [comment]
The Sensor should show up as a separate device (Channel)

**Comment by Buddeli** [comment]
Ahh, now I can see it. Many thanks for your help.
