### ISSUE TITLE
Farben Datenpunkte für Cloud Adapter

### ISSUE THREAD

**Issue by dslraser** [iobroker-community-adapters/ioBroker.hue#44]
Welche Datenpunkte werden jetzt im Cloud Adapter benötigt um auch die Farben bzw. auch alle anderen Werte schalten zu können ?
Ich hatte bisher

hue
bri
on
ct
sat

Das hat Monate lang funktioniert. Jetzt schaltet die Farbe nur auf rot und weiss.(mit der aktuellen Version)

Ich bin jetzt zurück auf 0.6.9, dort funktioniert es und es wird auch direkt und ohne Verzögerung geschaltet.
Ich schalte z.B. über einen Präsenzmelder Licht im Bad. Beim öffnen der Tür wird sofort Präsenz erkannt und geschaltet (0.6.9). In der aktuellen Version stehe ich schon im Raum und dachte es hätte mal wieder Jemand den Schalter ausgemacht....Auf dem Weg zurück zum Schalter ging dann das Licht an. (ca. 2-3 Sekunden Verzögerung)
Polling habe ich in 0.6.9 auf 5 Sekunden und bisher keine Probleme damit. Ich frage über den Alexa 2 Adapter auch eingeschaltete Lampen ab und lasse die Ansagen, da sind dann 30 Sekunden viel zu lang, da die Lampen schon längst aus sind aber noch mit angesagt wurden.

**Comment by WolfspiritM** [comment]
Hue scheint im moment (zumindest bei mir) nicht zu funktionieren:

![image](https://i.gyazo.com/1221a1ba7cd55801022e4db451d9721e.gif)

**Comment by modmax** [comment]
Das Problem mit den Farben hatte ich auch.
Das kam mit dem Update 1.0.1 rein
--> (bluefox) hue changed from 0-65535 to 0-360°

Damit kann der Cloud-Adapter aber nicht umgehen, da der noch HUE-Werte von 0-65535 erwartet und 0-360 ist dann nur rot.

Müßte wohl eher der Cloud-Adapter gefixt werden, daß er nach Unit ° abfragt und dann entweder 0-360 oder 0-65535  benutzt.

**Comment by Vardaaran** [comment]
Habe das gleiche Problem. Ich schalte meine Hue-Lampen-Farbe (ohne Cloud) bislang über die Datenpunkte:
"hue",
"sat" und
"level".
Ab 1.0.1 funktioniert das so aber nicht mehr - die Farben sind falsch. Wenn ich die gewünschte farbe in der Hue-App einstelle und die Werte in ioBroker abfrage (um sie reproduzieren zu können), werden aber immer noch die alten (falschen) werte angezeigt.
Wie bekomme ich also die richtigen raus?

**Comment by GermanBluefox** [comment]
Please use last 0.6.9. I must fix some bugs in 1.x

вс, 16 сент. 2018 г., 22:15 Vardaaran <notifications@github.com>:

**Comment by mimquadrat** [comment]
no matter what color you say to Alexa. It´s always set red :)

**Comment by foxriver76** [comment]
Should be fixed on GitHub.
