### ISSUE TITLE
SSL fehler 

### ISSUE THREAD

**Issue by ghost** [iobroker-community-adapters/ioBroker.hue#450]
<html><body>

`
hue.0 | 29104 | 2023-08-02 23:02:13.879 | debug | Using https to connect to 192.168.1.155:443
-- | -- | -- | -- | --
hue.0 | 29104 | 2023-08-02 23:02:08.878 | warn | Could not get configuration from HUE bridge (192.168.1.155:443)
hue.0 | 29104 | 2023-08-02 23:02:08.877 | error | Request failed with status code 429
hue.0 | 29104 | 2023-08-02 23:02:08.759 | debug | Using https to connect to 192.168.1.155:443
hue.0 | 29104 | 2023-08-02 23:02:03.768 | error | Could not get UUIDs: Unexpected token < in JSON at position 0
hue.0 | 29104 | 2023-08-02 23:02:03.758 | warn | Could not get configuration from HUE bridge (192.168.1.155:443)
hue.0 | 29104 | 2023-08-02 23:02:03.757 | error | Error
`

schalte ich SSL aus, dann gehts unter Port 80....

installiert ist die v3.9.5

**Comment by GermanBluefox** [comment]
Es ist nicht SSL Fehler, es ist "Zu viele Requests". Vermutlich kann HUE bridge mit SSL nicht so schnell antworten. Bitte polling vergrößern.
