### ISSUE TITLE
bridge v1 - Push connection error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by konwin** [iobroker-community-adapters/ioBroker.hue#457]
**Describe the bug**
Regardless of the port setting of the adapter it always tries to connect to the bridge via 443 and I get every second the entry
`Push connection error: connect ECONNREFUSED 192.168.x.y:443`
in the logs.
As far as I understand the old bridge v1 does not support SSL, because when trying the SSL option of the adapter or using port 443 in the settings I can't get a connection to the bridge. But even withouth SSL and port 80 set up the adapter seems to have some hard coded port 443 setting.
The adapter works with the old bridge v1 and I can control my (even older) LivingColors lamps, but the adapter keeps spamming the logs with the error message from above!

**To Reproduce**
1. Go to 'Logs'
2. Choose 'hue.0' from drop-down
3. See error

**Expected behavior**
When setting up port 80 in the adapter settings I expect it to connect to :80 and not, as stated in the error message, to port :443!

**Versions:**
 - Adapter version: 3.9.3 and 3.9.5 tested
 - JS-Controller version: 4.0.24
 - Node version: v18.16.0
 - Operating system: Raspbian GNU/Linux 10 (buster)
 - Bridge model: v1

**Comment by OneCreek** [comment]
having the same issue. 

ioBroker im Docker. 
Adapter version: 3.9.3 and 3.9.5 tested
JS-Controller version: 4.0.24
Node version: v18.17.1
Operating system: Raspbian GNU/Linux 11 (bullseye)
Bridge model: v1; BSB001; API-Version 1.16.0; SW Version: 01043155

**Comment by foxriver76** [comment]
Yes, the adapter needs to be adapted, to not use the push connection logic when ssl is deactivated.

**Comment by foxriver76** [comment]
3.9.6 auf dem Weg, sollte das fixen
