### ISSUE TITLE
'light id' Error

### ISSUE THREAD

**Issue by nifu777** [iobroker-community-adapters/ioBroker.hue#460]
Hallo zusammen,

ich habe seit etwa 2 Tagen folgendes Problem ohne etwas direkt geändert zu haben:

Weder über VIS noch über die Skripte lassen sich meine Hue Lampen steuern. Der Adapter ist korrekt verbunden. Ich sehe in den Objekten auch die Veränderungen, wenn ich über die Hue App selbst die Lampen steuere.

Das Kuriose ist: Wenn ich im Objektbaum selbst die Lampen auf "true" oder "false" setze, dann wird die Lampe auch gesteuert. Wenn ich die Steuerung jedoch über die VIS oder Skripte wähle, erhalte ich nachfolgenden Fehler:

hue.0 | 2023-08-23 08:50:01.920 | error | Could not set LightState of Philips hue.Wandlampe: No value provided and 'light id' is not optional

Weiß jemand, wo hier das Problem liegen könnte? Sowohl den Raspberry als auch den Adapter habe ich schon mehrfach neu gestartet. 

Node.js: v18.16.1
NPM: 9.5.1
js-controller: 4.0.24

Philips Hue Adapter: v3.9.5: Fehler vorhanden)

Heute Update ausgeführt: Philips Hue Adapter: v3.9.6: Fehler vorhanden)

Danke & beste Grüße!

**Comment by nifu777** [comment]
Habe das Problem gerade gefunden:

In meinen Skripten bzw. in der VIS verweist alles auf

"hue.0.Philips_hue.Wandlampe.on"

Korrekt muss es aber nun sein (weiß nicht ob da irgendwie was umgestellt wurde:

"hue.0.Wandlampe.on"


Entfernt man also das ".Philips_hue" aus dem Pfad, klappt wieder alles ohne Probleme! :)

**Comment by foxriver76** [comment]
Siehe -> https://github.com/iobroker-community-adapters/ioBroker.hue/issues/461 

Es scheint als hat Hue die Bridges umbenannt, welche den Default Namen hatten.

**Comment by Wondermusic** [comment]
Ich habe ein ähnliches Problem (also gleiche Fehlermeldung wie oben beschrieben), allerdings habe ich den Adapter eben erst installiert. Ich laufe derzeit auf 3.9.5, nachdem ich direkt von GitHub die 3.10. geladen hatte (Habe erst gedacht, Fehler im neuen Release).
Seltsamerweise kann ich die Lichter steuern, solange ich sie nicht einzeln auf true setze. Soll heißen, in der Gruppe schalten geht, einzeln nicht. Ich habe mal ein Debuglog angehängt. [hue.log](https://github.com/iobroker-community-adapters/ioBroker.hue/files/12475375/hue.log)
Habe bei der Logaufnahme folgende Reihenfolge geschaltet: 

- Theke, weiß = null Reaktion
- Duschlicht = Geht an, aber nach ca. zwei Sekunden von selbst wieder aus
- Gruppe Bar = Alle Lichter schalten wie gewünscht
- Gruppe Badezimmer = Das Licht schalten wie gewünscht
- Theke, Farbe = Keine Reaktion

Wenn ich die Leuchten über die hue App am Handy schalte, werden mir die Zustandsänderungen alle im iobroker angezeigt.

Ich hatte vorher den Adapter hue.extended am Laufen (weil ich auch einen Deconz in Betrieb habe, wollte ich alles über einen Adapter laufen haben), wo alles funktioniert hat, dieser wird aber leider nicht mehr weiterentwickelt.
