### ISSUE TITLE
Bitte alte Legacy Struktur wieder - No value provided and 'group id' is not optional

### ISSUE THREAD

**Issue by Stormbringer11** [iobroker-community-adapters/ioBroker.hue#461]
Hallo Foxriver,

bin jetzt auf Version 3.9.6 mit dem Adapter aber irgendwie habe ich zunehmend Probleme damit obwohl er vorher perfekt lief.

1. Könntest du bitte irgendwas machen, dass die alte Legacy Struktur wieder hergestellt wird?  Früher waren alle DPs unter hue.0.Philips_hue und jetzt knallt er nochmal 110 Lampen unter hue.0.Hue_Bridge. Habe da zig Skripte und VirtualPower Meter angelegt drunter.
 
2. Command funktioniert gar nicht mehr egal unter welchem DP. Auf Debug kommen im LOG nur immer solche Fehler:

{"on":true,"bri":100,"xy":[0.561,0.4042],"colormode":"xy","transitiontime":90}

hue.0 | 2023-08-23 13:36:39.768 | error | Could not set GroupState of Philips hue.Klolichter: No value provided and 'group id' is not optional
-- | -- | -- | --

Vielen Dank für die Mühe im Voraus :o)

**Comment by foxriver76** [comment]
Ist denn Legacy Struktur nutzen ausgewählt im Adapter?

**Comment by Stormbringer11** [comment]
Ja ist ausgewählt ;-)

**Comment by foxriver76** [comment]
Kann ich nicht nachstellen, eben 3,9.6 lokal installiert, Legacy Struktur angehakt und er legt mir nur DPs innerhalb der Struktur an und sind auch steuerbar. Sowohl Lampen, als auch Gruppen als auch Räume getestet. 

Da bräuchte ich vermutlich mehr Infos.

**Comment by foxriver76** [comment]
ah 

> knallt er nochmal 110 Lampen unter hue.0.Hue_Bridge.

das heißt aber er nutzt die Legacy Struktur, aber du hast deine Bridge umbennant.

**Comment by Stormbringer11** [comment]
Umbenannt habe ich nichts aber in der Hue App heißt sie Hue Bridge. Könnte aber jetzt nicht sagen ob die vorher anders hieß und durch ein Update geändert wurde. Den Namen kann man gar nicht ändern oder?  Also zumindest ist es nicht die Bezeichnung, von der Fritzbox. Ansonsten verlaufen alle Anleitungen ins Leere.

**Comment by wired-ed** [comment]
Hallo zusammen,

> hue.0	2023-08-23 13:36:39.768	error	Could not set GroupState of Philips hue.Klolichter: No value provided and 'group id' is not optional

Ich kann seit Kurzem über den Adapter keine Hue Geräte mehr ansteuern (ich tue das aus jarvis und aus blockly heraus) und bekomme die gleiche Fehlermeldung wie @Stormbringer11. Bis vor Kurzem hat alles noch perfekt funktioniert.

ioBroker ist auf v6.9.1, js-controller auf 5.0.12 und der Philips Hue Bridge Adapter auf 3.9.6

Vielen Dank im Voraus für Tipps!

Viele Grüße
Jan

**Comment by foxriver76** [comment]
Hat hue Villt den default Bridge Namen geändert bei schon existenten bridges?

![IMG_2939](https://github.com/iobroker-community-adapters/ioBroker.hue/assets/25484431/f9413743-9d37-4209-ad2e-05f520c2b44f)

ansonsten mal den objektaum checken ob er eine parallelstruktur angelegt hat

**Comment by Stormbringer11** [comment]
wie ändert man denn den namen? wenn du der meinung bist, dass es daher kommen könnte besteht die möglichkeit durchaus 😉 wie gesagt hab da nie was verstellt. kann’s aber gerne einmal testen. strangerweise funktioniert szenen aufruf aber noch. nur lampen und gruppen direkt ansteuern mag er gar nicht mehr.

**Comment by splizz1st** [comment]
Ich kann die Problemstellung exakt so bestätigen. Bei mir war es auch so. Ich arbeite mit Linkeddevices und habe nun die Verknüpfungen auf die Datenpunkte im neuen 'Ordner' Hue_Bridge erstellt. Das funktioniert soweit. Ich habe aber noch Probleme mit einer Lampe:

`2023-08-25 01:14:49.762  - [33mwarn[39m: linkeddevices.0 (1577) State "hue.0.Philips_hue.Flur_oben.on" has no existing object, this might lead to an error in future versions
2023-08-25 01:14:49.804  - [31merror[39m: hue.0 (20221) Object "Philips_hue.Flur_oben" on stateChange is null, undefined or corrupted`

**Comment by wired-ed** [comment]
> Hat hue Villt den default Bridge Namen geändert bei schon existenten bridges?

Ich habe da definitiv nichts geändert.

**Comment by foxriver76** [comment]
Du bist auch nicht Philips Hue 😬

**Comment by wired-ed** [comment]
> Du bist auch nicht Philips Hue 😬

Whoops, in der Tat - hatte "Hue" als "Du" gelesen - I know - das Alter 🤣

**Comment by Stormbringer11** [comment]
hm, ist es machbar, dass der Adapter wieder den alten Ordnernamen verwendet oder bei der Legacy Struktur dem Nutzer selber auswählen zu lassen welchen Ordner er anlegt? Habe Alias zwar im Einsatz aber bei der Masse an Lampen und DPs wird man wahnsinnig. Da hilft einen der leider auch nicht viel weiter....

**Comment by foxriver76** [comment]
Benenne sie doch in den alten Namen um. 

https://github.com/iobroker-community-adapters/ioBroker.hue/assets/25484431/2628019e-1b42-4764-bd9e-5fb8356ed203

**Comment by Stormbringer11** [comment]
Ein Hund bist du schon, hab immer oben in den Einstellungen rumgefummelt. Werd auch alt ;D Es kann so einfach sein, jetzt scheint wieder alles zu gehen. Vielen lieben Dank und ein schönes Wochenende.
