### ISSUE TITLE
Hue Motion Sensor lässt sich nicht AN/AUS schalten

### ISSUE THREAD

**Issue by H852ing** [iobroker-community-adapters/ioBroker.hue#468]
Hallo,

Seitdem Philips den Motion Sensor aktualisiert hat und das Einstellungsmenü in der Hue App auch anders für die Bewegungssensoren aussieht, lässt sich der Sensor nicht mehr über den ioBroker Adapter ein- oder ausschalten.

Ich habe sonst den "hue.0.Hue_motion_sensor_(Flur).on" einfach mit true/false schalten können.
Leider ignoriert die Hue Bridge die Einstellungen seit dem Update der Sensoren bzw. des Einstellungsmenüs einfach.

Davor hat auch eine Änderung des Wertes im ioBroker Adapter dafür gesorgt, dass der Schalter in der Hue App entsprechend aktualisiert wird. Das passiert jetzt ebenfalls nicht mehr.

Ist es möglich, hier vielleicht anzusetzen und zu prüfen, was Philips geändert hat, sodass es wieder möglich ist, den Bewegungssensor ein- oder auszuschalten?

Es wäre großartig, wenn das wieder funktionieren würde.

Vielen Dank.

**Comment by haselchen** [comment]
@H852ing 

Moin, 
in Deinen Ausführungen wären natürlich noch die Versionsnummern hilfreich gewesen.
Einerseits von Deinem System, welche Node Version, JS Controller etc. und dann noch die Adapter Version von HUE.
Ich habe die 3.10.0 und JS Controller 4.0.24 und Node 18.
Bei mir werden die Datenpunkte vom Bewegungsmelder in der App sofort aktualisiert.


Bedeutet, dass wir bei Dir gucken müssen wo es hakt.

![grafik](https://github.com/iobroker-community-adapters/ioBroker.hue/assets/42101470/7303a97b-49f7-4330-917c-196df0474272)

Der Haken darf **nicht** gesetzt werden, dann klappt es. Sonst nicht.

**Comment by H852ing** [comment]
@haselchen

Danke für deine Antwort.
Momentan habe ich noch die 3.9.5 des Adapters installiert.
Beim JS Controller bin ich auch bei 4.0.24 aber bei Node habe ich noch die v16.19.0
Ich habe es aus der Objekte Oberfläche ohne als auch mit "Bestätigt" probiert.
Leider ändert sich in der Hue App unter Zubehör auf dem Smartphone der Schalter nicht.


Ich werde mal versuchen es auf exakt deine Versionskombination zu heben.
Ich melde mich dann noch einmal.
Schon einmal danke für deine Unterstützung.

**Comment by H852ing** [comment]
@haselchen 

Neue Erkentniss,...
Ich habe den Hue Adapter 3.9.5 mal komplett deinstalliert und den kompletten Objektbaum entfernt und dann die 3.9.5 wieder installiert und alles neu ziehen lassen.

Siehe da,... Jetzt funktioniert es.
Ohne das ich irgendwas an der Node oder JS Controller Version geändert habe.

Also hat sich irgendwie der Adapter wohl leicht verschluckt und ein bereinigen hat geholfen.
Darauf hätte ich aber echt schon früher kommen können.

Schande über mich^^
