### ISSUE TITLE
Version 1.1.1

### ISSUE THREAD

**Issue by Stormbringer11** [iobroker-community-adapters/ioBroker.hue#47]
Aktuelle Version funktioniert leider auch total unzuverlässig beim Ausschalten und Einschalten z. T. stark verzögert. Auch werden Farben von Szenen im Orangebereich falsch dargestellt. Bisher war die 0.6.9 noch die Beste abgesehen davon, dass sie das Log mit Fehlern zugepflastert hat und ioBroker verlangsamt hat

**Comment by Gatlingod** [comment]
https://github.com/iobroker-community-adapters/ioBroker.hue/issues/40
