### ISSUE TITLE
Creating a User is not possible

### ISSUE THREAD

**Issue by edstrinova** [iobroker-community-adapters/ioBroker.hue#481]
**Describe the bug**
Entering the correct IP address, clicking on Create User and then on the Hue button does not happen. In the logs it says "Could not get configuration from HUE bridge (192.168.0.76:443)".

**To Reproduce**
Entering the correct IP address, clicking on Create User and then on the Hue button does not happen. In the logs it says "Could not get configuration from HUE bridge (192.168.0.76:443)".

**Expected behavior**
Create User should work.

**Screenshots & Logfiles**
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**
 - Adapter version: 3.9.5
 - JS-Controller version: 5.0.12
 - Node version: v18.17.1
 - Operating system: debian
 - Bridge model: api/config: {"name":"XX","datastoreversion":"161","swversion":"1959194040","apiversion":"1.59.0","mac":"00:XX:XX:XX:XX:XX","bridgeid":"001788FFFE404C56","factorynew":false,"replacesbridgeid":null,"modelid":"BSB002","starterkitid":""}

**Additional context**

**Comment by Schiiiinken** [comment]
see this great solution given by https://developers.meethue.com/support/:

https://developers.meethue.com/develop/get-started-2/

thx :-)

**Comment by EuloTV** [comment]
same problem here
