### ISSUE TITLE
Seit jüngstem Bridge Update > regelmäßiger Disconnect des Adapters

### ISSUE THREAD

**Issue by tommy536** [iobroker-community-adapters/ioBroker.hue#49]
Hallo,

vor kurzem gab es ein Hue Bridge Udpate auf SW 1810251352.

1. Seit dem Update der Bridge verliert der Adapter in Version 1.1.0 nach ein paar Stunden Betrieb seine Verbindung und muss neu über ioBroker gestartet werden.

2. Über ioBroker wird mir nur Version 1.1.0 angeboten und nicht 1.1.1. Warum ist das so?

Grüße

**Comment by tommy536** [comment]
Update: Es scheint nach einiger Laufzeit eine Anhäufung von Errors zu geben. Inhalt des Errors ist immer: Timeout for Polling....

Jedes Objekt wird dann mit einem Error ausgegeben. Der Adapter läuft dann scheinbar über?

**Comment by Mauflo** [comment]
Leider schaltet bei felerhaftem Polling ab und zu eine Lampe aus. ist immer eher zufällig und sehr lästig!

**Comment by foxriver76** [comment]
Should be fixed on GitHub
