### ISSUE TITLE
Adapter is not working anymore

### ISSUE THREAD

**Issue by a-i-ks** [iobroker-community-adapters/ioBroker.hue#51]
Since recently the adapter doesn't work for me anymore. The objects can be read from the bridge, but a state change is unfortunately no longer transferred.
My bridge runs on SW: 1811120916
I am using the latest version of the adapter (1.1.1)

**Comment by Baenker** [comment]
No Problems with the adapter and the same Firmware on the Bridge in my configuration

**Comment by a-i-ks** [comment]
Thanks for your answer @Baenker . I will try to reset my hue bridge to default settings and then try to connect the adapter with the bridge again. Maybe this will solve my problems.  I'll keep you updated. 
**Update: Resetting the bridge solved the problem. Maybe the api user was blocked because of too many requests.**
