### ISSUE TITLE
Enhancement to read also iConnectHue Animations 

### ISSUE THREAD

**Issue by noaboa97** [iobroker-community-adapters/ioBroker.hue#52]
Hi, 
So to have nice animations I use iConnectHue Animations which are also written on the Hue Bridge and also run on the bridge. So a neat little feature would be that the hue adapter also reads those animations and so I could create scripts to turn on the animation autmatic. 
Also in general it would be nice if there would be the feature to read the normal scenes and activate them.

Thanks

**Comment by foxriver76** [comment]
Related to https://github.com/iobroker-community-adapters/ioBroker.hue/issues/39

**Comment by foxriver76** [comment]
You could try if they are synced now with https://github.com/iobroker-community-adapters/ioBroker.hue/commit/a175313f3db89ac60eeab04f21d123d496b84c8f 
Unfortunately there is no free version of the app so I can`t try

**Comment by foxriver76** [comment]
If it's not working, please reopen.
