### ISSUE TITLE
Helligkeitswerte für Zonen und Räume werden nicht aktualisiert

### ISSUE THREAD

**Issue by micw421** [iobroker-community-adapters/ioBroker.hue#523]
Wenn ich z.B. über die App für eine Zone oder einen Raum die Helligkeit verändere, wird diese nicht am Datenpunkt eingetragen, obwohl die API eine entsprechende Nachricht sendet:

New push connection update: {"dimming":{"brightness":52.17},"id":"f306e655-aa3e-4bcd-84cd-6b50afdf144f","id_v1":"/groups/5","owner":{"rid":"cc96efda-2664-45d5-830b-56542919eb1e","rtype":"room"},"type":"grouped_light"}

New push connection update: {"dimming":{"brightness":54.15},"id":"f4a4de82-f33f-48a9-972e-918996a45735","id_v1":"/groups/4","owner":{"rid":"9e87647f-afa2-43c3-a552-7da4f35cd87f","rtype":"zone"},"type":"grouped_light"}

 - Adapter version: 3.10.1

**Comment by micw421** [comment]
Ich habe nun in handleGroupUpdate folgendes ergänzt:

        if (update.dimming) {
            await this.setStateAsync(`${channelName}.level`, Math.round(update.dimming.brightness), true);
            await this.setStateAsync(
                `${channelName}.bri`,
                hueHelper.levelToBrightness(update.dimming.brightness),
                true
            );
        }

Damit funktioniert es wie gewünscht.
Bitte bei Gelegenheit übernehmen ...

**Comment by leopard3330** [comment]
Wo kan ich es anderen in IO?

**Comment by micw421** [comment]
Ich habe es direkt in .../iobroker.hue/build/main.js geändert.
Mir ist auch vollkommen unklar, warum dieser offensichtliche Bug nicht längst offiziell behoben wurde.

**Comment by mcm1957** [comment]
@micw421 
Zunächst einm ein herzliches DANKE dass du das Problem analysiert und einen Fix gefunden hat.

Allerdings löst deine Aussage

> Mir ist auch vollkommen unklar, warum dieser offensichtliche Bug nicht längst offiziell behoben wurde.

auch ein wenig Ärger aus. Sorry.

Wie du (hoffentlich) weißt wird ioBroker von unbezahlt tätigen Freiwilligen entwickelt die hier ihre Zeit und ihr Wissen einbringen. (Ich habe finanziell noch keinen Euro gesehen - aber ein Danke von Zeit zu Zeit reicht mir auch und es gibt genug User denen das bewußt ist.) Wenn du schreibt dir ist nicht klar warum das nicht längst behoben ist, dann kann ich nur antworten 'weil dafür noch niemand Zeit hatte' und 'weil du auch (noch ?) nicht mitarbeitest'. Ich investiere jeden Tag Stunden in ioBroker damit ihr das gratis benutzen könnt - aber mehr als 10 Adapter kann niemand ernsthaft betreuen und alleine im Community Bereich exsitieren über 150 Adapter. Außerdem besitze ich kein Hue Equipment und kann daher auch nichts ändern / testen.

**Und damit ich auch was konstruktives sage:
Bitte erstell doch eine PR im Adapterrepository (https://github.com/iobroker-community-adapters/ioBroker.hue) mit den notwendigen Änderungen.** Ich od. Foxriver76 werden diesen sicher zeitnahe ansehen / mergen. Die Anpassungen im Sourcecode (TS, src Verzeichnis) reichen, Releasenotes und Versionsanpassung kann ich im Zuge der Releaseerstellung erledigen.

**Comment by micw421** [comment]
Hallo mcm1957,

sorry, wenn das etwas blöd rüberkam.
Aber ich habe mich schon etwas gewundert, dass in ca. 5 Monaten andere Sachen eingebaut wurden, anstatt diesen Bug zu beheben.
Ich bin selbst Entwickler und arbeite gerne mit, so dass ich mal einen PR erstellen werde.

Viele Grüße!

**Comment by Baenker** [comment]
Hallo @micw421 hattest Du das PR erstellst? Ich kann es nicht finden? Habe es aber vielleicht übersehen…

**Comment by micw421** [comment]
Leider noch nicht geschafft ...

**Comment by Baenker** [comment]
Ich habe immer noch großes Interesse an dieser Lösung. @micw421 Könntest Du evtl ein paar Minuten opfern und den PR erstellen

**Comment by micw421** [comment]
Hallo @Baenker,
ich müsste mich erstmal in die Thematik PR einarbeiten, schaffe das in nächster Zeit zeitlich nicht. Sonst gerne selbst den PR erstellen.
Ansonsten kannst du es einfach direkt im Quellcode ändern, s.o.
Muss halt nach jedem Update gemacht werden, aber so oft passiert das ja nicht ...

**Comment by mcm1957** [comment]
> Ich habe nun in handleGroupUpdate folgendes ergänzt:
> 
> ```
>     if (update.dimming) {
>         await this.setStateAsync(`${channelName}.level`, Math.round(update.dimming.brightness), true);
>         await this.setStateAsync(
>             `${channelName}.bri`,
>             hueHelper.levelToBrightness(update.dimming.brightness),
>             true
>         );
>     }
> ```
> 
> Damit funktioniert es wie gewünscht. Bitte bei Gelegenheit übernehmen ...

@foxriver76 
Da von micw421leider kein PR zu kommen scheint, kannst du das ev. mal anschaun und einschieben...

**Comment by foxriver76** [comment]
done with 3.12.0
