### ISSUE TITLE
Error "Cannot get result for lightStatus* - Error: socket hang up"

### ISSUE THREAD

**Issue by Karkas66** [iobroker-community-adapters/ioBroker.hue#57]
Hi Folks,

I updated my Hue Bridge (Hardware revision v2) to the latest Firmware version 1811120916. It almost broke my entire setup. I´ve got 10 Rooms with about 20 Devices of all kind. Tons of custom Java Script implementations that all worked for Month without touching it.

Since the update iobroker throws the following Messages whenever it Polls the Bridge (every 30 second):

  
`hue.0 | 2019-02-04 19:03:25.540 | error | Cannot get result for lightStatus13
hue.0 | 2019-02-04 19:03:25.539 | error | Error: socket hang up
hue.0 | 2019-02-04 19:03:25.480 | error | Cannot get result for lightStatus12
hue.0 | 2019-02-04 19:03:25.479 | error | Error: socket hang up
hue.0 | 2019-02-04 19:03:25.421 | error | Cannot get result for lightStatus11
hue.0 | 2019-02-04 19:03:25.420 | error | Error: socket hang up
hue.0 | 2019-02-04 19:03:25.361 | error | Cannot get result for lightStatus10
hue.0 | 2019-02-04 19:03:25.360 | error | Error: socket hang up
hue.0 | 2019-02-04 19:03:25.301 | error | Cannot get result for lightStatus9
hue.0 | 2019-02-04 19:03:25.300 | error | Error: socket hang up
hue.0 | 2019-02-04 19:03:25.242 | error | Cannot get result for lightStatus8
hue.0 | 2019-02-04 19:03:25.241 | error | Error: socket hang up
hue.0 | 2019-02-04 19:03:25.182 | error | Cannot get result for lightStatus7
hue.0 | 2019-02-04 19:03:25.181 | error | Error: socket hang up
hue.0 | 2019-02-04 19:03:25.122 | error | Cannot get result for lightStatus6
hue.0 | 2019-02-04 19:03:25.121 | error | Error: socket hang up
hue.0 | 2019-02-04 19:03:25.063 | error | Cannot get result for lightStatus5
hue.0 | 2019-02-04 19:03:25.062 | error | Error: socket hang up
hue.0 | 2019-02-04 19:03:24.993 | error | Cannot get result for lightStatus4
hue.0 | 2019-02-04 19:03:24.990 | error | Error: socket hang up
hue.0 | 2019-02-04 19:03:24.934 | error | Cannot get result for lightStatus3
hue.0 | 2019-02-04 19:03:24.932 | error | Error: socket hang up
hue.0 | 2019-02-04 19:03:24.875 | error | Cannot get result for lightStatus1
hue.0 | 2019-02-04 19:03:24.872 | error | Error: socket hang up
hue.0 | 2019-02-04 19:03:24.814 | error | Cannot get result for lightStatus19
hue.0 | 2019-02-04 19:03:24.813 | error | Error: socket hang up
hue.0 | 2019-02-04 19:03:24.755 | error | Cannot get result for lightStatus18
hue.0 | 2019-02-04 19:03:24.754 | error | Error: socket hang up
hue.0 | 2019-02-04 19:03:24.696 | error | Cannot get result for lightStatus17
hue.0 | 2019-02-04 19:03:24.695 | error | Error: socket hang up
hue.0 | 2019-02-04 19:03:24.636 | error | Cannot get result for lightStatus15
hue.0 | 2019-02-04 19:03:24.635 | error | Error: socket hang up
hue.0 | 2019-02-04 19:03:24.576 | error | Cannot get result for lightStatus14
hue.0 | 2019-02-04 19:03:24.575 | error | Error: socket hang up
hue.0 | 2019-02-04 19:03:24.516 | error | Cannot get result for lightStatus13
hue.0 | 2019-02-04 19:03:24.515 | error | Error: socket hang up
hue.0 | 2019-02-04 19:03:24.448 | error | Cannot get result for lightStatus12
hue.0 | 2019-02-04 19:03:24.446 | error | Error: socket hang up
hue.0 | 2019-02-04 19:03:24.390 | error | Cannot get result for lightStatus11
hue.0 | 2019-02-04 19:03:24.388 | error | Error: socket hang up
`

It sometimes works and i see something like this:
`
hue.0 | 2019-02-04 18:51:40.275 | error | error: Error: socket hang up
hue.0 | 2019-02-04 18:51:40.268 | info | final lightState for Philips_hue.Buero:{"bri":0,"on":false,"level":0}
`
But that is very rare.

I was on Version 0.6.9 when I did the update. I tried 1.1.2 as a workaround, which did not work and I went back to 0.6.9

Any ideas?

**Comment by noaboa97** [comment]
I have the same problem since the update... I guess philips hue changed something in their hue api or so.

**Comment by Baenker** [comment]
No Problems here. I saw the  error only one time after the update.

**Comment by Karkas66** [comment]
I still have the Problem... does no one have any idea?

**Comment by PietPinguin** [comment]
Same problem after firmware update Hue Bridge and active polling
