### ISSUE TITLE
hue/ct broken?

### ISSUE THREAD

**Issue by DanielWeeber** [iobroker-community-adapters/ioBroker.hue#61]
I am unable to set the color or color temperature via hue/ct
Even If I type in any correct number (I know that this has changed since 0.6.9) the color either does not change or changes to the wrong color. A second after I typed in a valid number a way different number is replaced for that, which is out of range.

**Comment by Spampunk** [comment]
With version 1.2.3 there is a mismatch of the ct values. You have to type (or set) the color temperature in degrees Kelvin (e.g. 3000). And in return the value at this dp is set between 156 and 500. This is a quite strange behaviour as it does not give me the ability to visualize the correct value. It's even worse as a high value in Kelvin responds to a small value in return and vice versa.

Any idea how to fix this?

**Comment by foxriver76** [comment]
PR #66 should fix this.

**Comment by foxriver76** [comment]
fixed with https://github.com/iobroker-community-adapters/ioBroker.hue/commit/68ca3b7edae4dd3438be9f5ff119e90fb34908ca and https://github.com/iobroker-community-adapters/ioBroker.hue/commit/29ec18b1f1ffbc45dceead9704f7d60eee090442
