### ISSUE TITLE
Dimmer Switch Objekte werden spät, bis gar nicht aktualisiert

### ISSUE THREAD

**Issue by senger1985** [iobroker-community-adapters/ioBroker.hue#63]
Ich habe den Dimmer/Switch von Hue an die Bridge angelernt und dieser wird auch im ioBroker erkannt.

Nur werden die Daten eher sporadisch übertragen und dann noch bei der selben Taste verschiedene Werte übermittelt.

Beispiel: Bei dem oberen Button kommen dann Zahlen, wie 1001, 1002 etc.
Bei dem zweiten Button kommen dann Zahlen, wie 2001, 2003 etc.

**Comment by arteck** [comment]
die werden nicht sporadisch sondern so wie das polling Interval eingestellt ist aktualisiert

ausserdem werden nicht nur "drücken" sondern auch "gedrückthalten" übertragen..
