### ISSUE TITLE
Can't add instance (can't accept Apache Licence, button stays greyed out)

### ISSUE THREAD

**Issue by JoergGiencke** [iobroker-community-adapters/ioBroker.hue#630]
There's no way to click the Accept button it stays greyed out no matter what I do. Thus there's no way to create an intance of the adapter.

<img width="535" alt="image" src="https://github.com/user-attachments/assets/f50f186f-ca97-4c15-b128-f8cb7525f2e2">

**Comment by JoergGiencke** [comment]
If one opens Edge's developer mode (F12, just that, nothing else) the button becomes accessible.
That 'solved' the problem for me, but of course it's not a solution.

**Comment by mcm1957** [comment]
@JoergGiencke 
Please add version information for EVERY issue

adapter
admin
js-controller
node
O/S

**Comment by JoergGiencke** [comment]
adapter 3.12.0
admin 7.0.22
js-controller 6.0.9
node 18.20.4
O/S Ubuntu 20.04.6 LTS (GNU/Linux 5.4.0-190-generic x86_64)

**Comment by foxriver76** [comment]
This is an Admin issue

**Comment by mcm1957** [comment]
see https://github.com/iobroker-community-adapters/ioBroker.hue/issues/630
Will be processed with this issue.
