### ISSUE TITLE
device not updating status

### ISSUE THREAD

**Issue by noaboa97** [iobroker-community-adapters/ioBroker.hue#64]
Hello,

I have a Gledopto Zigbee Controller connected to the Hue Bridge. It works very well with the Hue Bridge the only thing I noticed, that when I turn on the Zigbee Controller via the Hue app the state in ioBroker won't update itself what is kind of strange because with the normal hue bulb it works. 
When I set the state in ioBroker to "true" or "false" it will turn on or off. 
But it just won't update if the state changes on the hue bridge. 

Anyone else experiencing this problem? or has a solution?

I tried setting the polling interval to 1 second but that didn't help.

best Noah

**Comment by foxriver76** [comment]
If you turn the device on without hue app, does the Hue app shows the state correctly? Otherwise, (thats what I guess) Hue does not know the state, hence ioBroker also doesn't get the state.
