### ISSUE TITLE
Warnmeldungen

### ISSUE THREAD

**Issue by DrBakterius** [iobroker-community-adapters/ioBroker.hue#67]
Ab Version größer 0.6.9 werden in unregelmässigen Abständen Warnungen ausgegeben weil ein Teilnehmer den Befehl nicht bestätigt und der Befehl wiederholt gesendet wird.

z.B.:

> 2019-07-20 08:50:10.316 - warn: hue.0 lightQueue: job lightStatus:14:0e39df67ad37d4ca5fa0cdeccab6cc33 failed: Error: read ECONNRESET
> 
> 2019-07-20 08:50:10.321 - warn: hue.0 lightQueue: retry [1/10] job lightStatus:14:0e39df67ad37d4ca5fa0cdeccab6cc33
> 
> 2019-07-20 08:50:10.338 - warn: hue.0 lightQueue: job lightStatus:15:bc9348bef04b2fbbcdd2baab936528a7 failed: Error: Request failed with status code 500
> 
> 2019-07-20 08:50:10.339 - warn: hue.0 lightQueue: retry [1/10] job lightStatus:15:bc9348bef04b2fbbcdd2baab936528a7
> 
> 2019-07-20 08:50:10.386 - warn: hue.0 lightQueue: job lightStatus:17:39331db62eab84f6453ca2954b34c464 failed: Error: Request failed with status code 500
> 
> 2019-07-20 08:50:10.387 - warn: hue.0 lightQueue: retry [1/10] job lightStatus:17:39331db62eab84f6453ca2954b34c464

Kann man die Warnmeldung erst ausgeben wenn eine gewisse Anzahl an Wiederholungen fehlgeschlagen ist?

**Comment by Apollon77** [comment]
Bitte 1.2 von latest nutzen, bzw kommt vorauss. heute eh in Stable. Wenn Problem dann noch da ist bitte nochmals mit aktualisiertem Log melden

**Comment by DrBakterius** [comment]
Es ist die v1.2.3 installiert!

**Comment by bergjet** [comment]
Habe mit v1.2.3 auch diese Meldungen
