### ISSUE TITLE
Error MSGs after Update to 1.2.3

### ISSUE THREAD

**Issue by t1m02k16** [iobroker-community-adapters/ioBroker.hue#68]
Afte the update to Version 1.2.3 i alway get error Messages:

![image](https://user-images.githubusercontent.com/19432480/61795195-25a26980-ae23-11e9-8d88-3ca9232a526a.png)

**Comment by Apollon77** [comment]
@jens-maus ?! Any idea?

**Comment by jens-maus** [comment]
Looks like the bridge is blocking requests?!? That's why ECONNRESET. I would siggest to reset it and check that there are not two hue adapters running at the same time...

**Comment by t1m02k16** [comment]
I do not have two hue adapters running. do you think restart the bridge or what do you mean by restarting

**Comment by t1m02k16** [comment]
![image](https://user-images.githubusercontent.com/19432480/61879020-7208aa80-aef2-11e9-8d92-b336e6ad9d33.png)

**Comment by hetti72** [comment]
I have the same issue since i updated my HUE Bridge to SW Version 1933087030. As a Workaround i checked the "ignore Groups" Option in the Adapter config, then erverything works as expected. But i need the Groups for some Automation Scripts. 
Has nowbody else this Problem?

**Comment by 7oku** [comment]
I've got the same issue as well. It is reproducable!

That are devices (bulbs) which are not reachable from the bridge (because the switch is off and has cut the power to the bulb). The bridge just slaps away iobroker then, which generates 30-40 log entries within 1-2 secs, because of all the retries. 

IMHO there needs to be found some other way to manage that kind of "state", but have to admit the hue bridge is not very "nice" in responding here in a meaningful way.

**Comment by hetti72** [comment]
Hi,

> That are devices (bulbs) which are not reachable from the bridge (because the switch is off and has cut the power to the bulb). 

I have no turned off (powerless) bulbs in my installation. And in my case the problem seems to be related to the Groups, because when i disable Group polling within the Adapter everything Works. And the whole System worked flawless before i upgraded the Bridge to SW Version 1933087030

**Comment by foxriver76** [comment]
The spam by the logging is really intense. IMHO we should only log a warning/error when all retries have failed.

**Comment by foxriver76** [comment]
Requests are now reduced massively by https://github.com/iobroker-community-adapters/ioBroker.hue/commit/d78b775ba51bbc3e34aa885a52c220f052784e51 
Hence, the load on the bridge and queue is reduced. Please try if this fixes the issue.
