### ISSUE TITLE
Version 2.0.0 Datenpunkte aktualisieren sich nicht

### ISSUE THREAD

**Issue by Spampunk** [iobroker-community-adapters/ioBroker.hue#71]
Steuere ich die Bridge nicht über ioBroker, z.B. per App, werden die Stati nicht in ioBroker aktualisiert.

**Comment by foxriver76** [comment]
Danke fürs testen. Entsprechend der Release Notes hat sich die State Struktur geändert. Schaust du auch auf die richtigen DP's? 

Der Adapter Namespace repräsentiert nun die Bridge, sprich statt `hue.X.<bridge_name>.<lightname>.on` nun `hue.X.<lightname>.on`.

**Comment by Spampunk** [comment]
Ich habe die DPs zuvor gelöscht. Die DPs entsprechen also dem neuen Namespace.

**Comment by foxriver76** [comment]
Und es wird gar nichts (Gruppen, Lichter, Sensoren) aktualisiert? Wann hast du von GitHub installiert? Kann das bei mir nicht bestätigen.

**Comment by Spampunk** [comment]
Sensoren habe ich leider nicht. Die Leuchte selbst wird aktualisiert, jedoch die Gruppe nicht.
Ich habe heute gegen 10 Uhr die Version 2.0.0 von GutHub installiert.

**Comment by foxriver76** [comment]
Werden bei mir auch gesynced. Kannst du mal bitte sicherstellen, dass du wirklich den aktuellen Stand hast. Hatte ja heute früh noch 1-2 Commits gepushed. Einfach nochmal von GitHub installieren und ganz wichtig 'Upload des Adapters'.

**Comment by Spampunk** [comment]
Adapter neu installiert. Nun werden alle DPs auch gesynct, außer "on". Selbst, wenn ich den DP selbst auf "false" setze (in den ioBroker Objekten), geht die Gruppe zwar aus, aber es bleibt "true" in roter Schrift stehen.

**Comment by Spampunk** [comment]
Update: ich habe den DP "on" noch einmal gelöscht und dann den Adapter neu gestartet. Jetzt funktioniert alles wie gewünscht.

Vielen Dank, Max!

Übrigens eine tolle Sache, nun auch die Szenen kontrollieren zu können - prima Arbeit!

Noch eine Sache, die mir aufgefallen ist: Die Farbtemperatur wird je nach Zugang (iobroker/App) anders dargestellt. Mit der App geht der maximale Wert Kelvin auch auf 6536° K, gebe ich ihn händisch ein, wird maximal 6494° K dargestellt.

**Comment by foxriver76** [comment]
Top. Ich schaue das mit den Kelvin mal an, evtl hat Bluefox da was limitiert.
