### ISSUE TITLE
Room ON true false geht irgendwie nicht

### ISSUE THREAD

**Issue by Floppz** [iobroker-community-adapters/ioBroker.hue#74]
Is there any possibility to switch rooms on or off again?!?
I can light it up with the presetbuttons. But i cant use the ON - true/false for the room to switch it off.

**Comment by Floppz** [comment]
Warum stammel ich mir hier auf Englisch einen ab :)
Also ganz einfach - seit dem 2.0 finde ich keine Möglichkeit mehr alle Lampen eines Raumes auszuschalten. 
Vorher konnte ich einfach den Wert "ON" auf false setzen und alle Lampen gingen aus. Jetzt muss ich jede einzelne Lampe ausschalten.
Allg. kann ich bei den Räumen nur sehen, was gerade bei den Lampen eingestellt ist, aber nix verändern. 

Kleines Feedback und Dank an den Developer
Das 3. Sek. Polling macht keine Probleme, bin momentan bei 26 Lampen auf Bridge 1 und 37 Lampen auf Bridge 2. Läuft traumhaft.

**Comment by foxriver76** [comment]
Kannst du mal checken welche Version von node-Hue-api drauf ist, glaube größer 3 macht Probleme.

**Comment by Floppz** [comment]
Kann ich checken - nur wo :)

**Comment by foxriver76** [comment]
Linux? `cat /opt/iobroker/node_modules/iobroker.hue/node_modules/node-hue-api/package.json | grep version`

Hast du von GitHub installiert oder klassisch?

**Comment by Floppz** [comment]
Über Github installiert, klassisch krieg ich 2.0 nicht angezeigt
Api Version ist 3.2.1

**Comment by foxriver76** [comment]
Dann installier nochmal von GitHub bitte + Upload . Mir ist es nämlich heute morgen aufgefallen und habe dann die dep wieder auf 2.6.4 runter.

**Comment by foxriver76** [comment]
Ja 2.0 wird nur in latest angezeigt nicht stable

**Comment by Floppz** [comment]
wie dep ich runter?!? Ich weiß ich bin n Noob :)

**Comment by foxriver76** [comment]
Einfach nochmal von GitHub installieren

**Comment by foxriver76** [comment]
Den Adapter. Das mit der Dep wird dann automatisch gefixt

**Comment by Floppz** [comment]
JA GEIL! Geht wieder.
So, dann kann ich jetzt mal alle Datenpunkte in den Skripts neu verknüpfen :)
Danke für die schnelle Hilfe!

**Comment by foxriver76** [comment]
Gerne.

**Comment by Floppz** [comment]
soll ich zumachen?!?

**Comment by Floppz** [comment]
ach hast schon ^^

**Comment by foxriver76** [comment]
Der Vollständigkeit halber: Der aktuelle GitHub Stand läuft nun mit der node-hue-api v3. Allerdings läuft vieles bislang nur über die vorübergehende Abwärtskompatibilität, siehe https://github.com/peter-murray/node-hue-api#2x-backwards-compatibility-shim
