### ISSUE TITLE
Version 2 of the adapter does not work with ha-bridge anymore

### ISSUE THREAD

**Issue by cernst1980** [iobroker-community-adapters/ioBroker.hue#78]
I´m using ha-bridge https://github.com/bwssytems/ha-bridge with ioBroker for a long time now to control 433 MHz devices.
Since upgrade to version 2 of the adapter, it does not work anymore.
HA-Bridge and devices are not discovered, no error messages in the logs.

**Comment by foxriver76** [comment]
V2.0.0?

**Comment by foxriver76** [comment]
V >= v2.1.0 is using the node-hue-api in version 3 I guess the error lies somewhere there. Maybe the adapter logs an error after stoppage? Because uncaught rejected promises are logged at stoppage.

**Comment by cernst1980** [comment]
Currently, i´m using V2.2.1.
Nothing is logged by the adapter beside start and stop messages.
It seems, that the adapter tries to connect to port 443 https, although port 80 is configured. ha-bridge is only listening on port 80.

**Comment by foxriver76** [comment]
Thanks I will look into this. Until then you should try 2.0.0

**Comment by foxriver76** [comment]
Port is now configurable again, but it seems like that currently https is forced by node-hue-api 

https://github.com/peter-murray/node-hue-api/issues/142

**Comment by foxriver76** [comment]
Please test 2.2.3

**Comment by cernst1980** [comment]
It´s working again, thank you for your work!
