### ISSUE TITLE
Hue Bridge 1.0 wird nicht erkannt

### ISSUE THREAD

**Issue by guergen1** [iobroker-community-adapters/ioBroker.hue#79]
Hallo, die letzte funktionierende Version für die runde Hue-Bridge ist die 2.0.0
Danach wird die Bridge nicht mehr erkannt

**Comment by foxriver76** [comment]
Vermutlich lag es daran, dass immer der Port 443 angezogen wurde. Nun wird wieder wie gehabt der Port aus den Adaptereinstellungen (default: 80) angezogen. Bislang nur auf Github gefixt.

**Comment by foxriver76** [comment]
Bitte 2.2.3 testen

**Comment by guergen1** [comment]
Ist der Adapter im npm schon auf 2.2.3 hochgezogen? Ich bekomme noch 2.2.2 mim Broker angezeigt

**Comment by guergen1** [comment]
Läuft!
