### ISSUE TITLE
Adapter lässt sich nicht auf 2.3.0 updaten

### ISSUE THREAD

**Issue by guergen1** [iobroker-community-adapters/ioBroker.hue#81]
Folgende Meldung kommt: 
![grafik](https://user-images.githubusercontent.com/34395245/67703328-8a85d680-f9b3-11e9-950d-787d80305c79.png)

Danach ist der Adapter immer noch auf der alten Version!
Hier das log dazu:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'iobroker.hue@2.3.0',
1 verbose cli   '--loglevel',
1 verbose cli   'error',
1 verbose cli   '--production',
1 verbose cli   '--save',
1 verbose cli   '--prefix',
1 verbose cli   '/opt/iobroker' ]
2 info using npm@6.11.3
3 info using node@v10.17.0
4 verbose npm-session bb4db6ea51f18359
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/iobroker.hue 199ms (from cache)
8 silly registry:manifest no matching version for iobroker.hue@2.3.0 in the cache. Forcing revalidation.
9 http fetch GET 200 https://registry.npmjs.org/iobroker.hue 76ms
10 silly fetchPackageMetaData error for iobroker.hue@2.3.0 No matching version found for iobroker.hue@2.3.0.
11 timing stage:rollbackFailedOptional Completed in 1ms
12 timing stage:runTopLevelLifecycles Completed in 3031ms
13 verbose type version
14 verbose stack iobroker.hue: No matching version found for iobroker.hue@2.3.0.
14 verbose stack     at pickManifest (/usr/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:122:13)
14 verbose stack     at fetchPackument.then.packument (/usr/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:43:18)
14 verbose stack     at tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
14 verbose stack     at Promise._settlePromiseFromHandler (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:517:31)
14 verbose stack     at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:574:18)
14 verbose stack     at Promise._settlePromise0 (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:619:10)
14 verbose stack     at Promise._settlePromises (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:699:18)
14 verbose stack     at _drainQueueStep (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
14 verbose stack     at _drainQueue (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:131:9)
14 verbose stack     at Async._drainQueues (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:147:5)
14 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
14 verbose stack     at runCallback (timers.js:705:18)
14 verbose stack     at tryOnImmediate (timers.js:676:5)
14 verbose stack     at processImmediate (timers.js:658:5)
15 verbose cwd /
16 verbose Linux 5.0.0-29-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "iobroker.hue@2.3.0" "--loglevel" "error" "--production" "--save" "--prefix" "/opt/iobroker"
18 verbose node v10.17.0
19 verbose npm  v6.11.3
20 error code ETARGET
21 error notarget No matching version found for iobroker.hue@2.3.0.
22 error notarget In most cases you or one of your dependencies are requesting
22 error notarget a package version that doesn't exist.
23 verbose exit [ 1, true ]

**Comment by Apollon77** [comment]
2.3.0 seems not on npm

**Comment by foxriver76** [comment]
Um die Hue Version 2.3.0 ranken sich viele Mythen, viele behaupten sie gesehen zu haben, doch keiner hat sie je installieren können.

Entsprechend meinem Forum Post (https://forum.iobroker.net/topic/26098/test-adapter-hue-v2-2-x/84) und der dort verlinkten Konversation mit @jens-maus wurde die Version zurückgenommen.
