### ISSUE TITLE
2.2.3 Status von Innr Lichtern wird richtig dargestellt, nehmen aber keine Werte an 

### ISSUE THREAD

**Issue by Speedbreaker12** [iobroker-community-adapters/ioBroker.hue#82]
Hallo Zusammen,
wie schon im Titel, ich habe einige Innr Lichter an der Hue Bridge, über die Hue App und Alexa lassen sie sich ohne Probleme steuern. Der Hue Adapter aktualisiert die Werte der Lichter zwar richtig, es kann aber manuell nicht geändert werden! Schalte ich z.B. On auf True, wird der Wert rot und springt wieder zurück auf false.

Ich bin für jede hilfe dankbar.
![Huerrror](https://user-images.githubusercontent.com/18654629/67977617-be156a80-fc18-11e9-9e5f-d18a62df8175.JPG)

**Comment by foxriver76** [comment]
Kannst du mir mal bitte ein Screenshot von dem Licht im Objekte Tab zeigen.

**Comment by foxriver76** [comment]
Und noch einen wenn du im Objekte Tree, hinter dem Channel für die Lampe auf den 'Bearbeiten' Stift drückst. Dann den Tab `nativ`, z. B.

![Bildschirmfoto von 2019-11-01 12-16-45](https://user-images.githubusercontent.com/25484431/68021392-8e5e7500-fca1-11e9-87bb-dc4057c7d63a.png)

**Comment by hoaloha** [comment]
Hallo,
ich habe diese Meldung auch, allerdings ohne Innr Lampen. Nutze Hue Lampen+Iris und Osram plugs. Taucht bei mir beim schalten einer Osram Steckdose auf. Es wird alles ordentlich geschaltet, aber der Fehler ist im Log. Lässt sich manuell reproduzieren.

<img width="1135" alt="hue_fehler" src="https://user-images.githubusercontent.com/47867028/68052880-ee2d3e00-fcea-11e9-8c3e-f98c139158f1.png">

**Comment by hoaloha** [comment]
Ergänzung: Die Steckdose zeigt in der Hue App nicht erreichbar an, was sie aber ist. Vom Strom nehmen ändert an "nicht erreichbar" nur kurzfristig etwas.
