### ISSUE TITLE
OSRAM Plugs funktionieren seit Version 1.2x nicht mehr

### ISSUE THREAD

**Issue by gitknd** [iobroker-community-adapters/ioBroker.hue#83]
Ich habe an der Bridge 2.0 Osram Plugs laufen (native Hue Geräte jedoch nicht). Bis 1.2.x ging alles einwandfrei. Seit Version 2.x lassen sich die Plugs nicht mehr über ioBroker schalten. Im iobroker Log kommt minütlich:

host.iobroker | 2019-11-09 12:46:17.417 | info | Restart adapter system.adapter.hue.0 because enabled
-- | -- | -- | --
host.iobroker | 2019-11-09 12:46:17.417 | error | instance system.adapter.hue.0 terminated with code 1 ()
host.iobroker | 2019-11-09 12:46:17.417 | error | Caught by controller[0]: at startup (bootstrap_node.js:160:9)
host.iobroker | 2019-11-09 12:46:17.416 | error | Caught by controller[0]: at run (bootstrap_node.js:394:7)
host.iobroker | 2019-11-09 12:46:17.416 | error | Caught by controller[0]: at Module.runMain (module.js:611:10)
host.iobroker | 2019-11-09 12:46:17.416 | error | Caught by controller[0]: at Function.Module._load (module.js:445:3)
host.iobroker | 2019-11-09 12:46:17.416 | error | Caught by controller[0]: at tryModuleLoad (module.js:453:12)
host.iobroker | 2019-11-09 12:46:17.415 | error | Caught by controller[0]: at Module.load (module.js:494:32)
host.iobroker | 2019-11-09 12:46:17.415 | error | Caught by controller[0]: at Object.Module._extensions..js (module.js:586:10)
host.iobroker | 2019-11-09 12:46:17.415 | error | Caught by controller[0]: at Module._compile (module.js:549:28)
host.iobroker | 2019-11-09 12:46:17.415 | error | Caught by controller[0]: at Object.runInThisContext (vm.js:97:10)
host.iobroker | 2019-11-09 12:46:17.414 | error | Caught by controller[0]: at createScript (vm.js:56:10)
host.iobroker | 2019-11-09 12:46:17.414 | error | Caught by controller[0]: SyntaxError: Unexpected token (
host.iobroker | 2019-11-09 12:46:17.414 | error | Caught by controller[0]: ^
host.iobroker | 2019-11-09 12:46:17.413 | error | Caught by controller[0]: stateChange: async (id, state) => {
host.iobroker | 2019-11-09 12:46:17.412 | error | Caught by controller[0]: /opt/iobroker/node_modules/iobroker.hue/main.js:38
host.iobroker | 2019-11-09 12:46:17.086 | info | instance system.adapter.hue.0 started with pid 29992

**Comment by foxriver76** [comment]
Bitte mindestens node version 8 installieren
