### ISSUE TITLE
Stop Entertainment Modus (TV Color Sync)

### ISSUE THREAD

**Issue by wizzardking** [iobroker-community-adapters/ioBroker.hue#84]
Thank you for the great work on this Adapter.
I just have one feature request.

When Entertainment Modus is enabled (Hue Lamps will Sync color with the TV Picture), the Entertainment Modus will not be disabled automaticly after I shut down the TV and the Android Box where the HUE Sync is installed on.
So, I have to open the HUE App on my mobile phone to disable the HUE Entertainment Modus, before this Adapter can manage those Lamps again.

So, it would be realy nice if there is a way to stop the entertainment modus also directly from inside this adapter.

**Comment by foxriver76** [comment]
Implemented in 2.4.0
