### ISSUE TITLE
Stoppage of entertainment mode not working

### ISSUE THREAD

**Issue by wizzardking** [iobroker-community-adapters/ioBroker.hue#85]
Thank you very much for your fast reaction on the previous task https://github.com/iobroker-community-adapters/ioBroker.hue/issues/84

Because this task is allready closed, I open a new one.
I updated to the newest version this morning with git, and it will find now the Entertainment Areas.

The Strange thing is, it now has a folder inside the HUE Adapter called "Philips hue.Entertainment" and also one called "Philips hue.TV" (TV is the Name of my Entertainment Area).
So, basicly it added the same thing twice.

The other problem I have with it is, that it's still not possible for me to disable the Ambilight synchronisation.
If I switch the on status to false, it outputs the following error in the log and status still remaining true.
groupQueue: job groups.setGroupState:undefined:54ec10399cacd34164392f8c7ac69398 max retry reached: TypeError: Cannot read property 'groups' of undefined

And maybe this is just a layout thning, but all other folders inside the HUE Adapter called "Philips_hue.Hue_Lightname". The entertainment Areas starting with "Philips hue..." (a space instead of an underline)

**Comment by wizzardking** [comment]
I also made now a test with a HUE Lightstrip synced by the HUE App on the PC.
It didn't output an error there when I switch it in ioBroker to false (off), but sync will also still remaining on there, So, there isn't anything I could change in the Entertainment Areas in ioBroker.

**Comment by foxriver76** [comment]
Have you done an upload of the adapter after updating via git?

**Comment by foxriver76** [comment]
okay, according to your descirption it seems more likely to be an issue with the id.

**Comment by foxriver76** [comment]
Can you please provide a screenshot of the objects to avoid misunderstandings

**Comment by wizzardking** [comment]
Hi foxriver

Sure. BTW, do you speak german? would make it more easy to communicate. ;)

Screenshot of Group TV2 (is an entertainment group):
http://prntscr.com/pwfmk5

And here one of the other Entertainment Groups:
http://prntscr.com/pwfndo

I am able to change settings in the TV2 group (like put lamps in this group on and off) as long the lamps aren't synced. But as soon the lamps are synced, it will output the error aboth

**Comment by foxriver76** [comment]
`Entertainment` scheint ein Raum zu sein. Kannst du mal die Struktur soweit zugeklappt zeigen, dass man sieht was er da für eine Id ohne `_` angelegt hat.

**Comment by foxriver76** [comment]
> I am able to change settings in the TV2 group (like put lamps in this group on and off) as long the lamps aren't synced. But as soon the lamps are synced, it will output the error aboth

Kannst du nur einzelne Lampen schalten oder kannst du auch den `on` State von TV2 schalten zum aktivieren/deaktivieren?

**Comment by wizzardking** [comment]
Wegen Entertainment: Dan werden diese vermutlich noch von den ersten Versuchen sein. Der Entertainment Raum ist in der HUE App nicht mehr ersichtlich.

Mit ID ohne _ habe ich dies vermutlich nicht klar formuliert. Ich meine eigentlich nur den generierten Namen damit: http://prntscr.com/pwgayu

Ich kann bei TV2 auch den On Status problemlos wechseln und die Lampen reagieren auch darauf. Lediglich wenn die HUE Bridge noch meint, dass diese Lampen aktuell noch synchronisiert werden, erscheint die Fehlermeldung und die Lampen reagieren nicht.
In diesem Zustand kann ich aber den Status auch nicht per Alexa oder über die HUE App selber wechseln. Ich muss hierfür zuerst in der Hue App wählen, dass die Synchronisierung aufhören soll.

Ich denke per HUE API sollte es möglich sein einen Befehl zu senden, dass die Synchronisation stoppen soll (sonst würden 3rd party addons dies ja auch nicht können). Ich habe diesbezüglich aber leider nichts gefunden.

**Comment by foxriver76** [comment]
Ich hätte erwartet, dass es gestoppt wird wenn man die jeweilige Entertainment Gruppe `on` -> false setzt. Nur anscheinend sagt das nur aus ob die Lampen darin an sind.

**Comment by wizzardking** [comment]
Das wäre mMn auch das naheliegendste Ergebnis. Philips hat sich dies aber anscheinend anders überlegt und möchte nicht, dass die Lampen manuell gesteuert werden können, so lange diese Synchronisiert sind.

**Comment by foxriver76** [comment]
Puh, gut wenn es externe steuern, villt läuft es wieder irgendwie über Rules, Softwareseitige Sensoren oder sowas. Du könntest mal den Adapter auf Debug stellen, und mir das ewig lange JSON schicken.

**Comment by foxriver76** [comment]
Btw. wie nutzt du diesen Entertainment Bereich, mit sowas hier: https://www2.meethue.com/de-de/p/hue-play-hdmi-sync-box/8718699704803 ?

**Comment by foxriver76** [comment]
Tritt das Problem noch mit Adapter Version > 3 auf? Falls ja, bitte mal Screenshots von den Objektordnern, die deine Entertainment Gruppe darstellen die zum synchronisieren genutzt wird. Und mal ein Debug Log Auszug, damit ich die Struktur der Gruppe sehen kann.

Ich denke hiermit https://github.com/peter-murray/node-hue-api/blob/master/docs/group.md#entertainment kann ich das Starten/Stoppen der Synchronistation realisieren.

**Comment by foxriver76** [comment]
Note:
class could be interesting + stream.active

```javascript
"10": {
      "name": "Entertainment-Bereich 1",
      "lights": [],
      "sensors": [],
      "type": "Entertainment",
      "state": {
        "all_on": false,
        "any_on": false
      },
      "recycle": false,
      "class": "TV",
      "stream": {
        "proxymode": "auto",
        "proxynode": "/bridge",
        "active": false,
        "owner": null
      },
      "locations": {},
      "action": {
        "on": false,
        "alert": "none"
      }
    }
```
