### ISSUE TITLE
Unable to set light state

### ISSUE THREAD

**Issue by Florian-Hoehne** [iobroker-community-adapters/ioBroker.hue#86]
I have issues to switch on a smart plug connected with the hue adapter.
To switch it on and off I used a script that worked well for months. But due to recent updates the hue adapter does not work anymore. Unfortunately I do not remember the last version before the update (sorry) but is there any hint to solve the issue. 

### The script
The plug operates a bell in my household. According to log the set state function fails.

```javascript
var timeout;
    const timeOff = 7000;

    var dev = 'hue.0.Philips_hue.Bell.on';
    setState(dev,true);

    let Text = 'Ding Dong! Es hat geklingelt!';

    sendTo("pushover", "send", {
        message: 'Haustürklingel wurde betätigt!',
        sound: "magic",
        priority: 1,
        title: 'Ring Haustür'
    });

    timeout = setTimeout(function () {
        setState(dev, false);
    }, timeOff);
```

My guess: that log the adapter tries to access a property that does not exist in the newer version.

![log](https://user-images.githubusercontent.com/26935996/69500023-d155e600-0ef7-11ea-9b68-08d240f40a76.png)

**Comment by foxriver76** [comment]
Existiert das Problem nach wie vor mit der neusten Version?
