### ISSUE TITLE
Wrong state of rooms

### ISSUE THREAD

**Issue by IchBinSmart** [iobroker-community-adapters/ioBroker.hue#88]
Rooms show the wrong level if not all lamps of that room are "on". 

E.g. 
One Lamp in LivingRoom is off => hue.0.LivingRoom.On will show false and hue.0.LivingRoom.Level will show zero, which is not correct and different to the level and state in the hue app.

Thx for the great work. The adapter is awesome!!!

**Comment by foxriver76** [comment]
In rooms there is an indicator called anyOn which tells you if any lamp is on. For level the API only provides one value.
