### ISSUE TITLE
Outdoor Motion sensor - Incorrect display of exactly zero degrees

### ISSUE THREAD

**Issue by aleks-83** [iobroker-community-adapters/ioBroker.hue#89]
The log of the datapoint **hue.0.Hue_outdoor_temperature_sensor_1.temperature** shows a weird behaviour.
When the sensor measures exactly zero degrees, the value becomes **.-6** instead of 0.00.
![image](https://user-images.githubusercontent.com/42573655/70320372-d33b7580-1824-11ea-9236-0980dd640c18.png)

Hue adapter 2.3.1
JS controller 2.1.0
Node.js v10.17.0
NPM 6.11.3

**Comment by foxriver76** [comment]
temperature conversion is done by 

```javascript
function convertTemperature(value) {
    if (value !== null) {
        value = value.toString();
        const last = value.substring(value.length - 2, value.length);
        const first = value.substring(0, value.length - 2);
        value = `${first}.${last}`;
    } else {
        value = '0';
    }
    return value;
}
```

When I run this code with a value of 0 or 00 it should do the job. Would be good to know which value we get from the hue bridge when this happens.

**Comment by aleks-83** [comment]
What about testing a value of 0.00?

**Comment by foxriver76** [comment]
My sensor delivers 1411 for 14.11 °C So I guess this is the pattern, but it won't make a difference anyway.

**Comment by foxriver76** [comment]
Please try 2.4.5, but I am not sure if this really was the problem.

**Comment by aleks-83** [comment]
OK thank you, I will test and report.

**Comment by foxriver76** [comment]
Better 2.4.6, I think I've found a potential issue when having negative numbers in temperature conversion

**Comment by aleks-83** [comment]
OK

**Comment by aleks-83** [comment]
Eventhough if my sensor didn't measure (or didn't show) exactly zero degrees, it seems to be working.

![2020-01-02 12_27_33-objects - ioBroker](https://user-images.githubusercontent.com/42573655/71664967-664fc880-2d5b-11ea-9aae-6015e94963ef.png)

**Comment by foxriver76** [comment]
Thanks for the feedback. If the issue occurs again, feel free to reopen this ticket.
