### ISSUE TITLE
Hue Gruppezustand/ Zustand einzelne Lampen in Gruppe

### ISSUE THREAD

**Issue by Ropdepil** [iobroker-community-adapters/ioBroker.hue#90]
Hallo,

mir ist folgendes Problem aufgefallen:

Wenn ich meine Gruppe Schlafzimmer (Schlafzimmer.on) ausschalte mit false, gehen die dazugehörigen Lampen aus. Wenn ich jetzt nun eine einzelne Lampe in dieser Gruppe Schlafzimmer einschalten will (bsp. Nachtischlampe), muss ich Nachtischlampe.on immer zweimal mit true betätigen, damit diese an geht. Dieses Verhalten ist bei allen Gruppen und Lampen

**Comment by foxriver76** [comment]
Wie schaltest du denn die Punkte? Und zeig mal das zugehörige Log am besten Loglevel debug. Kann/Sollte eigentlich nicht sein.

**Comment by Ropdepil** [comment]
<block xmlns="http://www.w3.org/1999/xhtml" type="timeouts_settimeout" id="hcd`G}UG:$Gp(8/etgC3" disabled="true" x="-366" y="1427">
  <field name="NAME">timeout</field>
  <field name="DELAY">10</field>
  <field name="UNIT">sec</field>
  <statement name="STATEMENT">
    <block type="control" id="%iXpI2UefeR(P(bnKC3]">
      <mutation delay_input="false"></mutation>
      <field name="OID">hue.0.Philips_hue.Wohnbereich.command</field>
      <field name="WITH_DELAY">FALSE</field>
      <value name="VALUE">
        <block type="text" id="jL5Tw/#uNq`i9WNp,CI:">
          <field name="TEXT">{"on":false,"transitiontime":0}</field>
        </block>
      </value>
      <next>
        <block type="control" id="Yl7UK+-58uZDJ{Y_E4^H">
          <mutation delay_input="false"></mutation>
          <field name="OID">hue.0.Philips_hue.Essbereich.command</field>
          <field name="WITH_DELAY">FALSE</field>
          <value name="VALUE">
            <block type="text" id="qxz@h}J5b;U*s|VEY@OF">
              <field name="TEXT">{"on":false,"transitiontime":0}</field>
            </block>
          </value>
          <next>
            <block type="control" id="}eGs^Cah90*`GSJjEb!N">
              <mutation delay_input="false"></mutation>
              <field name="OID">hue.0.Philips_hue.Betonwand.command</field>
              <field name="WITH_DELAY">FALSE</field>
              <value name="VALUE">
                <block type="text" id="9x(L*|)Jh{.j![!neixY">
                  <field name="TEXT">{"on":false,"transitiontime":0}</field>
                </block>
              </value>
              <next>
                <block type="control" id="5Wn|1$@_KR/wbU=PKNL3">
                  <mutation delay_input="false"></mutation>
                  <field name="OID">hue.0.Philips_hue.Flur.command</field>
                  <field name="WITH_DELAY">FALSE</field>
                  <value name="VALUE">
                    <block type="text" id=",bdE*cAm@CPtY4C/HD#}">
                      <field name="TEXT">{"on":false,"transitiontime":0}</field>
                    </block>
                  </value>
                  <next>
                    <block type="control" id="-1dow02o4_WIsC5]HHX-">
                      <mutation delay_input="false"></mutation>
                      <field name="OID">hue.0.Philips_hue.Küche.command</field>
                      <field name="WITH_DELAY">FALSE</field>
                      <value name="VALUE">
                        <block type="text" id="o1nw=lt+-ol/1otv.nLm">
                          <field name="TEXT">{"on":false,"transitiontime":0}</field>
                        </block>
                      </value>
                    </block>
                  </next>
                </block>
              </next>
            </block>
          </next>
        </block>
      </next>
    </block>
  </statement>
</block>

**Comment by foxriver76** [comment]
Wie schaltest du die Datenpunkte?

**Comment by Ropdepil** [comment]
Hallo tut mir leid. Hab jetzt mal geupdated und jetzt scheint es zu funktionieren, Ich schalte meist mit dem datenpunkt command und json. Mir ist zuvor aufgefallen wenn ich beispielweise das haus verlasse und einen taster betätige der alle hue Lampen ausmacht All.command {"on":false,"transitiontime":80}, dass ich danach andere lampen/bzw. Gruppen immer zweimal betätigen musste mit xx.command  {"on":true.....usw} 

jetzt nach dem Update oder vielleicht nach dem Neustart des Adapters scheint es zu funktionierne
