### ISSUE TITLE
Update auf v3.0.1 macht große Probleme mit node.js v8

### ISSUE THREAD

**Issue by ThmsD** [iobroker-community-adapters/ioBroker.hue#91]
Ich habe ein Update des Adapters auf 3.0.1 gemacht. Anschließend hat sich die Instanz nicht mehr mit der Bridge verbunden.
Im Log wird im Millisekunden takt folgendes geloggt:
```
2020-01-11 14:12:50.093  - [33mwarn[39m: host.ioBroker startInstance hue.0: required node.js version >=10, actual version v8.14.0
2020-01-11 14:12:50.094  - [33mwarn[39m: host.ioBroker startInstance hue.0: instance disabled because of node.js version mismatch
```
Ein Downgrade auf 2.5.0 ließ die Instanz des Adapters wieder ordnungsgemäß arbeiten und ioBroker funktionierte auch wieder flüssig.

Ein Hinweis im Changelog wäre toll gewesen.
Wird node.js >= v10 vorausgesetzt, oder könnte man v8 wieder mit aufnehmen?

**Comment by foxriver76** [comment]
Leider hat die Dependency die Abhängigkeit auf nodejs10. Changelog ergaenze ich, dass die Instanz im ms Takt abschmiert ist ein Controller Bug. Fix steht allerdings https://github.com/ioBroker/ioBroker.js-controller/pull/603

Edit: Allerdings kannst du gerne auf nodejs10 upgraden, 8 ist sowieso EOL und 10 ist auch die empfohlene Version für ioBroker.

**Comment by markuskobe** [comment]
Was ist der beste/einfachste Wege von node 8 auf 10 zu aktualisieren?

**Comment by Apollon77** [comment]
Zur Frage nach Update; https://forum.iobroker.net/topic/22867/how-to-node-js-f%C3%BCr-iobroker-richtig-updaten
