### ISSUE TITLE
States on, colormode springen nochmal zurück auf alten Zustand 

### ISSUE THREAD

**Issue by Ropdepil** [iobroker-community-adapters/ioBroker.hue#94]
Hallo,  
Bei mir springen die Zustände beispielsweise von on oder dem colormode bei schalten nochmal zurück auf den alten Zustand und dann auf den gewollten Zustand.
Beispiel:
On steht auf true. Schalte ich ihn auf false geht er kurz auf false dann kurz wieder auf true und dann wieder auf false. Dies geschieht auch beim colormode und level.
Version: 3.0.3
Viele Grüße

**Comment by foxriver76** [comment]
Umso niedriger das polling steht umso höher die Wahrscheinlichkeit dass das passiert. Allerdings kann ich es bei mir durch haendisches State setzen nicht nachstellen. Wie hoch steht das Polling? Und passiert es auch mit höheren polling Intervallen?

**Comment by Ropdepil** [comment]
Mein polling steht auf 1. werde ich mal ausprobieren ob es sich bessert wenn ich es erhöhe. Mir ist das nur irgendwie erst nach dem Update auf die Version aufgefallen.

**Comment by Ropdepil** [comment]
Hat sich tatsächlich verbessert. Hab den Wert jetzt auf 8 erhöht. Danke nochmal
