### ISSUE TITLE
Philips Hue Sync Box

### ISSUE THREAD

**Issue by wolltswurm** [iobroker-community-adapters/ioBroker.hue#95]
Is it possible to add the Philips Hue Sync Box?

-start and stop to sync
-change entertainment
-wake up the box from sleep

**Comment by foxriver76** [comment]
Yeah, I would love to. I recently tried to implement basic actions for this purpose. Due to the lack of testers, I have no clue if it works. I added a state `activeStream` to every entertainment group of the adapter. You can try if you can stop and maybe start the synchronization with this state.

**Comment by foxriver76** [comment]
For completeness: stopping the synchronization works with the adapter. Everything else needs the sync box api, thus see https://github.com/ioBroker/AdapterRequests/issues/324
