### ISSUE TITLE
Error in log: 'light id' is not optional

### ISSUE THREAD

**Issue by mswiege** [iobroker-community-adapters/ioBroker.hue#96]
**Describe the bug**
I have the following error in my logs suddenly. I don't know what changed when this started and also couldn't find anything that is not working anymore. 

```
hue.0 | 2020-01-25 11:53:08.922 | error | at process._tickCallback (internal/process/next_tick.js:68:7)
-- | -- | -- | --
hue.0 | 2020-01-25 11:53:08.922 | error | at getCachedState.then (/opt/iobroker/node_modules/node-hue-api/lib/api/Api.js:184:28)
hue.0 | 2020-01-25 11:53:08.922 | error | at Cache.getLight (/opt/iobroker/node_modules/node-hue-api/lib/api/stateCache.js:17:42)
hue.0 | 2020-01-25 11:53:08.922 | error | at LightIdPlaceholder.getValue (/opt/iobroker/node_modules/node-hue-api/lib/placeholders/Placeholder.js:42:27)
hue.0 | 2020-01-25 11:53:08.922 | error | at UInt16Type.getValue (/opt/iobroker/node_modules/node-hue-api/lib/types/RangedNumberType.js:25:31)
hue.0 | 2020-01-25 11:53:08.922 | error | at UInt16Type.getValue (/opt/iobroker/node_modules/node-hue-api/lib/types/Type.js:58:17)
hue.0 | 2020-01-25 11:53:08.922 | error | (7010) Uhandeld Rejection Error: No value provided and 'light id' is not optional at Error: No value provided and 'light id' is not optional
```

**Comment by foxriver76** [comment]
Adapter Version?

**Comment by mswiege** [comment]
Hue Adapter 3.1.1
IoBroker js-controller 2.2.7

I just update js-controller to 2.2.8 and until now the error didn't show up again. Maybe that fixed it?

**Comment by foxriver76** [comment]
Normally it shouldn’t. Please create a new user in the adapter settings once, because the mechanic in the api has changed.

**Comment by mswiege** [comment]
Created a new user, all was fine for one hour but then got again this error.

```
(17364) Uhandeld Rejection Error: No value provided and 'light id' is not optional at Error: No value provided and 'light id' is not optional
    at UInt16Type.getValue (/opt/iobroker/node_modules/node-hue-api/lib/types/Type.js:58:17)
    at UInt16Type.getValue (/opt/iobroker/node_modules/node-hue-api/lib/types/RangedNumberType.js:25:31)
    at LightIdPlaceholder.getValue (/opt/iobroker/node_modules/node-hue-api/lib/placeholders/Placeholder.js:42:27)
    at Cache.getLight (/opt/iobroker/node_modules/node-hue-api/lib/api/stateCache.js:17:42)
    at getCachedState.then (/opt/iobroker/node_modules/node-hue-api/lib/api/Api.js:184:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by foxriver76** [comment]
Would be helpful if you set the instance to debug until the errors appears again. Does it only appear when you try to control a light, otherwise it should appear on every polling. Maybe you (or a running script) is trying to control a light which is no longer present on your bridge.

**Comment by mswiege** [comment]
You are right! Thank you. 
I've switched to debug and that remembered me that one switch I toggle with a script I removed from the bridge some weeks ago. This was causing (reproducible) this error. So the only suggestion for code change could be to catch the crash and rather make an error log entry that the lamp with name X can not be found on the bridge anymore, so future users have it easier to figure out what is wrong.

**Comment by foxriver76** [comment]
Thanks for your feedback. Logging is more meaningful in 3.2.1 when updating a state fails.
Also when lights/groups/sensors are removed during runtime of the adapter, the info will be logged, that this device has been removed. Furthermore, if the controller supports recursive removage (js-c 2.2.8 and higher) the corresponding object will automatically be deleted.
