### ISSUE TITLE
TypeError: Cannot read property 'ack' of null

### ISSUE THREAD

**Issue by weiland** [iobroker-community-adapters/ioBroker.hue#97]
**Describe the bug**
When I tried to change any state of the light it never worked neither using the iobroker interface or any other iobroker interface.

**To Reproduce**
1. Go to 'iobroker Objects'
2. Click on 'hue.0' (and other subfolders)
3. Try to change any state of a light bulb
4. It turnes red and the following error log appears:

**Stacktrace**
```
hue.0 | 2020-02-20 09:46:33.143 | error | at process._tickCallback (internal/process/next_tick.js:68:7)
-- | -- | -- | --
hue.0 | 2020-02-20 09:46:33.143 | error | at promise.then (/opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49)
hue.0 | 2020-02-20 09:46:33.143 | error | at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
hue.0 | 2020-02-20 09:46:33.143 | error | at client.mget (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:619:13)
hue.0 | 2020-02-20 09:46:33.143 | error | at states.getStates (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5922:17)
hue.0 | 2020-02-20 09:46:33.143 | error | at adapter.getStates (/opt/iobroker/node_modules/iobroker.hue/main.js:207:17)
hue.0 | 2020-02-20 09:46:33.143 | error | at handleParam (/opt/iobroker/node_modules/iobroker.hue/main.js:132:55)
hue.0 | 2020-02-20 09:46:33.143 | error | (12215) TypeError: Cannot read property 'ack' of null
hue.0 | 2020-02-20 09:46:33.143 | error | (12215) uncaught exception: Cannot read property 'ack' of null
```

**Expected behavior**
The light bulb should turned on and the stat in ioBroker should not be red.

**Screenshots & Logfiles**
See Stacktrace above.
There seems to a null-case in line 132 of `main.js`.

**Versions:**
 - Adapter version: 3.2.2
 - JS-Controller version: iobroker.admin 4.0.3
 - Node version: 10.18.1
 - Operating system: Raspbian 10.2
 - Bridge model: <bridge-model>

**Additional context**
I already prepared a PR which catches the `null` and made it working again for me.

**Comment by foxriver76** [comment]
Had a short look at it, all in all it seems that `getStates` https://github.com/ioBroker/ioBroker.js-controller/blob/15205d49eb402fba6d6471f38e6fbc472ff0b220/lib/adapter.js#L6059 returned the Object which contained `<id>.command`as a `key` but the corresponding value was `null`.

**Comment by Apollon77** [comment]
which is a valid response since js-controller 2.x ... it was "undefined" before (when you not used redis).

**Comment by foxriver76** [comment]
Probably thats the reason why it 'never' happend in the past. It's fine. just wanted to know why it just came up now ;-)

**Comment by Apollon77** [comment]
In this case the state had no value. It can happen directly if you "Kill" your state DB (or it gets corrupt) or such ... so because of a reason the state value was killed ...
